### ISSUE TITLE
Antivirus Bitdefender blocks setup 2.10

### ISSUE THREAD

**Issue by dcpc007** [Razviar/mtgap#1]
at installation, alert :

Le fichier C:\Users\Shadow\AppData\Local\mtgaprotracker\app-2.0.10\resources\app\.webpack\main\native_modules\fastlist.exe est infecté par DeepScan:Generic.Malware.P!Pk!.8D451706 et a été placé en quarantaine. Nous vous recommandons d'effectuer une analyse du système afin de vérifier que votre système est sain.

**Comment by Razviar** [comment]
Hello! It's false alarm, because of the very nature of tracking software.
The code of app is signed by encryption certificate and obviously it's not
virus.

пт, 22 нояб. 2019 г. в 20:05, dcpc007 <notifications@github.com>:

**Comment by Razviar** [comment]
Can you verify with 2.0.14 ?

**Comment by dcpc007** [comment]
used on 2.0.15 : Ok

**Comment by Razviar** [comment]
Glad to hear that, thank you! It means that trust is building up and now
antivirus software doesn't give false positives.

пн, 9 дек. 2019 г. в 14:32, dcpc007 <notifications@github.com>:
