### ISSUE TITLE
mtgaprotracker.exe keeps trying to create Update.exe

### ISSUE THREAD

**Issue by jeohist** [Razviar/mtgap#10]
**Describe the bug**
mtgaprotracker.exe keeps trying to create Update.exe. Specifically:

CreateFile
QueryBasicInformation
CloseFile

In 20 seconds it did this approximately 35k times. CPU was constantly at 25-50%, RAM was around 7GiB in use. This happened after I auto-updated. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 1909 18363.476
 - Browser N/A
 - Version 2.0.14

**Additional context**
I can upload a brief PML of what was happening if requested.

**Comment by Razviar** [comment]
Is there some antivirus or firewall interrupting this process? Actually we didn't code updates but just use squirrel+electron boilerplate. So I can't tell anything specific about that

**Comment by jeohist** [comment]
No, I didn't see any activity from Windows Defender at the time, I'm not running any other software that might interfere. I'll see if I can reproduce it at the next update.

**Comment by Razviar** [comment]
Please let me know. Most likely we'll release next update tomorrow

**Comment by Razviar** [comment]
Sorry for late response, you've mentioned some additional logs, can you share those to help us debug this issue
