### ISSUE TITLE
Unknown issue with `Sync Old Logs` feature

### ISSUE THREAD

**Issue by MiguelNoronha** [Razviar/mtgap#100]
**Detailed context (ISSUES WILL NOT BE INVESIGATED WITHOUT IT!):**
- Link to your MTGA Pro account: https://mtgarena.pro/u/Sahfire.171903
- Link to page/pages are in question
- Screenshots of issue if applicable 

**Your Desktop:**
 - OS: Windows 10 B17763
 - App Version 2.0.40

**Describe the bug**
Whenever I use the `Sync Old Logs` feature, I get a successful message, but my match history (from before the installation of MTGA.Pro) does not update.
I've followed the guidelines in [TRACKER IS NOT UPDATING?](https://mtgarena.pro/mtga-pro-tracker/), but there were no changes in the results:

1. Latest Version of the tracker ✔️
2. WIPE SETTINGS ✔️
3. Restart MTGA, tracker and PC ✔️
4. Manual Update ✔️
5. Check blocked traffic ✔️
    - Used Wireshark to track the TCP exchanges

**To Reproduce**
1. Open MTGA and MTGA.Pro
2. Use `Sync Old Logs` button
3. Wait for success message
4. Check [Match History](https://mtgarena.pro/matches/?Sahfire.171903)
5. History not updated - Cry
6. Test live sync of MTGA.Pro by having a new match
7. Check [Match History](https://mtgarena.pro/matches/?Sahfire.171903)
8. History updated

**Screenshots**

Steps for attempted resolution of issue:
![chrome_IVen7R1GZM](https://user-images.githubusercontent.com/5839485/78456285-a7c57c00-769a-11ea-8197-7c25a03febc2.png)

Attempt ot use `Sync Old Logs`:
![MTGA_d9cexphvcm](https://user-images.githubusercontent.com/5839485/78456287-a85e1280-769a-11ea-83a3-96e05b63a439.png)

Wireshark data (pasted to csv to remove other traffic and hide my IP):
![EXCEL_vbRHWv2rWF](https://user-images.githubusercontent.com/5839485/78456283-a6944f00-769a-11ea-8110-68632aea5de0.png)

Match History after 1 new match:
![chrome_1bE6s948Ob](https://user-images.githubusercontent.com/5839485/78456286-a7c57c00-769a-11ea-8041-948f679a0cae.png)

**Comment by Razviar** [comment]
Thanks for detailed bug report. How old are those logs? Did you had tracker already running while those logs were generated? In fact, there's numerous reasons why old logs may not get parsed, and this function is not guaranteed. We still working on it

**Comment by MiguelNoronha** [comment]
👋
I installed the tracker this morning, and was hopping to look at the logs from last night, was playing from for about 7 hours on the FNM event xD
Some of the logs are a bit older than that, but the latest before the tracker was installed was indeed the one from last night
Cheers

**Comment by Razviar** [comment]
Can you please drop over some log samples?

**Comment by MiguelNoronha** [comment]
[UTC_Log - 04-03-2020 22.55.46.log](https://github.com/Razviar/mtgap/files/4432258/UTC_Log.-.04-03-2020.22.55.46.log)

**Comment by Razviar** [comment]
Thanks, we will look into it

**Comment by Razviar** [comment]
You had detailed logs disabled back then. 
**[615865] DETAILED LOGS: DISABLED**
Tracker automatically ignores logs with detailed logs disabled.

**Comment by MiguelNoronha** [comment]
😢
totally missed that detail
sorry for wasting your time 🙇

**Comment by Razviar** [comment]
@MiguelNoronha no problem, better double check then miss bug
