### ISSUE TITLE
Events match link has more matches than matches page

### ISSUE THREAD

**Issue by ineffablebob** [Razviar/mtgap#101]
Account: mtga.cc/u/ineffablebob
Events page: https://mtgarena.pro/events/#event-QuickDraft_THB_20200319
Matches page (for specific event): https://mtgarena.pro/matches/?ineffablebob#event-1144272
Matches page (for the days of the event): https://mtgarena.pro/matches/#historyfrom-28-03-2020;historyto-29-03-2020;srt-1;direct-2

My setup: Windows 10, app version 2.0.40

Description:
If you go to the events page and click on the Matches link from a specific event, the resulting Matches page shows all the matches from the event. But if you go to the Matches page from the menu and then select the same timeframe as the event, there's only a partial list.

Example: The screenshot EventMatchList is from the link for event 1144272 above. It shows 8 games, all from March 28-29. The screenshot DateMatchList is from the match page searching by date. It shows only two games from those same days.

![EventMatchList](https://user-images.githubusercontent.com/15248914/79339273-a4ca5700-7ef6-11ea-8b44-2f57f267b818.png)
![DateMatchList](https://user-images.githubusercontent.com/15248914/79339278-a5fb8400-7ef6-11ea-80c7-0cb52d92a3dc.png)

This is important since it prevents the win/loss stats on the Matches page from being accurate. For instance, the Matches page stats are wrong for overall win/loss for all Limited games because only some of the matches are showing up. My guess is that the query used by the Matches page when searching by date is somehow missing a bunch of the games that are in the database, while the query used when searching by event ID works properly.

**Comment by ineffablebob** [comment]
Note that this is different from issue #86. That one is about matches not tracked at all. In this issue, the matches are there - we know that since they show up in matches list by event ID - but they're not showing up for some reason when searching by criteria other than event ID.

**Comment by Razviar** [comment]
Thanks for reporting! Now it's fixed.
Also we found root reason: it was opponent rank. System was hiding by default matches where opponent rank is missing. Currently we also fixed the bug causing lost data about opponent ranks. But obviously old matches will stay as is, with missing ranks.
