### ISSUE TITLE
"mtgarena.pro/stats/" & "Lifetime W/L Ratio" are empty

### ISSUE THREAD

**Issue by outrullers** [Razviar/mtgap#102]
tracker version 2.0.42

profile: mtga.cc/u/outrullers.172171

problem: My "mtgarena.pro/stats/" is empty and "Lifetime W/L Ratio: 0%"

![2020-04-15_23-44-47](https://user-images.githubusercontent.com/28491840/79386644-1e078f80-7f73-11ea-823c-0760dea5bd18.png)
![2020-04-15_23-43-50](https://user-images.githubusercontent.com/28491840/79386647-1fd15300-7f73-11ea-8c91-2c394acaabb3.png)

**Comment by outrullers** [comment]
tracker v.2.0.42

**Comment by Razviar** [comment]
Lifetime wl ratio is temporarily disable. You can see wl on matches page m As for statistics, we'll look into it

**Comment by outrullers** [comment]
It`s ok with "Lifetime wl ratio"
Looking forward to working personal stats )
Tank you!

**Comment by Razviar** [comment]
Can you please try to open https://mtgarena.pro/stats/#outrullers.172171 in guest mode? I can see it rendering.

If it does render for you, please take a screenshot of your stats page with open console (ctrl+shift+i)

**Comment by outrullers** [comment]
![2020-04-20_10-59-28](https://user-images.githubusercontent.com/28491840/79728100-0f640400-82f6-11ea-9fbb-ca9ab01c1215.png)
it does render in guest mode

P.S.: and it does it with ads, sorry )

**Comment by outrullers** [comment]
<img width="492" alt="2020-04-20_11-44-59" src="https://user-images.githubusercontent.com/28491840/79732786-d54a3080-82fc-11ea-8b36-73c4378a96ab.png">
That`s with console opened
"Failed to load resource: net::ERR_BLOCKED_BY_CLIENT"
I think it is someting on my side that prevents it from loading?

**Comment by outrullers** [comment]
Ok, I got it. It is an issue with adblocker.
I can see stats page in Edge without 3d-party adblocers.
But in Chrome I have adblocker installed and stats are not shown (even when the page in white list)

**Comment by Razviar** [comment]
Well, you should white-list our site in ad-block then.
