### ISSUE TITLE
Linked my MTGA to wrong random MTGApro account 

### ISSUE THREAD

**Issue by philajar** [Razviar/mtgap#104]
**Detailed context (ISSUES WILL NOT BE INVESIGATED WITHOUT IT!):**
- Link to your MTGA Pro account: https://mtgarena.pro/u/Sabrevolt.174753
- Screenshots of issue if applicable 
![image](https://user-images.githubusercontent.com/63880296/79613349-38488700-80b3-11ea-85dd-1e02e68ca027.png)

**Your Desktop:**
 - OS: Windows 10 Enterprise
 - App version v2.0.42

**Describe the bug**
 App linked my MTGA game account to a random MTGAPro account that is not mine. 

**To Reproduce**
Steps to produced the behavior:
1. Created MTGApro account. logged in to account in Chrome. https://mtgarena.pro/u/Sabrevolt.174753
2. Downloaded and installed MTGAPro APP. 
3. Logged in to MTGA and enabled log collection.
4. Attempted to link accounts in MTGAPro APP. 
It opened a window in default browser Internet Explorer. gave error message about not being logged in. No one was logged into a MTGAPro account in Internet Explorer.
5. MTGAPro APP is now linked to a BumbleBeeast.174775 MTGAPro account instead of mine (Sabrevolt.174753). No one else uses this computer and no one was logged into a MTGAPro account in Internet explorer. Token 4744f4ef
![image](https://user-images.githubusercontent.com/63880296/79614167-d6891c80-80b4-11ea-9b2f-3f4fa0dfb007.png)

6. Tried to use UNLINK action in MTGAPro APP and it opens IE and gives Invalid request error.
![image](https://user-images.githubusercontent.com/63880296/79614059-9aee5280-80b4-11ea-96ba-b9abcd608adf.png)

**Comment by Razviar** [comment]
Try to go to settings tab and click "wipe settings", then try to repeat sync process again.

**Comment by Razviar** [comment]
Server side bug was fixed, now you just need to re sync your account after settings wipe. Closing this
