### ISSUE TITLE
tracker is not updating (yeah i know, probably a noob thing...)

### ISSUE THREAD

**Issue by aBystander295** [Razviar/mtgap#105]
**Detailed context (ISSUES WILL NOT BE INVESIGATED WITHOUT IT!):**
- https://mtgarena.pro/u/aBystander-67475.175021/
- mtga.cc/progress/?aBystander-67475.175021

**Your Desktop:**
 - OS: Windows 10
 - AppVersion: 2.0.43

**Describe the bug**
- haven't played in a long time...
- the app is correctly Syncd but my collection doesn't show up on the server
- have uninstalled and reinstalled MTGA and the app, wiped the setting... 
- the detailed log are enabled
- i nuked my old  MTGA pro account and created a new one, the app is synced to the new one but nothing get to the server
- i have openened my firewall for mtgaprotraker

![image](https://user-images.githubusercontent.com/63911054/79638456-aa899c00-8185-11ea-9ef0-892101311f9a.png)

[output_log.zip](https://github.com/Razviar/mtgap/files/4496674/output_log.zip)

am i the only one with this issue?

**Comment by Razviar** [comment]
Thanks for reporting, we will investigate

**Comment by Razviar** [comment]
I just uploaded your log from my PC in test mode, and all data got into your account. So it's something weird. You should try to uninstall tracker and manually remove folder C:\Users\{USERNAME}\AppData\Roaming\MtgaProTracker then try installing and syncing again.

**Comment by aBystander295** [comment]
it worked, thanks!!
