### ISSUE TITLE
Error: Issue with MTGA path access

### ISSUE THREAD

**Issue by Rocklicker** [Razviar/mtgap#106]
Error: Issue with MTGA path access...

I have tried to locate the folder or file. Nothing works.

The tracker was working perfect before the release of the new cards on 4/16/20 and has not worked since no matter the version or update.

I have been using the tracker for over a year. 

V2.0.43
Windows 10

**Comment by Razviar** [comment]
Well you need to make sure nothing is blocking access to mtga path to the app: firewalls, antivirus etc.

**Comment by Razviar** [comment]
Also can you verify Settings tab? In "MTGA Path" section there should be the path to your MTGA installation location, where MTGA.exe resides.

**Comment by Rocklicker** [comment]
no path. Say Unknown! in red above the box and says Locate MTGA in box. I have not changed any settings or programs other than update magic and the tracker.

**Comment by Razviar** [comment]
Then you should locate game installation folder

**Comment by Rocklicker** [comment]
OK, finally got it to work! TY

**Comment by Rocklicker** [comment]
Ok, got that part fixed. Now it is stuck. Awaiting User Credentials in log (might take 5-30 seconds) 
Log path is set to default and says it is fine do not tinker with it.

**Comment by Razviar** [comment]
It was for you to start mtga and login with some account

**Comment by Rocklicker** [comment]
Ok, seems to be working after some steps to sync. TY
