### ISSUE TITLE
In-game overlay cannot show my deck and opponent deck

### ISSUE THREAD

**Issue by tinyau** [Razviar/mtgap#107]
**Detailed context (ISSUES WILL NOT BE INVESIGATED WITHOUT IT!):**
- Link to your MTGA Pro account - https://mtgarena.pro/u/tinyau

**Your Desktop:**
 - OS: Windows 10 Professional 
 - App Version: 2.0.43

**Describe the bug**
In-game overlay cannot show my deck and opponent deck

**To Reproduce**
1. Enable Overlay
2. Start MTG Arena
3. Enable show my deck and opponent deck
4. Start a match in either "Play" or "Standard Ranked"
5. No card is shown whenever my opponent or I play a card

**Comment by Razviar** [comment]
Please try 2.0.47 and check if it helped
