### ISSUE TITLE
wrong old link on the homepage

### ISSUE THREAD

**Issue by TaZi-loh** [Razviar/mtgap#108]
**Detailed context:**
- Link to page are in question: [bugs and suggestions](https://mtgarena.pro/bugs-and-suggestions/)

**Describe the bug**
On the mentioned page it is written:
"The best way to report bug or submit and discuss feature request is on our GitHub."
The word "GitHub" is linked, however not to this GitHub repo but to the old archived one.

Thought somebody might want to change that.

**Comment by Razviar** [comment]
Fixed, thanks for noticing
