### ISSUE TITLE
Web site: My Decks W/L sort not working as expected

### ISSUE THREAD

**Issue by Tr0ll13n** [Razviar/mtgap#11]
**Describe the bug**
On web site, in My Decks section, clicking on W/L column header doesn't seem to be sorting the decks in a proper way.

**To Reproduce**
1. Go to web site / My Arena / My Decks
2. Click on W/L column header
4. Decks are not sorted according to W/L ratio

**Expected behavior**
You would expect the decks to be sorted by W/L ratio, including when you select the various options (last 30 days, color, terrain,...).

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
This was present a few weeks ago then has been fixed. Reappered again.

**Comment by fueled13** [comment]
Can confirm this is still an issue as of January 2020.

**Comment by Razviar** [comment]
We are working on it

**Comment by Tr0ll13n** [comment]
Hello Ravziar, do you have an ETA for this fix ?

**Comment by Razviar** [comment]
No, we don't. I'll try to increase priority if this issue

**Comment by Tr0ll13n** [comment]
Well, the feature is very handy when you have a lot of decks, so if you could do something that would be awesome m8. Cheers!

**Comment by Razviar** [comment]
Fix has finally been delivered.

**Comment by Tr0ll13n** [comment]
Tested a few minutes ago, doesn't seem to be working.

**Comment by Razviar** [comment]
Try again, maybe you had cached version

**Comment by Tr0ll13n** [comment]
Yep, working now after reloging. Thx for fixing this m8.
