### ISSUE TITLE
The result of the last match doesn't seem to be reflected in the profile.

### ISSUE THREAD

**Issue by stormcat664** [Razviar/mtgap#110]
sample: mtga.cc/u/sai.92020
![image](https://user-images.githubusercontent.com/52299273/80194206-fd1afa80-8654-11ea-98c1-0a475a772875.png)
![image](https://user-images.githubusercontent.com/52299273/80193730-50d91400-8654-11ea-9fcf-15bec214c3ec.png)

**Describe the bug**
The result of the last match doesn't seem to be reflected in the profile.
It was happening yesterday. (I went 7-2 in Quick draft, but the indication was 6-2.)

**Comment by Razviar** [comment]
Applied patch, should be working fine for new events.
