### ISSUE TITLE
Deleted decks will be reinstated.

### ISSUE THREAD

**Issue by stormcat664** [Razviar/mtgap#111]
**Describe the bug**
After deleting a deck from My Decks, it show something like the image below, or the details of the deck.
![image](https://user-images.githubusercontent.com/52299273/80194907-12dcef80-8656-11ea-9735-553cd982aa74.png)
Then, when I open My Decks again, I find that the deck I deleted has been put back together.

**Comment by Razviar** [comment]
If the deck is present in MTGA, it will get resurrected every time you launch the game. You can't partially unlink some decks.
