### ISSUE TITLE
bugged since ikra

### ISSUE THREAD

**Issue by candybomberz** [Razviar/mtgap#112]
**Detailed context (ISSUES WILL NOT BE INVESIGATED WITHOUT IT!):**
- mtga.cc/u/candybomberz
- http://prntscr.com/s5prjg 

**Your Desktop:**
 - OS: windows 8.1 Pro N 64bit
 - App Version 2.0.43

**Describe the bug**
tracker isn't working, shows the message "error: Issue with MTGA path access"

**To Reproduce**
This is bugged since the ikra release.
I am from EU germany.
my mtg arena is installed in the following folder
H:\Games\mtg arena\MTGArena

**Comment by Razviar** [comment]
It means tracker can't get access to your MTGA installation. You need to:
1. Make sure path to MTGA is correctly set in settings
2. Make sure nothing is preventing the app to get access there. For instance, you can try to run tracker in admin mode to see of problem will be resolved.

**Comment by candybomberz** [comment]
Problem resolved, I reinstalled mtga pro and set the path and now it's working again.
