### ISSUE TITLE
Wrong account's collection synced after switching arena accounts

### ISSUE THREAD

**Issue by Birne94** [Razviar/mtgap#114]
**Detailed context (ISSUES WILL NOT BE INVESIGATED WITHOUT IT!):**
https://mtgarena.pro/u/Birne94.175644/
https://mtgarena.pro/progress/?Birne94.175644#tab-Collection

**Your Desktop:**
 - OS: Windows 10 
 - App Version: 2.0.43

**Describe the bug**
Yesterday, I had a friend of mine log into their account from my PC while the tracker was running. Since then, the website shows my friend's collection instead of mine. This makes some features like browsing craftable decks or the craftlist unusable. The vault progression was updated accordingly, however.

I have already tried to wipe all settings or syncing the old logs again. The "Accounts" page in the app only shows my account, no trace of my friend's.

**To Reproduce**
- Have the tracker running in the background
- Play on an account (linked)
- Switch to another account (not linked)
- Switch back to the original account
- => profile shows wrong collection

**Comment by Razviar** [comment]
Closing in favor of #113

**Comment by Razviar** [comment]
Unfortunately, we can't fix account which was damaged (like undo wrong data). We can fix this issue to avoid such errors in future tho

**Comment by Razviar** [comment]
We deployed v.2.0.44 containing fix for this issue. From now on it should separate data from the accounts. But unfortunately all messed up accounts with mixed data are beyond fixing.
