### ISSUE TITLE
new feature suggestion

### ISSUE THREAD

**Issue by Amigatsu** [Razviar/mtgap#115]
my idea is a spectate feature
the idea is so you could see if your friend is in a battle and spectate it
i want it because when im with my friends I want to see the battle their in and cheer them and stuff

maybe what it will do is that when a friend is on battle besides or below the name it will say like "on battle" or something like that then when you click it it wil show the option to spectate the battle their in

**Comment by Razviar** [comment]
This is 3rd party tool git, you should address this to game developers
