### ISSUE TITLE
Deleting decks from My Decks takes a random amount of tries

### ISSUE THREAD

**Issue by bqback** [Razviar/mtgap#116]
**Detailed context (ISSUES WILL NOT BE INVESIGATED WITHOUT IT!):**
- Profile: mtga.cc/u/Liandry
- Page: https://mtgarena.pro/decks/?my

**Your Desktop:**
 - OS: Windows 10

**Describe the bug**
Pressing the Delete Deck button always gives a "deck got lost somewhere" error, and only sometimes deletes the deck.

**To Reproduce**
1. Go to My Decks
2. Click on Delete Deck buton of any deck
3. Confirm that you want to do this
4. See error 'Deck [deck ID] got lost somewhere'
5. Go back to My Decks and *maybe* see it's gone

**Comment by Razviar** [comment]
Issue fixed
