### ISSUE TITLE
Error: enable detailed logs, but detailed logs enabled

### ISSUE THREAD

**Issue by lesf0** [Razviar/mtgap#117]
**Detailed context (ISSUES WILL NOT BE INVESIGATED WITHOUT IT!):**
- Link to your MTGA Pro account
- Link to page/pages are in question
- Screenshots of issue if applicable 

**Your Desktop:**
 - OS: ArchLinux, Wine 5.4
 - App Version 2.0.27-1 (aur)

**Describe the bug**
Detailed log is enabled in mtga settings, but tracker still shows that error message. Tried to restart mtga and tracker. Tried to remove log file. Tried to disable and then enable detailed log.  
Example log is there: [output_log.zip](https://github.com/Razviar/mtgap/files/4599613/output_log.zip)

**To Reproduce**

**Comment by Razviar** [comment]
Try to go to settings tab and locate log manually.

**Comment by lesf0** [comment]
> Try to go to settings tab and locate log manually.

Already did it, there was "log file not found" before. Log file seems to be detected correctly because app is able to detect whether mtga is currently started or not.

**Comment by Razviar** [comment]
No, app detects if game is running by locating process in memory, not log file. You need to locate it manually. Click button "LOCATE LOG" and you need to show the path to output_log.txt. IMPORTANT! Do not set path to program files there, only to log in appdata folder.

**Comment by lesf0** [comment]
I've already did locate that file in appdata directory

**Comment by Razviar** [comment]
So you set correct path to log in the app?

**Comment by lesf0** [comment]
Yes, I set correct path to the exact file I attached above.

**Comment by Razviar** [comment]
Can you please check with new 2.0.48 version?

**Comment by lesf0** [comment]
I will check it once AUR package is updated, thank you

**Comment by lesf0** [comment]
AUR maintainer said he'd already applied fix from 2.0.48 to his current 2.0.47 version, so I've tried it. Problem is gone, log is being parsed correctly

**Comment by Razviar** [comment]
@lesf0 I'm sorry for dumb question, what is aur?

**Comment by lesf0** [comment]
https://aur.archlinux.org/ , an user-provided package repository for archlinux.

**Comment by Razviar** [comment]
@lesf0 ah, get it, thanks
