### ISSUE TITLE
Can't see profile, settings, etc. on Web Version

### ISSUE THREAD

**Issue by riesen25** [Razviar/mtgap#118]
**Profile**
- [https://mtgarena.pro/u/riesen25](https://mtgarena.pro/u/riesen25)

**Your Desktop:**
 - OS: Windows 10
 - App Version 2.0.45

**Describe the bug**
I cannot get to [https://mtgarena.pro/u/](https://mtgarena.pro/u) as is just shows a blank page. I cannot reset the account (which I think needs to happen) because the tool to do so is on this page. Pretty much all the links under the "My Arena" menu load a blank page while I am logged in. If I log out, I can see my user page as a visitor. Is it possible to delete the account so I can start over or reset it on the back end?

**To Reproduce**
1. Log in
2. Click on My Areana > Profile 
3. See Blank Page (with background only)

**Comment by Razviar** [comment]
Please take a screenshot of open console when you on that page

**Comment by Razviar** [comment]
Your account have been fixed.

**Comment by riesen25** [comment]
Everything is working now! Thanks and glad to help!
