### ISSUE TITLE
Overlay not showing cards during match

### ISSUE THREAD

**Issue by stormsson** [Razviar/mtgap#119]
**Detailed context**
- https://mtgarena.pro/u/stormsson 

**Your Desktop:**
 - OS: Windows 8.1
 - App Version 2.0.45

**Describe the bug**
No cards are shown during the match.
Full logs are enabled, "enable overlay" option is active

**To Reproduce**
    

1. Enable Overlay
2.     Start MTG Arena
3.     Enable show my deck and opponent deck
4.     Start a match in either "Play" or "Standard Ranked"
5.     No card is shown whenever my opponent or I play a card

**Comment by Razviar** [comment]
Can you please test v.2.0.48 ? We have made some fixes.

**Comment by stormsson** [comment]
Hello @Razviar , tested with .48, nothing changed :( 
is there some application log/something else i could attach?

**Comment by Razviar** [comment]
Ah, sorry, I just noticed that you have win 8. Tracker works only on win10

**Comment by stormsson** [comment]
@Razviar sorry to bother again, do you happen to have any hint/code areas about what causes win8 to be not compatible ? (I'd like to check on my own if maybe I could ever be able to fork and fix it)
