### ISSUE TITLE
Not parsing Logs

### ISSUE THREAD

**Issue by Soujds** [Razviar/mtgap#124]
Hello

I've udpated the tracker on the 21st and it hasn't parsed any log since then.

I've triyed the "sinc old logs" but it skip all.

![image](https://user-images.githubusercontent.com/65915968/82832798-75771480-9ebc-11ea-834b-0a248ed0d21a.png)

Tryed to uninstall and install again, reset tracker and client but it's not working.

Did anyone have the same issue?

Thanks in advance

**Comment by Razviar** [comment]
Have you tried to wipe settings?
