### ISSUE TITLE
Mouse stutters/pauses briefly when moving around the screen

### ISSUE THREAD

**Issue by Rokkr-0** [Razviar/mtgap#129]
**Detailed context (ISSUES WILL NOT BE INVESIGATED WITHOUT IT!):**
- mtga.cc/u/Rokkr

Here's a link to a recording of the issue:
[https://youtu.be/EekDAwO4qug](https://youtu.be/EekDAwO4qug)

**Your Desktop:**
 - Windows 10
-  Tracker 2.0.48
 - MTGA v2213.786053

**Describe the bug**
About 20 seconds after the game loads to the main menu, the mouse stutters/pauses briefly when moving around the screen. 

Issue persists in ever other screen of the game.

The issue **does not occur** when running the game **without the Tracker**.

**To Reproduce**
1. Launch the Tracker
2. Launch the game
3. Wait for about 20 seconds after the game menu loads
4. Observe stuttering/stalling mouse.

**Comment by Razviar** [comment]
We attempted to reproduce on different PCs and weren't able. What PC specs do you have? Looks like it's overall performance issue

**Comment by Rokkr-0** [comment]
Thanks for looking into this and responding, I really like the program and this issue has made it unusable for me. Also, I've been playing every day for the last few weeks and the issue did not happen until the most recent update.

I'll try reinstalling the program in case something weird happened during the recent update. In the meantime, my specs are below:

Win10 Pro
32GB RAM
i9-9900K
GeForce RTX 2080 Ti 11GB

**Comment by Razviar** [comment]
Try to wipe settings, it might help more than reinstall. In fact your hardware should be more than enough, so it's definitely something wrong

**Comment by Razviar** [comment]
Another thing to check is tracker app folder. Please verify if there's any error logs in there

**Comment by Rokkr-0** [comment]
Reinstalling it was the fix. When I narrowed it down to the app I tried clearing the settings and it didn't help, but the reinstall did the trick. Thanks for your help!

**Comment by gianfr80** [comment]
I have the exact same problem, it started with 2.0.47 an continued with .48
I have a notebook, an a PC , both same problem
one has Nvidia 940mx with  Intel i5 7th generation 8 gig ram, an the other  Ati 290x i7 4990k with 32 gig ram

the problem its when you turn on the overlay, once on, start the problem an youe have to kill the tracker. 

Have updated driver, antivirus, reinstalled the game, on 3 diferent HDD an SSD, unninstalled via windows the tracker, an reinstaller, wipped data, i dont know what else todo, 
But when go back to 2.0.46 an turn off auto update i can use it..

**Comment by Razviar** [comment]
Looks like there's some other users having this issue, we will keep investigating

**Comment by gianfr80** [comment]
> Reinstalling it was the fix. When I narrowed it down to the app I tried clearing the settings and it didn't help, but the reinstall did the trick. Thanks for your help!

Can you tell me exactly your steps to fix it?

did you first wipe data, close de tracker, an then reinstall?
or did you wipe, ununstall an then reinstall
or just unnninstal an the n install
or no wipe or uninnistal an just reinstall over 

please step by setp.. i m stuck

**Comment by Razviar** [comment]
Anyone who's still affected, please grab experimental version here: https://dropmefiles.com/ZCmpR
And let me know if it helps. If it does, we'll push it to release.

**Comment by Razviar** [comment]
What a relief for me to announce that just deployed 2.0.50 resolves this issue.
