### ISSUE TITLE
web site "crafter" have does not aligned with collection

### ISSUE THREAD

**Issue by iknowwhatismyname** [Razviar/mtgap#132]
Hi MTGA Pro team,

I'm using the crafter/Deck Crafting Adviser to track my next packs to buy and I review the columns "have".
For example, "Luminous Broodmoth" have 0 and need 4.
If I go in collection and search for this card, I see I have really 4 cards as in MTGA. 
So the crafter looks to have a bug and not use the most updated "collection" .
I hope you can fix this and this is influencing my next pages to get.
Thanks and continue your great work.

iknowwhatismyname#52295

**Comment by Razviar** [comment]
Have you tried to ctrl+f5 or clear cache in browser settings?

**Comment by iknowwhatismyname** [comment]
Hi Raviar,

It does not to be client side related. I see same behavior in another browser or in incognito mode. 

Digging a bit, 5808 looks to be the id for  "Luminous Broodmoth"
Looking at https://mtgarena.pro/mtg/do3.php?cmd=getuserdata response
for collection : 5808 {ic: "4", ir: 0, it: 4}  but collectionhistory higher bracket is [5200 … 5258].

https://mtgarena.pro/mtg/do3.php?cmd=boosteradv response is
missingcards/ 5808: {indecks: "2", missing: "4", have: "0", reprint: "0", expansion: "90", rarity: "4", cardid: "21",…}

I use   "Luminous Broodmoth" as example as it is one. On non Ikoria, I see 'The Circle of Loyalty' that reports 4 in collection (and in mtga) and 3 in the "have" column of crafter, 
"Ashiok, Sculptor of Fears" reports 3 in collections and 2 in the "have" column of crafter.
It feel the gaps is 2-3 months and affects cards that was crafted or opened in a pack during that time, so more recents are the cards the more they are affected.

Not sure if this is related or useful or not.:) 
let me know if you want me to dig more

thanks

**Comment by Razviar** [comment]
Yes, that's very helpful! Thanks for digging.

**Comment by Razviar** [comment]
Issue is resolved now. Thanks for the vigilance.
