### ISSUE TITLE
Not syncing inventory/progress no matter what

### ISSUE THREAD

**Issue by J-Camara** [Razviar/mtgap#133]
ACCOUNTS:
mtga.cc/u/Parov.153535
mtga.cc/u/Jan Camara

 - Windows 10 pro
 - App Version: 2.0.49

BUG DESCRIPTION
I can't see progress or collection. The message 'Old logs ar uploaded!' shows normally, if i "wipe all settings" and sync account again nothing happens. I even tried creating a fresh account with a new email and it didint helped.

DETAILS // REPRODUCTION
On january i had the tracker working normally, then Tryed installing on my laptop and i had problems wich i dont remember exactly. But the problems made me quit using the tracker because it worked only on my old PC, not on laptop. At this time i was synced with a facebook account.

Now i got a new PC. Installed tracker and logged into old account. My collection was stuck on january: no ikoria or theros cards, absolute none. Tryed re-syncing, restarting, sync old logs, pick last log, wiping Ovl and settings but nothing worked.
![image](https://user-images.githubusercontent.com/66565375/83975022-b3fecd00-a8c7-11ea-9f86-38cc14704024.png)
![empty log](https://user-images.githubusercontent.com/66565375/83975032-c416ac80-a8c7-11ea-8bf5-c511d993cde0.PNG)

Then I logged out of website, wiped both Ovl location and All settings, created whole new different account now with email address (gmail), Synced new account and... my progress is as if I had zero cards.

I really like the way you display the progress and handles collection, but it seems I can't get over with this problem. Help, me please :(

**Comment by Razviar** [comment]
Account is fixed for user ID 191499 "Jan Camara".
After settings wipe you will see collection uploaded.

**Comment by J-Camara** [comment]
It worked, thanks so much!!!

:)
