### ISSUE TITLE
AOL IM style friends list and chat ability

### ISSUE THREAD

**Issue by mcfly31796** [Razviar/mtgap#137]
Good day, 

It would be great if there was a simple chat ability during game play as well as in the game lobby.  It would also be great to add and keep a friends list that showed when they were online.  

Think AOL Instant Messenger! It would make finding your friends and inviting them to games much easier as well as much more fun than having to text back and forth through phones.  It would be like the old days of chat rooms, but while nerding out and playing Magic!

I love MTG.  I don’t love Arena...but it is growing on me.  The toughest thing is to sit and play against some stranger who you can’t even talk to.  You can play with a friend, but it takes coordination and never just happens by chance.  

In order to keep the trolling to a minimum, both parties should have to agree to the chat as well as be able to report shit behavior.  But on the right or left side of the screen, there should be a friends list showing who is online as well as who just got online with easy one touch chatting and game requests.  I think it would keep the game from getting kind of boring playing with only simple emotes.  

Just a suggestion from a 40 year old nerd who played back in the 90’s and rediscovered the game in 2012 and still LOVES IT!

Again, think AOL IM!!

-Marty

**Comment by Razviar** [comment]
Hello! This is MTGA Pro Tracker 3rd party support tool git. You should reroute your idea to MTGA official community forums.
