### ISSUE TITLE
Crashes at install time (Win10 19645.1)

### ISSUE THREAD

**Issue by uffish** [Razviar/mtgap#140]
- Link to your MTGA Pro account
https://mtgarena.pro/u/mpk

**Your Desktop:**
 - OS: Windows 10 19645.1 (fast ring)
 - App Version: All recent

**Describe the bug**
When installing MTGAP (have tried the last five versions with nearly identical results every time), the installer exits either immediately or very shortly after starting, leaving MTGAP marked as installed by Windows but not able to run. I have tried uninstalling and reinstalling multiple times and nothing seems to have helped.

Let me know if there are any logs I should be collecting and I'll gladly pass them along. Thanks in advance for any advice you can offer!

**To Reproduce**
1. Download a recent version of MTGAP
2. Run the installer
3. The installer will either instantly exit or the "installation progress" screen will appear for a few seconds then vanish
4. MTGAP is marked as installed, but cannot be run

**Comment by Razviar** [comment]
Check if antivirus blocking it. Try to reboot PC and try again.

**Comment by uffish** [comment]
Tried all the above. No change in behaviour - either nothing at all happens, or the installer screen appears and animates for about 2 seconds before disappearing again. Are there any installer logs somewhere I can check out?

**Comment by Razviar** [comment]
Check appdata/local/mtgaprotracker folder, is there any log files?

**Comment by uffish** [comment]
The only log there is - app-2.0.50/SquirrelSetup.log - doesn't say much:

﻿2020-06-19 21:14:25> Program: Starting Squirrel Updater: 
--updateSelf=C:\Users\mpk\AppData\Local\SquirrelTemp\Update.exe
2020-06-19 21:14:25> Program: About to wait for parent PID 9004

m.

**Comment by Razviar** [comment]
Have you tried to install it on another PC? Was there result different?

**Comment by uffish** [comment]
It has installed on another PC - the problem seems to be only with my machine that is on the Windows Insider fast ring, which doesn't guarantee to be a stable platform. It probably makes sense to close this bug.
