### ISSUE TITLE
Reprint count is not updating properly

### ISSUE THREAD

**Issue by iknowwhatismyname** [Razviar/mtgap#141]
Hi Razviar,

it is back... :(
"Goreclaw, Terror of Qal Sisma" - I have 4, I see 3 in crafter. 
I remember when we fixed that one, i only had 3. So i guess i opened it in a packed since you fixed 132.

iknowwhatismyname#52295

**Comment by Razviar** [comment]
Most likely it's different issue, we will investigate

**Comment by Razviar** [comment]
Yeah, it's another issue, related to reprint count updates. We are working on fix, eta is 2-3 days

**Comment by Razviar** [comment]
Patch applied, collection should get corrected soon
