### ISSUE TITLE
Searching Decks, Using "Contains Cards" never works.

### ISSUE THREAD

**Issue by jpcguy89** [Razviar/mtgap#145]
Nearly every time I try and search for a deck in MTGA Pro using the Contains Cards I get 0 results, and it just doesn't work. For example, I searched for a deck containing both Ugin, the Spirit Dragon and Nissa, Who Shakes the World. I got zero results. Maybe I'm wrong and there's just no decks on the site containing those two cards, but I find that hard to believe.

**Comment by Razviar** [comment]
I just tried and wasn't able to replicate the issue.
When I entered cards, I got some decks. Here's direct link to results:
https://mtgarena.pro/decks/?community#date-30;hascrd-4173,6258
Try to open it and let me know what you've got.

**Comment by jpcguy89** [comment]
This is bizarre, I now get only one result, but its completely different than your. Here's the url and a screenshot.

https://mtgarena.pro/decks/#date-30;hascrd-6258,4173[
![mtgaproerror](https://user-images.githubusercontent.com/1883268/85892377-71d5f680-b7b6-11ea-877b-9309b98888ec.png)
](url)

**Comment by jpcguy89** [comment]
Ok I think we can mark this as resolved. It was my expectation that entering items into "contains cards" without configuration. I was unaware that in order to get all results you have to switch to community first.

If I might may a suggestion, perhaps if there's less than X results, you can do an additional search in community and append it underneath with a divider and something like "More Results Outside of Featured" or something similar.
