### ISSUE TITLE
Multiplayer games

### ISSUE THREAD

**Issue by unEvil** [Razviar/mtgap#146]
I'd like to see more than one on one matches in Arena.
MTG is a group game (outside of tournaments) so having the option for three or four players in a group game either free for all or teams (ex. two-headed giant) would increase the cards in use and would also create new decks away from the standard tournament style decks that are played the majority of the time within the game.

Would only need an option for multiplayer games (standard, historic and Brawl) and a either a reduction in size of each players board with the continued use of zooming or having a the extra players along each side of the screen.

**Comment by Razviar** [comment]
This is 3rd party tool support project. Please refer your request to game devs
