### ISSUE TITLE
Issue with mtga path access

### ISSUE THREAD

**Issue by LeviLenaers** [Razviar/mtgap#148]
your app isn't working, did several restarts, Detail logging is enabled.
But i don't se any sync button, nor does the credentials come in my log, keep waiting for it to come in my logs.

Your step by step doesn't work. Did everythig like your tutorial said. NOT WORKING

**Comment by rat128** [comment]
Same.  Not sure what else to say, but happy to try things or send logs.  Here is a screenshot with the error I have.
![Capture](https://user-images.githubusercontent.com/44983104/86291010-63277f00-bbbc-11ea-95fb-6d712596b6bc.PNG)

**Comment by Razviar** [comment]
Try to go to settings and point to game installation folder manually

**Comment by Razviar** [comment]
If you have the same issue, please let me know:
1. Your platform (win or Mac)
2. Location of mtga.exe

**Comment by Silver-Streak** [comment]
Same issue here, 
Platform: Win10 Pro 64 bit
Location of MTGA: D:\Program Files\Games\Wizards of the Coast\MTGA

**Comment by diogonb** [comment]
Same issue here
Platform: Win10 Pro - 64 bit
Location: D:\Games

**Comment by rat128** [comment]
> Try to go to settings and point to game installation folder manually

The auto find button in settings worked for me to resolve this issue. Not sure how I missed that the first time. Sorry to waste your time.

**Comment by Razviar** [comment]
**!Important!
now you need to point to "Wizards of the Coast\MTGA\MTGA_Data" folder to pick it manually!!!**

**Comment by Marthisdil** [comment]
Still an issue.   My game path is C:\Games\MTG Arena\MTGArena - worked up until this latest release.  Even if I tell it to try and auto find, or manually select the folder, it says found successfully, but then changes back to not found,.

**Comment by Dakkith** [comment]
> **!Important! now you need to point to "Wizards of the Coast\MTGA\MTGA_Data" folder to pick it manually!!!**

Thanks Razviar. That sorted the issue out for me.

**Comment by diogonb** [comment]
> **!Important! now you need to point to "Wizards of the Coast\MTGA\MTGA_Data" folder to pick it manually!!!**

This helped me too

**Comment by Silver-Streak** [comment]
Unfortunately, after picking it manually, it worked for a day and now just says "Game is not running"

**Comment by Razviar** [comment]
@Silver-Streak try wiping settings, restart everything (tracker, mtga, PC)

**Comment by Razviar** [comment]
Closing this for housekeeping purposes. If you have anything to add, feel free to do it, I'll reopen it if that will be needed.
