### ISSUE TITLE
Mac OS release version is always 2.1.0

### ISSUE THREAD

**Issue by Immelstorn** [Razviar/mtgap#149]
- Link to your MTGA Pro account - mtga.cc/u/Immelstorn

**Your Desktop:**
 - OS: Mac OS 10.15.5

**Describe the bug**
I download new release version from assets, put it into Application folder and replace old one. Then I start the app and I see that it's version is 2.1.0, if I click at the version number it thinks for a while and then restarts having version 2.1.1.
So I suppose version updates 2.1.2-2.1.4 were only for windows client, maybe you can state it in the release notes?

**Comment by Razviar** [comment]
We are working currently on Mac and Windows versions sync. At the moment in releases pack Win version is 2.1.4 and Mac version is 2.1.0. Updates 2.1.2-2.1.4 were focused on regressions fixes related to Mac implementation

**Comment by Immelstorn** [comment]
Ok, thanks,  can I fully rely on in-app update system on Mac OS? Or should I proceed to update manually?

**Comment by Razviar** [comment]
Automated updates are working. You can grab updated version here tho: https://github.com/Razviar/mtgap/releases/tag/v2.1.4
We just pushed 2.1.4 for Mac

**Comment by Immelstorn** [comment]
>Automated updates are working. 

doesn't seem so
![MTGA Pro Tracker 2020-07-03 12-47-18](https://user-images.githubusercontent.com/2045727/86462133-62612b00-bd2b-11ea-9676-6b2ed2d54a36.png)

**Comment by Razviar** [comment]
Mac version starting from 2.1.1 is verified to be auto-updating. Closing the issue.
