### ISSUE TITLE
Paid Mastery rewards not uploaded

### ISSUE THREAD

**Issue by Kriellya** [Razviar/mtgap#15]
What it says on the tin. The Paid Mastery rewards aren't getting recorded on the site.

Dug through the logs to make sure it wasn't an MTGA problem, then updated the tracker and reloaded that log. I'm going to attach the relevant line from the log, cause I can see why the parser wouldn't read this line correctly. The important section is 'battlePassUpdate's 'inventoryUpdates', which contains two blocks. The first block is the free track, and is being uploaded correctly. The second appears to correspond with the paid track, and is not uploaded at all.

Because apparently, despite having a 'trackTier' element in battlePassUpdate, they don't use it.

```
"battlePassUpdate":{"trackName":"BattlePass_ELD","trackTier":0,"trackDiff":{"currentLevel":65,"currentExp":0,"oldLevel":64,"oldExp":975,
	"inventoryUpdates":[
		{"delta":{"gemsDelta":0,"goldDelta":0,"boosterDelta":[{"collationId":100015,"count":1}],"cardsAdded":[],"decksAdded":[],"starterDecksAdded":[],"vanityItemsAdded":[],"vanityItemsRemoved":[],"draftTokensDelta":0,"sealedTokensDelta":0,"vaultProgressDelta":0.0,"wcCommonDelta":0,"wcUncommonDelta":0,"wcRareDelta":0,"wcMythicDelta":0,"artSkinsAdded":[],"artSkinsRemoved":[],"voucherItemsDelta":[]},"aetherizedCards":[],"xpGained":0,"context":{"source":"BattlePassLevelUp","sourceId":"BattlePass_ELD[0][64]"}},
		{"delta":{"gemsDelta":0,"goldDelta":0,"boosterDelta":[],"cardsAdded":[69614],"decksAdded":[],"starterDecksAdded":[],"vanityItemsAdded":[],"vanityItemsRemoved":[],"draftTokensDelta":0,"sealedTokensDelta":0,"vaultProgressDelta":0.0,"wcCommonDelta":0,"wcUncommonDelta":0,"wcRareDelta":0,"wcMythicDelta":0,"artSkinsAdded":[],"artSkinsRemoved":[],"voucherItemsDelta":[]},"aetherizedCards":[{"grpId":69614,"goldAwarded":0,"gemsAwarded":0,"set":""}],"xpGained":0,"context":{"source":"BattlePassLevelUp","sourceId":"BattlePass_ELD[1][64]"}}
	]
},"rewardWebDiff":{"currentUnlockedNodes":[1,6,11,16,21,26,4,9,14,19,24,29,2,7,12,17,22,27,0],"currentAvailableNodes":[5,3],"oldUnlockedNodes":[1,6,11,16,21,26,4,9,14,19,24,29,2,7,12,17,22,27,0],"oldAvailableNodes":[5,3],"inventoryUpdates":[]},"orbCountDiff":{"oldOrbCount":1,"currentOrbCount":1}}
```

![trackerpic](https://user-images.githubusercontent.com/718382/69687001-523aec00-1076-11ea-9b43-cd49a7c13862.png)

**Comment by Razviar** [comment]
Thanks, especially for logs analysis. You should join us to develop this thing with this deep understanding of mtga logs ;)

**Comment by Razviar** [comment]
Finally this issue was addressed. Sorry for such a delay.
