### ISSUE TITLE
Mac OS: overlay problems

### ISSUE THREAD

**Issue by Immelstorn** [Razviar/mtgap#150]
- Link to your MTGA Pro account - mtga.cc/u/Immelstorn

**Your Desktop:**
 - OS: Mac OS 10.15.5
 - App Version 2.1.1

**Describe the bug**
1. When I enable overlay for the first few seconds I can click on it, make it smaller/larger, etc. After some time it becomes irresponsible, no key elements can be clicked. The only way to make it clickable is to bing tracker's main window to front and then in the Mac OS menu bar choose second tracker window (see video https://youtu.be/4x94OB1GaTY).

2. Even if I can click on it after switching windows, I still can't move it.

3. Hotkeys for overlay doesn't work at all.

**Comment by bmeudre** [comment]
Hi @Immelstorn,

Thanks for reporting this issue. Can you try to update to latest tracker (2.1.5) and let us know if you still encounter this issue. We have compatibility issues with overlay interaction and Mac OS X so we added a setting to have the overlay interactive or not (default setting is not interactive). Hotkeys should work on latest version.

**Comment by Immelstorn** [comment]
Hi @bmeudre,

thanks for fixing! It seems hotkeys are working good, so we can live without interactive overlay I guess.
The only annoying thing is you can't really hide opponents deck with hotkey. I press option+W, deck disappears, but after opp will draw/play something it will appear again.

**Comment by Razviar** [comment]
Hotkey issue is fixed in 2.1.6

**Comment by fasmat** [comment]
> Hotkey issue is fixed in 2.1.6

There is no dmg available for 2.1.6?
