### ISSUE TITLE
Is the Human Draft overlay still Bugged?

### ISSUE THREAD

**Issue by Drizzt893** [Razviar/mtgap#153]
mtga.cc/u/Drizzt893

Windows 10
v2.1.4

Human Draft overlay still not working.  My tracker is set to auto update, and I noticed it restart today on it's own, so I checked if there were updates.  I saw that human draft was implemented a few updates ago, but mine still isn't working.  Is this a known bug?  I don't want to waste in game currency checking if the overlay works multiple times if there's a known way to fix it.  I don't have time to play through multiple drafts, so it would take weeks to troubleshoot on my own.

**Comment by Razviar** [comment]
It was implemented few weeks ago and we didn't received any complains since then. What do you mean by bugged: overlay window not showing up or draft is not getting recorded? We have only in game help for human draft, but no draft record in history

**Comment by Drizzt893** [comment]
The overlay menu shows up and works fine in Quick Draft, but in Traditional Draft (I don't play Premium) the overlay that shows the picks and W/L ratio etc. doesn't show up.  It seems the overlay isn't aware that I'm drafting at all when I'm in a human draft.

I'll buy into a draft if you need screenshots or logs etc., but it might me a while before I can get into another draft after that.  I'll happily supply any other info you need, but I haven't drafted with humans in a few days, so my logs probably don't have a human draft right now.

I just realized that last time I did a human draft was probably 2.1.3, not 2.1.4 since I think it auto updated today.

**Comment by Razviar** [comment]
You can actually get me your logs from previous drafts. Take a look at game installation folder, mtga_data/logs/logs

Get those which have relatively big size and date in filename coinside with date of your drafts. Zip those and send me over

**Comment by Drizzt893** [comment]
https://drive.google.com/drive/folders/1nFdzxtd44dvBjqu27eekbHxsPGgz6Bgk?usp=sharing

I'm not familiar with this code, but it looks like one of the folders has a deck recorded for traddraft, so hopefully it has what you need.  It's possible I drafted the night before the logs start though.

**Comment by Razviar** [comment]
Thanks, we'll investigate this logs

**Comment by Razviar** [comment]
Thanks to your input human draft is fixed. Now you can have fun with it using 2.1.5 version of Tracker.
