### ISSUE TITLE
M21 error quantity of cards

### ISSUE THREAD

**Issue by gastonmb** [Razviar/mtgap#157]
The number of cards are wrong in the Progress of the sets.

For example:

M21 in Arena have:
21 mythics
58 rares
85 uncommons
111 commons

In MTG Arena Pro
15 mythics
53 rares
80 uncommons
101 commons

Please, check and change that.

**Comment by Razviar** [comment]
For that number we count only 'boostable' cards, meaning only those which you can get from opening boosters. And these numbers are correct for boostable cards. We've been receiving a lot of requests from user to make card count equal to 'only boostable', so we will keep it this way.
