### ISSUE TITLE
Profile and matches not updating since 14 july

### ISSUE THREAD

**Issue by candybomberz** [Razviar/mtgap#158]
**Detailed context (ISSUES WILL NOT BE INVESIGATED WITHOUT IT!):**
mtga.cc/u/candybomberz

**Your Desktop:**
 - OS: Windows 10
 - App Version: 2.1.7

detailed logs are enabled in the game client

I tried syncing old logs, didn't help, for some reason only logs from 8th and 9th july are available

**Comment by Razviar** [comment]
Have you tried to wipe settings?

**Comment by candybomberz** [comment]
Wiping settings seems to have worked.
