### ISSUE TITLE
Unable to read Social Feed?

### ISSUE THREAD

**Issue by BrunoBatta** [Razviar/mtgap#163]
Hi!
I’m Having problems to read social feed in app since last update. 
Any idea?

![D079AC65-5BE1-48D4-A6A7-A63B6E4CC6D1](https://user-images.githubusercontent.com/55740209/88057546-85307380-cb62-11ea-979b-3f067f77b7a2.png)
**Detailed context (ISSUES WILL NOT BE INVESIGATED WITHOUT IT!):**
- Link to your MTGA Pro account
- Link to page/pages are in question
- Screenshots of issue if applicable 

**Your Desktop:**
 - OS: [e.g. Windows 10]
 - App Version [e.g. 2.0.22]

**Describe the bug**

**To Reproduce**

**Comment by Razviar** [comment]
Should be fixed in 1.10.0
