### ISSUE TITLE
e

### ISSUE THREAD

**Issue by NicolasMuzette** [Razviar/mtgap#17]
Hi everyone,
I can't see anything in the "Accounts" tab :

![image](https://user-images.githubusercontent.com/17221151/69717608-a690ab00-110c-11ea-9713-f525514f33c6.png)

also, the "General" Tab tells me the game is not running 

![image](https://user-images.githubusercontent.com/17221151/69717815-12731380-110d-11ea-8cad-a8227ff3e0f0.png)

I tryed to run it as administrator, rebooting and my .NET framwork is ok.

I use updated windows 10. and de 2.0.14 app version.

any advices ? thanks everyone.

**Comment by Razviar** [comment]
This means tracker came get data from your log. You should try to set game log location manually
