### ISSUE TITLE
Draft Details have packs all shifted around

### ISSUE THREAD

**Issue by Kusand** [Razviar/mtgap#170]
**Detailed context (ISSUES WILL NOT BE INVESIGATED WITHOUT IT!):**
- Account: mtga.cc/u/Kusand
- Event page: https://mtgarena.pro/draft/Kusand/2543d265-d663-47de-8dcd-b30b8f57606b/
<img width="1159" alt="Screen Shot 2020-07-29 at 11 38 42 AM" src="https://user-images.githubusercontent.com/573270/88821185-5896e000-d190-11ea-85dd-3838a9fa255f.png">

**Your Desktop:**
 - OS: Mac OSX
 - App Version: 2.1.8

**Describe the bug**
My events pages don't correctly show the draft packs I received

**To Reproduce**
1. Go to linked Event Page
2. Click on Pack 1
3. The only card listed in Pack 1 Pick 1 is my pick. The rest of Pack 1 is down in Pick 2. Everything else is jumbled up from there.

**Comment by Razviar** [comment]
Hi! Thanks for reporting! Two questions:
1. Are picks recorded correctly at all? Meaning, are those picks are your picks?
2. Is there any recognizable pattern? Like, if rest of Pack 1 is down in Pick 2, is this pattern holds on onwards?

**Comment by Razviar** [comment]
Also, can you please get logs of this draft from this folder:
Library/Application Support/com.wizards.mtga/Logs/Logs 
(you should be able to find files by UTC time stamps)

**Comment by Kusand** [comment]
Yes, the picks are correct. They *seem* to all be shifted but my memory of the chaff in each pack isn't that great. The draft log is too large to upload to Github though.

**Comment by Razviar** [comment]
@Kusand can you please upload logs zipped and using some file sharing tools like https://dropmefiles.com/ ?

**Comment by Kusand** [comment]
Oh, duh. ZIPs.
[UTC_Log - 07-28-2020 23.36.40.log.zip](https://github.com/Razviar/mtgap/files/4996588/UTC_Log.-.07-28-2020.23.36.40.log.zip)

**Comment by Razviar** [comment]
This happen because other user besides you was tracking the same draft with our tracker. In result, his and yours packs got messed up. We fixed that issue, next drafts should be tracked fine. And it's kinda flattering that there's 2 our users among few random draft players lol.

**Comment by Kusand** [comment]
Thanks - I guess there's no disentangling this? Not a big deal, it was just such an awful draft that I was going to post it somewhere for advice on where I went wrong.
