### ISSUE TITLE
No progress update since last update (21-07-2020)

### ISSUE THREAD

**Issue by injhal** [Razviar/mtgap#171]
All of my progression is stop on 21 Jul 2020. I try to sync my log but no effects on my account. I use both windows and macos client. 
![Capture01-mtgarena](https://user-images.githubusercontent.com/3882716/88834979-e5638d00-d1d4-11ea-84f4-0ffb45d717d2.JPG)

**Comment by Razviar** [comment]
Can you please try to wipe settings and sync again?

**Comment by injhal** [comment]
After clean, sync data is ok. Sorry i should try it before. Nice job !
