### ISSUE TITLE
Tracker not saving config or finding user credentials

### ISSUE THREAD

**Issue by Aiadan** [Razviar/mtgap#172]
Profile (though maybe not applicable for this case): https://mtgarena.pro/u/Aiadan

 - OS: Windows 10
 - App Version 2.1.8

When selecting the correct path to the MTGA folder and then restarting the tracker, the correct path is no longer saved.
After selecting the correct path to the MTGA folder, the tracker is stuck on "Awaiting user credentials to appear in log...".

Detailed logging is enabled in MTGA.

**Comment by Razviar** [comment]
Try to wipe settings and start over. For MTGA path you need to provide path to the folder where MTGA.exe resides. For log path, you most likely don't need to touch that option. Sometimes restarting everything helps.

**Comment by Razviar** [comment]
Closing this due to old issues cleanup. If you have anything to add, feel free to comment here, we will re-open this.
