### ISSUE TITLE
Can't Sync account

### ISSUE THREAD

**Issue by Bigman22jr** [Razviar/mtgap#173]
Just signed up and downloaded the overwolf version and for some reason the sync button does nothing. It takes me to the browser page with the button and i click the button. It says that i have sync up but when i go to my collection or anywhere else to check it has nothing. the general tab under settings only has "Error: Parsing paused: new user account must be synced or skipped" which i have tried doing over and over but nothing happens. I go to the account tab click the button that says sync account. Click sure on the popup. Get taken to a new tab on my browser that has a confirm connection button. Click that. 1 second later is says all set you can close the tab. Go to my progress tab shows that i have no progress or cards nothing changes on the app itself. I have uninstalled and reinstalled everything a few times now no idea what i am doing wrong. I have detailed logs enable as well. Another thing that might be relevant is the on the account tab on the overlay is says I am not logged in on overwolf which is wrong I am. In fact i have it opened as well to check I am logged in for sure. One last thing is that sometimes when i try to go the account  tab on the overlay it instead sends me to the settings tab.

https://mtgarena.pro/u/Bigman22jrV2

 - OS: Windows 10
 - App Version I assume is 2.1.8 or whatever the version the overwolf app is currently using.

**Comment by Razviar** [comment]
Hello! In order to sync with overwolf version you need to:
1. Login into Overwolf account
2. Register on MTGA.pro with new account
3. Sync Overwolf account with MTGA.pro account
4. Only when OW and MTGA.pro are synced, you need to sync MTGA player ID with MTGA.pro by clicking respective button.

Now you can try to wipe settings and try again whole process. Or try standalone tracker version if this one is not working for you

**Comment by Razviar** [comment]
From database I can see that you are not synced with Overwolf account, your OW account name is empty

**Comment by Bigman22jr** [comment]
How do I sync my accounts that isn't the sync button under the account tab, because that button doesn't work it doesn't do anything? All it does is take me to a new browser tab have me click another button says everything is sync when nothing is synced. Is there another sync accounts button that i am missing?

**Comment by Razviar** [comment]
When you sync Overwolf account with MTGA.pro account, you are getting redirected to page with url like 
https://mtgarena.pro/overwolf/?sync=YOUR_OVERWOLF_USERNAME&comeback
On that page you should confirm sync. If you don't see your OW username after "sync=" then something is wrong. Like, you are not logged in with Overwolf client or something else.

**Comment by Bigman22jr** [comment]
well the issue seems to have fixed itself. The strange thing was all it took was resigning my current jumpstart run. I am not sure if that is what fixed it, but i just know after i clicked resigned for my current jumpstart run the app just popped out of nowhere and the sync button now works.
