### ISSUE TITLE
Overlay moved off screen, cannot recover.

### ISSUE THREAD

**Issue by mikerobrewer** [Razviar/mtgap#174]
**Detailed context (ISSUES WILL NOT BE INVESIGATED WITHOUT IT!):**
- Link to your MTGA Pro account
- Link to page/pages are in question
- Screenshots of issue if applicable 

**Your Desktop:**
 - OS: [e.g. Windows 10]
 - App Version [e.g. 2.0.22]

**Describe the bug**

**To Reproduce**

**Comment by Razviar** [comment]
Go to settings tab and click "wipe overlay position" button. Or "wipe settings"
