### ISSUE TITLE
Cards present in MTGA Pro but not in Arena client

### ISSUE THREAD

**Issue by VanitasEst** [Razviar/mtgap#175]
**Detailed context (ISSUES WILL NOT BE INVESIGATED WITHOUT IT!):**
- Link to your MTGA Pro account: https://mtgarena.pro/u/VanitasEst
- Link to page/pages are in question: https://mtgarena.pro/cards/#expansion-72

**Your Desktop:**
 - OS: Windows 10
 - App Version: 2.1.8

**Describe the bug**
There are multiple cards (of mostly pre-Ixalan expansions) that are present in your database and not in the Arena client. For example 5 out of the 6 cards of the Theros/THS expansion (attached image). Or "Teferi's Ageless Insight" of the Jumpstart/JMP expansion which is only present in Core Set 2021/M21. I can provide a full list if needed.
![mtgarenapro-phantomcards-ths](https://user-images.githubusercontent.com/69818695/90438054-b9e90980-e0d3-11ea-90bf-361b626b121e.png)

**Comment by Razviar** [comment]
The thing is, under the hood all those cards exist in MTGA, but they are "not craftable". So you can't see them in client, but they exist. To filter them out you need to set filter next to Historic to "Craftable" position like that: https://mtgarena.pro/cards/#expansion-72;rulings-1;srt-11;direct-0;booster-2 

We removed all older cards which are really not in the MTGA client right now (like pre-open-beta XLN set etc.), but all modern sets are being represented exactly how they look in the game's cards database.
