### ISSUE TITLE
Opponent Deck Keeps Popping Up After Being Hidden

### ISSUE THREAD

**Issue by moe-rs** [Razviar/mtgap#177]
mtga.cc/u/Reon

**Your Desktop:**
 - OS: Windows 10
 - App Version 2.1.8

**Describe the bug**
Match starts, the opponent deck is not shown, he plays a card, and then his deck list shows up on the right in an overlay. So I open the menu for MTGAP and hide it by clicking the little eye (OPP) button which hides the opponents deck list overlay. As soon as the opponent plays another card, the opponents deck overlay shows up again and so I have to hide it again, over and over every time the opponent plays a card. I'm able to hide it using the app settings as a workaround but this is cumbersome and not ideal. My own deck show/hide toggle works as expected.

**To Reproduce**
1. Start a match with default settings
2. Wait for the Opponent to play a card which causes the opponent deck overlay to show up
3. Click the MTGAP menu and hide the opponents deck by clicking the eye button labeled OPP which hides the opponents deck
4. Wait for the opponent to play a card which causes the opponent deck overlay to show up despite being explicitly hidden in step 

Expected Behavior:
If I explicitly hide the opponents deck using the hide toggle button then it should stay hidden (much like my own stays hidden after choosing to hide it via the eye button)

**Comment by Razviar** [comment]
I thought this issue was fixed log ago. We will revisit it then

**Comment by Razviar** [comment]
Latest release of both standalone and Overwolf version resolves this issue
