### ISSUE TITLE
Score in Matches incorrect sometimes

### ISSUE THREAD

**Issue by benyash** [Razviar/mtgap#178]
**Detailed context (ISSUES WILL NOT BE INVESIGATED WITHOUT IT!):**
- Link to your MTGA Pro account
**https://mtgarena.pro/u/Sam_I_Am**

- Link to page/pages are in question
**https://mtgarena.pro/matches/?Sam_I_Am**

- Screenshots of issue if applicable 
![bug](https://user-images.githubusercontent.com/69908926/90645687-ef5e3600-e23e-11ea-999d-a32aaa993e59.gif)

**Your Desktop:**
 - OS: [e.g. Windows 10]
**Windows 10 Home x64**
 - App Version [e.g. 2.0.22]
**2.1.8 (& early)**

**Describe the bug**
**Score of some matches are incorrect. For example 2nd & 4th lines on screenshort: "Win 0:1". Must be "Win 1:0". Result (win/ loss) -- correct, but not score.**

**To Reproduce**
**See on screenshot**

**Comment by Razviar** [comment]
Order of numbers in score is determined by team number assigned to you by system. Players don't know about that, but every time you enter the match, game randomly assigns "Team 1" and "Team 2" to you and your opponent. Then all events are happening not to the players directly, but to the teams. So score is rendered in format TEAM_1_SCORE : TEAM_2_SCORE. And when you see 0:1 score, it means that you were in "Team 2". To change rendering we would have to make a lot of work under the hood, so we will keep it as is.
