### ISSUE TITLE
Tracker doesn't track - Connection Error

### ISSUE THREAD

**Issue by necromanek** [Razviar/mtgap#18]
Hello, 

the tracker didn't connect today, it says Connection Error. When I stop it and start again, nothing changes except it doesn't remember settings like Start Minimized and Start with Windows. Thanks for your help!

Regards,
Jiri

Version 2.0.11

Firefox

**Comment by Razviar** [comment]
Hi! Please update to https://github.com/Razviar/mtgap/releases/tag/v2.0.14

**Comment by necromanek** [comment]
Updated, the tracker didn't registered my previous 15(?) games but tracked only one of them, and the first game with the updated tracker is missing, too. No big deal, just feedback. Thanks!

Jiri
