### ISSUE TITLE
MacOS rewards appear twice.

### ISSUE THREAD

**Issue by mithrandir15** [Razviar/mtgap#180]
mtga.cc/u/mithrandir15
mtga.cc/rewards/?mithrandir15

MacOS Catalina 10.15.6
Tracker version 2.1.8

Every reward in the rewards screen appears twice. Issue persists after re-syncing old logs.

**To Reproduce**
1. Receive rewards

<img width="1145" alt="Screen Shot 2020-09-03 at 3 38 21 PM" src="https://user-images.githubusercontent.com/22643969/92159520-8e685d80-edfb-11ea-850b-b959c2d7388b.png">

**Comment by Razviar** [comment]
Patch applied, should be no more doubles anymore. Old records will remain as is.

**Comment by mithrandir15** [comment]
Issue is fixed for Boosters and Events, but not for Quests and Daily Wins. mtga.cc/rewards/?mithrandir15

**Comment by Razviar** [comment]
Thanks for reporting, I'll re-open this and we will investigate

**Comment by Razviar** [comment]
Fix implemented
