### ISSUE TITLE
Does not show all ICR rewards

### ISSUE THREAD

**Issue by candybomberz** [Razviar/mtgap#183]
**Detailed context (ISSUES WILL NOT BE INVESIGATED WITHOUT IT!):**
- mtga.cc/u/candybomberz

**Your Desktop:**
 - OS: Windows 10
 - App Version 2.1.9

**Describe the bug**
Not all ICR rewards seem to show up on the profile page, eventhough they show up in the rewards section.

**Comment by Razviar** [comment]
Fix implemented
