### ISSUE TITLE
Filter for Rewards - Cards / Gold / Packs / All

### ISSUE THREAD

**Issue by jakelakedev** [Razviar/mtgap#184]
**Detailed context:**
Basically there is no filter now for rewards.  A filter by type would be great. 

**Proposed Workflow**
The second dropdown would have a series of checkboxes for one:many types. 
Gold/Gems
ICR
Booster
Experience

![image](https://user-images.githubusercontent.com/71096827/92783937-7052ae00-f363-11ea-846f-2493d7766efe.png)

This way its simpler to see what cards you have won in a particular date range.

**Comment by Razviar** [comment]
You need to select context in the left menu first (it's global rewards source), then you'll see rewards detailed filters in menu you've mentioned. 
Unfortunately, "many" options filters are not going to be implemented for now.
