### ISSUE TITLE
Decklist page on website has z-index issues

### ISSUE THREAD

**Issue by aminomancer** [Razviar/mtgap#186]
mtga.cc/u/aminomancer
![Screenshot (33)](https://user-images.githubusercontent.com/33384265/93276396-3c68f580-f774-11ea-848d-d944c223997c.png)

this just concerns the website not the app. but fwiw I'm using windows 10 1903 and firefox nightly. due to the css module classnames i'm pretty sure that the CSS rules causing this problem are generated by a script on the site or maybe from the google ads implementation. not really my area of expertise but i do know that rules out any content scripts from the browser or addons or anything else on my end.
STR:
1) go to a decklist on mtgarena.pro e.g. [this one](https://mtgarena.pro/decks/athreos-death-march)
2) don't block ads/be logged in
3) hover mouse over cards in the list
4) card previews with messages under them e.g. "Will be rotated from Standard soon!" are aligned to the left of the cursor instead of top or bottom, causing them to float pretty far to the left compared to other cards.
5) card previews appear *under* the ad panels. it's not the ad itself, it's the outermost div which contains the iframe in which ads are loaded. this div has no id and its class is generated by react so i don't know of a good way to tell you exactly which element i'm talking about. i can just show you the DOM as it appears in my devtools, so you can at least see where it is in the tree and how it relates to the rest of the doc and that this div has z-index: 100000. it's the ancestor of all the other ad elements so you can find it pretty easily.
![Screenshot (34)](https://user-images.githubusercontent.com/33384265/93276902-bc438f80-f775-11ea-8a89-9e3373f3a971.png)

i understand the ad panels need to have a high z-index and that's probably from the google ads script. but the preview cards should have an even higher z-index to adapt to the situation. i get that it's not a big problem because the ads don't normally appear for frequent users or people who use ad blocking extensions. i'm just mentioning it since it would be easy to fix and there's nothing to lose by fixing it.

thanks for the great tracker by the way.

**Comment by Razviar** [comment]
I think it's fixed now, I just checked, and there were no ads covering cards.
