### ISSUE TITLE
Zendikar Rising: One side of the flip cards shows not collected in collection.

### ISSUE THREAD

**Issue by Avatar1971** [Razviar/mtgap#187]
**Detailed context (ISSUES WILL NOT BE INVESIGATED WITHOUT IT!):**
- Link to your MTGA Pro account = Avatar1971
- Link to page/pages are in question = https://mtgarena.pro/collection/#expansion-104;rulings-1;srt-11;direct-0;collection-2
- Screenshots of issue if applicable 
![Screenshot (35)](https://user-images.githubusercontent.com/71606534/93719167-a5b28500-fb35-11ea-8416-a7ff5f109a80.png) 
![Screenshot (58)](https://user-images.githubusercontent.com/71606534/93719187-bd8a0900-fb35-11ea-950d-ef3109ef0bd0.png)
![Screenshot (59)](https://user-images.githubusercontent.com/71606534/93719201-cc70bb80-fb35-11ea-88b5-b867eb3272d8.png)
![Screenshot (60)](https://user-images.githubusercontent.com/71606534/93719205-d1ce0600-fb35-11ea-8ed0-d0156b4c7843.png)
![Screenshot (61)](https://user-images.githubusercontent.com/71606534/93719209-d7c3e700-fb35-11ea-85de-0362fa3564ff.png)
![Screenshot (62)](https://user-images.githubusercontent.com/71606534/93719212-dc889b00-fb35-11ea-81d2-cd3539474159.png)

**Your Desktop:**
 - OS: Windows 10
 - App Version = 2.1.9

**Describe the bug**
The one side of the flip cards in the screenshots is showing as unowned, but I have at least one of all of them. On the progress page, it shows I own only 88% of Zendikar Rising but I have at least one of every card so it should be 100%. When I checked the collection page and sorted by Unowned cards from Zendikar Rising, these are the cards it shows I do not own in the screenshots. For example in the screenshots it shows I do not have 6 of the Pathway lands but I really have a set of 4 for all the Pathway lands available in Arena. (screenshot below)

**To Reproduce**
Check your collection listed on the website versus in the Arena client to see that you do own the cards it lists as unowned on the website. This screenshot is from the Arena Client showing I have all the Pathway lands the website says I do not own.
![Screenshot (63)](https://user-images.githubusercontent.com/71606534/93719522-ec08e380-fb37-11ea-97e2-ff0866cfff8e.png)

**Comment by Razviar** [comment]
I can confirm that new type of double-sided cards is not supported in our system yet. Working on it, might take a while.

**Comment by Razviar** [comment]
We updated cards database, issue should be fixed by now. Please update affected pages with ctrl+f5 and let me know if it helped.

**Comment by Avatar1971** [comment]
Thank you for such a fast response, the cards are showing up as owned now.
