### ISSUE TITLE
Event page not loading

### ISSUE THREAD

**Issue by SmugglerArashi** [Razviar/mtgap#188]
**Detailed context (ISSUES WILL NOT BE INVESIGATED WITHOUT IT!):**
- Link to your MTGA Pro account
- Link to page/pages are in question: https://mtgarena.pro/direct-limited/ 
- Screenshots of issue if applicable 
![image](https://user-images.githubusercontent.com/71737039/93946970-9c2d4680-fd08-11ea-8b76-6e9f1dd92035.png)

**Your Desktop:**
 - OS: Win 10 Pro 64
 - App Version 2.19

**Describe the bug**
Event page for Direct Limited won't load.

**To Reproduce**
1. Go to https://mtgarena.pro/direct-limited/ 
2. Click on Create Event
3. Scroll down to Or sit there idly until the event page loads...die of old age
4. spinning white mana symbol...

**Comment by gardenofwine** [comment]
This happens to me as well. I hope this feature would be available, I just found out about it and would be happy to use it. However if it's deprecated then the page should probably say that.

**Comment by Razviar** [comment]
Unfortunately this service was closed and not supported anymore.
