### ISSUE TITLE
Pack 1 Pick 1 Draft Picks Not Showing

### ISSUE THREAD

**Issue by WillHops01** [Razviar/mtgap#193]
I am able to use the Pro Tracker tool to export my draft logs to the MTG Arena Pro website. I am also able to see the picks that I took and other potential picks for all my drafts EXCEPT for pack 1 pick 1 which only shows the card I picked, and not any of the other cards.

**Comment by Razviar** [comment]
This is how data is being served in MTGA log. We can't fix that.
