### ISSUE TITLE
Error Occured! window when accessing my Profile page on Firefox

### ISSUE THREAD

**Issue by necromanek** [Razviar/mtgap#194]
I have this issue when trying to access my Profile page. I can access Matches for example but not detailed info about my decks. Any idea why is that? Close button doesn't work, Reload button doesn't help. It's been two days now. Thanks!

![Screenshot_2020-10-13 My User Profile MTG Arena Pro](https://user-images.githubusercontent.com/54915405/95885924-2d2e9500-0d7e-11eb-8f73-55845c8248e0.png)

**Comment by Razviar** [comment]
Can you please share direct link to your profile so I could check?

**Comment by Razviar** [comment]
Sorry, we were unable to reproduce the issue. https://mtgarena.pro/u/ncr is accessible from latest Firefox both with logged in and logged out user. Probably you should try to clear browser cache.

**Comment by Razviar** [comment]
Closing this for housekeeping purposes. If you have anything to add, feel free to do it, I'll reopen it if that will be needed.
