### ISSUE TITLE
Website not rendering properly, cant find decks i can build with my collection tried on several browser

### ISSUE THREAD

**Issue by iurirolho** [Razviar/mtgap#197]
i tried emailing the email on site and also asking in discord but to this day I got no reply, this is what the page looks like I cant seem to be able to browse any decks I can build not matter the setting can you give a idea of why this happens, i wanna play new decks but only with cards i own
![image](https://user-images.githubusercontent.com/20928051/97115105-9c947500-16ec-11eb-912a-105bf9d366f4.png)

**Comment by Razviar** [comment]
Hello. Do you have collection synced?

**Comment by iurirolho** [comment]
i do indeed, last time i checked i synced, i tried syncing it many times as in the collection it displays my cards

**Comment by iurirolho** [comment]
![image](https://user-images.githubusercontent.com/20928051/97116381-91ddde00-16f4-11eb-8fd1-40d7e96f296b.png)
as you can see it synced indeed

**Comment by iurirolho** [comment]
hopefully, we can figure why the site is miss behaving on my end

**Comment by Razviar** [comment]
Please let me know your username on mtga.pro website, we will look into this.

Also, do you see decks with other filters? Like, "draftable" etc?

**Comment by iurirolho** [comment]
i can see with other filters so far, my username is iurirolho i think

**Comment by iurirolho** [comment]
mtga.cc/u/iurirolho

**Comment by Razviar** [comment]
It might be that you just need to increase time filter (on the screenshot I can see you have set it to latest 30 days) to get more decks. But we will look into it

**Comment by iurirolho** [comment]
i changed the filter but i would want to see for all types of sets if that's possible

**Comment by iurirolho** [comment]
you could implement a show all sets as a option for checking what I can build in terms of decks

**Comment by Razviar** [comment]
We just checked, and you have collection complete only at 4.62%. So there's very few decks you can make from cards you have. There's no bug in our system. To get more decks you should expand time filter like this https://mtgarena.pro/decks/?community#date-1525132800;ufilter-1
