### ISSUE TITLE
Not tracking all data.

### ISSUE THREAD

**Issue by icyamashita** [Razviar/mtgap#198]
**Detailed context (ISSUES WILL NOT BE INVESIGATED WITHOUT IT!):**
- Link to your MTGA Pro account : mtga.cc/u/BELGDOR

**Your Desktop:**
 - OS: Windows 10
 - App Version 2.1.12

**Describe the bug**
MyArena doesn't reflect the data even though the account has been synced.
My Decks, Matches, Colletion and all others.

**Comment by Razviar** [comment]
Try to wipe settings, restart everything and sync again

**Comment by icyamashita** [comment]
I wiped, set, and restarted, but the situation doesn't change.
I also reinstalled MTGArena and MTGApro, but they are the same.

The login is successful.
![er_1](https://user-images.githubusercontent.com/46469694/98679762-d2e81a80-23a3-11eb-9870-b0c5e7f3b67e.PNG)
![er_2](https://user-images.githubusercontent.com/46469694/98679766-d4194780-23a3-11eb-9d7b-34f44d7c63d0.PNG)
Ranking information has not been obtained.
![er_3](https://user-images.githubusercontent.com/46469694/98679768-d4b1de00-23a3-11eb-8a7a-74c11e8124ea.PNG)
Log parsing is complete.
![er_4](https://user-images.githubusercontent.com/46469694/98679772-d54a7480-23a3-11eb-8998-fa804d29a9b5.PNG)
The match record is not displayed.
![er_5](https://user-images.githubusercontent.com/46469694/98679780-d8456500-23a3-11eb-95ea-6169a5a6f993.PNG)
Card list of owned is not displayed.
![er_6](https://user-images.githubusercontent.com/46469694/98679782-da0f2880-23a3-11eb-904b-1634657ec8c0.PNG)

**Comment by icyamashita** [comment]
I installed and tested MTG Arena and MTG Apro on another PC and got the same results.
Is there a problem syncing your account, not the app?

**Comment by Razviar** [comment]
https://github.com/Razviar/mtgap/releases/tag/v2.1.12

Try standalone version, it might work

**Comment by icyamashita** [comment]
I tried the standalone version and the results were the same.
I have confirmed that the MTGARENA log has been generated.

**Comment by Razviar** [comment]
I can't recommend you anything at this point, we will look into it and see if we can figure out why data isn't being uploaded. If both overwolf and standalone versions are not working, it might be some rare case of incompatibility and/or some networking issues on your side

**Comment by icyamashita** [comment]
Thank you.
Unfortunately, I will give up using it at this time.
I want to delete my account, can you tell me how to do it?

**Comment by Razviar** [comment]
On user page mtgarena.pro/u/ in account settings there's deletion tool.
