### ISSUE TITLE
Boosters not being tracked

### ISSUE THREAD

**Issue by belugas64** [Razviar/mtgap#199]
MTGA Pro link: mtga.cc/u/Artoo_Detoo
MTGA Pro ID: 189339
MTG Arena ID: Artoo_Detoo#87904

Desktop: Windows 10
App version: 2.1.12

Program is not tracking all of the boosters that I have been opening.  For example, I received 3 Zendikar Rising boosters recently and opened them all, but the program is only tracking one of them:

![image](https://user-images.githubusercontent.com/74467345/99154249-50e64300-267c-11eb-9b49-6555b72eb011.png)

Only one booster is being tracked on the boosters page as well:

![image](https://user-images.githubusercontent.com/74467345/99154291-a7538180-267c-11eb-9f7e-213fef341d42.png)

This has been much worse in the past when I opened around 40-50 boosters but only 7 of them are being tracked:

![image](https://user-images.githubusercontent.com/74467345/99154328-e71a6900-267c-11eb-9d89-d623e0388a3d.png)

**Comment by Razviar** [comment]
Thanks for reporting! Can you check if it's only Boosters issue? Collection is being tracked correctly?

**Comment by belugas64** [comment]
Yes, collection looks like it's being tracked correctly.

**Comment by Razviar** [comment]
Looks like we have repeatable pattern with quick succession of booster openings (when you open several within one minute). Probably it's anti-doubles feature is causing the issue, since some time before we had issue with double records of the same boosters and applied respective patch. We are now looking for the way to fix both issues.

**Comment by belugas64** [comment]
Thanks for the update!  Really appreciate the quick reaction.

**Comment by belugas64** [comment]
Hey, sorry for bugging, but did anyone find anything with regards to this issue?  It's okay if you haven't, but I'm just wondering since it still occurs.  Thanks.

**Comment by Razviar** [comment]
We are back to investigation of this issue.

**Comment by Razviar** [comment]
We just implemented an attempt to fix this issue

**Comment by belugas64** [comment]
For the time being, this seems to have been fixed.  Thank you!
