### ISSUE TITLE
Pro Tracker not installing due to too many dependancies not included

### ISSUE THREAD

**Issue by Kender42** [Razviar/mtgap#2]
App won't install, error says that FFMPEG is not installed but it is installed just not in a default directory. Even after putting FFMPEG into windows environment variable, issue still remains.

[edit] This is for the new ProTracker 2.x

**Comment by Razviar** [comment]
Are you launching EXE file downloaded from Releases section? https://github.com/Razviar/mtgap/releases/tag/v2.0.10

Can you take a screenshot of the error?

**Comment by Kender42** [comment]
Error fixed, forgot to reboot PC
