### ISSUE TITLE
Keep getting this error on Startup

### ISSUE THREAD

**Issue by Kender42** [Razviar/mtgap#20]
Uncaught Exception:
Error: EPERM: operation not permitted, stat 'C:\Users\my user name\AppData\LocalLow\Wizards Of The Coast\MTGA\output_log.txt'
  at statSync (fs.js:856:3)
  at fs.statSync (electron/js2c/asar.js:278.27)
  at Object.fs.statSync (electron/js2c/asar.js:278.27)
  at pe.watch (C:\Users\my user name\AppData\Local\mtgaprotracker\app-2.0.14\resources\app\.webpack\main\inde,,,,:58740)
  at listOnTimeout (internal/timers.js:531:17)
  at processTimers (internal/timers.js:475:7)

I would have uploaded a screenshot but github says that it can't process the image

**Comment by Razviar** [comment]
It means that your OS doesn't let tracker to access file. You should set up security permissions.

**Comment by Kender42** [comment]
It just started happening about 5 minutes ago and now I get this everytime I start it

**Comment by Razviar** [comment]
Do you have latest version? Try manual update

**Comment by Kender42** [comment]
Yes I have the latest version. I downloaded it earlier this morning

**Comment by Kender42** [comment]
I usually get this error when programs try to run from AppData instead of Program Files

**Comment by stijndp** [comment]
2 quick possible reasons I can think of

1. No file permissions.
If this was the case, it would have occurred in previous versions also. But it is something you can try on your end @Kender42 
Solution 1: Run MTGA Pro Tracker as administrator
Solution 2: Manually set security. In explorer right click the folder "MTGA" in "C:\Users\my user name\AppData\LocalLow\Wizards Of The Coast\" > "Properties" > go to "Security" tab> click "Edit" > select "Users (YOUR_MACHINE_NAME\Users)" > select "Full control" under "Allow" > click "Apply" and then "Ok".

2. Program is reading the log with a too short interval.
It's possible that the software/hardware of Kender42 can't follow. Could be very slow hard drive, CPU too busy with others things or anti-virus holding something up just long enough for 2 reads to overlap.
It seems when libs like settings-store or json-storage read a file, it also locks the file. So maybe it's a limitation of Electron that files always get locked. And that is the error that Electron API gives if a locked file is trying to be read.
In contrast with MTGA pro v1 where filestreams were opening with read-only access and it doesn't matter if 20 processes access the same file at the same time.

Could be a lot of other things but I think these are the 2 main possible reasons.

**Comment by Razviar** [comment]
v16 with this issue fix is rolled out
