### ISSUE TITLE
Kaladesh Affecting Standard Progress Tracker

### ISSUE THREAD

**Issue by superpowered** [Razviar/mtgap#200]
**Detailed context (ISSUES WILL NOT BE INVESIGATED WITHOUT IT!):**
- mtga.cc/u/User.42209
- https://mtgarena.pro/progress
- Screenshots: 
<img width="1651" alt="kldprogressbug" src="https://user-images.githubusercontent.com/7035467/99615431-04cf3180-29e1-11eb-9779-7cdc6e90d084.png">
<img width="1569" alt="kldprogressbug2" src="https://user-images.githubusercontent.com/7035467/99615664-714a3080-29e1-11eb-8cc6-f01039423afa.png">

**Your Desktop:**
 - OS: Windows 10 Currently (with some previous OSX data)
 - App Version 2.1.12

**Describe the bug**
After the Kaladesh launch, the standard progress tracker showed a decrease in percent collected, even though Kaladesh is a historic only set. My assumption is that the tracker is still incorrectly marking it as standard (since it was taken out before historic was a thing)

**To Reproduce**
1. Go to Progress
2. View chart (Standard by default)
3. Note the dip in percentage, on Nov 9-10 even though the raw number counts are the same.

Side note: is there a repo for the website anywhere? I was considering doing a PR and fixing it myself, but could only find the repo for the electron app side of things.

**Comment by Razviar** [comment]
Thanks for reporting! We had KLR wrongfully marked as Standard indeed. Now it's fixed. I'm not sure if chart will get corrected, since that data is being recorded statically. But thanks to your report we will prevent such errors in future.

**Comment by superpowered** [comment]
It did in fact fix the chart!
