### ISSUE TITLE
Continuous pop-up ads on web site are annoying

### ISSUE THREAD

**Issue by MikeTheLiberal** [Razviar/mtgap#201]
**Detailed context:**
The new ads which pop-up, then stay open for 5 seconds before you close isn't that bad.

The fact that it happens every **ten seconds** is very annoying.

**Proposed Workflow**

Please set these up to either pop-up only once per page, or at a minimum no less than 30 seconds. The ad gets in the way of me reading the context of the page, especially on a laptop.

**Comment by Razviar** [comment]
Hello! We will convey this request to our ads agency
