### ISSUE TITLE
Booster History Page crashes when the edition 'G18' is chosen

### ISSUE THREAD

**Issue by jjrde** [Razviar/mtgap#211]
- Link to your MTGA Pro account: mtga.cc/u/Jonny
- Link to page/pages are in question: https://mtgarena.pro/boosters

**Your Desktop:**
 - OS: Windows 10
 - Browser: Firefox, version 85.0
 - Addon: ublock Origin
 
App-Info (Irrelevant, provided anyways):
 - App type: Standalone
 - App Version: 2.1.14

**Describe the bug**
On the Booster History page if one chooses the 'G18' set - the site crashes.

**To Reproduce**
1. Go to https://mtgarena.pro/boosters
2. Click on the set picker
3. Pick 'G18'

**Comment by Razviar** [comment]
We emulated your account environment (collection, booster data, etc.), logged in, applied G18 filter and got empty output, but no error. Please try to clear browser cache. If error persists, please take some screenshots or record video of this error happening.

**Comment by jjrde** [comment]
I'm using 'ublock Origin' btw.
I'm getting the following error in the browser console:

TypeError: r[(+ this.state.currentSet)][4] is undefined
    render https://static.mtgarena.pro/520.e7466b41dd2d23611ebc.js:1
    map https://static.mtgarena.pro/main.a7d3eb8fabf1c530ec82.js:2
    render https://static.mtgarena.pro/520.e7466b41dd2d23611ebc.js:1
    Ho https://static.mtgarena.pro/main.a7d3eb8fabf1c530ec82.js:2
    Uo https://static.mtgarena.pro/main.a7d3eb8fabf1c530ec82.js:2
    Hs https://static.mtgarena.pro/main.a7d3eb8fabf1c530ec82.js:2
    Cl https://static.mtgarena.pro/main.a7d3eb8fabf1c530ec82.js:2
    wl https://static.mtgarena.pro/main.a7d3eb8fabf1c530ec82.js:2
    _l https://static.mtgarena.pro/main.a7d3eb8fabf1c530ec82.js:2
    dl https://static.mtgarena.pro/main.a7d3eb8fabf1c530ec82.js:2
    Yr https://static.mtgarena.pro/main.a7d3eb8fabf1c530ec82.js:2
    unstable_runWithPriority https://static.mtgarena.pro/main.a7d3eb8fabf1c530ec82.js:2
    Hr https://static.mtgarena.pro/main.a7d3eb8fabf1c530ec82.js:2
    Yr https://static.mtgarena.pro/main.a7d3eb8fabf1c530ec82.js:2
    Wr https://static.mtgarena.pro/main.a7d3eb8fabf1c530ec82.js:2
    je https://static.mtgarena.pro/main.a7d3eb8fabf1c530ec82.js:2
    $t https://static.mtgarena.pro/main.a7d3eb8fabf1c530ec82.js:2
    En https://static.mtgarena.pro/main.a7d3eb8fabf1c530ec82.js:2
    In https://static.mtgarena.pro/main.a7d3eb8fabf1c530ec82.js:2
    Tn https://static.mtgarena.pro/main.a7d3eb8fabf1c530ec82.js:2
    Tn https://static.mtgarena.pro/main.a7d3eb8fabf1c530ec82.js:2
    Ql https://static.mtgarena.pro/main.a7d3eb8fabf1c530ec82.js:2
    _reactRootContainer https://static.mtgarena.pro/main.a7d3eb8fabf1c530ec82.js:2
    eu https://static.mtgarena.pro/main.a7d3eb8fabf1c530ec82.js:2
    render https://static.mtgarena.pro/main.a7d3eb8fabf1c530ec82.js:2
    l https://static.mtgarena.pro/main.a7d3eb8fabf1c530ec82.js:2
    9521 https://static.mtgarena.pro/main.a7d3eb8fabf1c530ec82.js:2
    9521 https://static.mtgarena.pro/main.a7d3eb8fabf1c530ec82.js:2
    9521 https://static.mtgarena.pro/main.a7d3eb8fabf1c530ec82.js:2
    o https://static.mtgarena.pro/main.a7d3eb8fabf1c530ec82.js:2
    <anonymous> https://static.mtgarena.pro/main.a7d3eb8fabf1c530ec82.js:2
    <anonymous> https://static.mtgarena.pro/main.a7d3eb8fabf1c530ec82.js:2
main.a7d3eb8fabf1c530ec82.js:2:1294015

**Comment by Razviar** [comment]
Adblock might be breaking the site actually

**Comment by jjrde** [comment]
You still might want to look at what's failing here, since ublock is a very common adblocker.
