### ISSUE TITLE
Small request: Add Gems gained on the My Arena>Profile page

### ISSUE THREAD

**Issue by henryyang89** [Razviar/mtgap#212]
Hi there! Really enjoy using mtgarena.pro.

Was looking at my profile page (https://mtgarena.pro/u) and checking out the summary. I noticed an outflow of gold since I used gold to pay for a premiere draft. However, I didn't see an inflow of gems.

Is it possible to add the change in gems in each day's session next to the gold?

**Comment by Razviar** [comment]
Hi! Please check that you have enabled gems publishing. You can do it by clicking Settings button below the avatar and tuning "Daily Publishing Settings" settings.
