### ISSUE TITLE
MTGA Pro is incorrectly detecting new account

### ISSUE THREAD

**Issue by hardbap** [Razviar/mtgap#227]
**Your Desktop:**
 - OS: Mac OS BigSur 11.2.1
 - App type: Standalone 
 - App Version: 2.1.20

**Describe the bug**

The tracker is detecting a new account which isn't the case. It appears to be having an issue parsing the nick.

![MTGA Pro Tracker 2021-03-12 10-21-37](https://user-images.githubusercontent.com/6355/110960847-2e5bf200-831d-11eb-9c94-d878b998d4d7.png)

**To Reproduce**
1. Open the app

**Comment by Razviar** [comment]
Update to 2.1.21 
https://github.com/Razviar/mtgap/releases/tag/v2.1.21

**Comment by hardbap** [comment]
@Razviar There isn't a DMG available for the latest version:

![image](https://user-images.githubusercontent.com/6355/110963919-a4158d00-8320-11eb-9659-008675be4c61.png)

**Comment by Razviar** [comment]
Yeah, we had a little delay, now DMG is in place.
