### ISSUE TITLE
Amount of wildcards isn't synced correctly

### ISSUE THREAD

**Issue by jjrde** [Razviar/mtgap#231]
User on mtgarena.pro:
mtga.cc/collection/?Jonny

Real wildcards as of this posting:
C/U/R/M
1/7/0/5

Wildcards as reported by the tracker and shown on mtgarena.pro:
C/U/R/M
1/7/11/5

Part of the logfile that contains the correct collection information:
[...]{"playerId":"UVLDDHPR4VEANNIZ3D3DMUBFD4","wcCommon":1,"wcUncommon":7,"wcRare":0,"wcMythic":5,[...] 
[UTC_Log - 03-15-2021 19.24.32.log](https://github.com/Razviar/mtgap/files/6144004/UTC_Log.-.03-15-2021.19.24.32.log)

**Comment by jjrde** [comment]
Further info to reproduce:
I did have a lot of wildcards and spent them all.
It might not sync correctly because I have exactly 0 rare wildcards right now.

**Comment by Razviar** [comment]
The issue was 0. Turned out, we had logic preventing 0 to be set as WC count. Now fix is deployed, number should update after next MTGA restart.
