### ISSUE TITLE
Bad UX for deck search from Matches page

### ISSUE THREAD

**Issue by FeChagas** [Razviar/mtgap#232]
I've faced a problem on the page [/matches](https://mtgarena.pro/matches/), in the option to see the opponent's spotted cards, with the option to **Search Decks** based on the cards spotted. Every instance of the action repeats the same request of the first deck viewed.

To reproduce the bug you need to:

1. While logged in go to [https://mtgarena.pro/matches/](https://mtgarena.pro/matches/).
2. On any of your matches click in the column _Opponent_ , in the mana colors, to see the spotted cards from the opponent's deck.
3. On the modal of spotted cards, click in the button **Search Decks**.
4. Repeat the steps above with any other match/history, and the result of clicking on the **Search Decks** button will be the previous/first set search parameters being used.

**Comment by jjosborne** [comment]
Having same issue, it's not pulling up anything relevant.

**Comment by Razviar** [comment]
Before you click on "Search decks" button, you should also click on the cards you want to search. You can select several cards from opponent's deck and then it will search decks having those cards. I understand that interface is not clear, we will fix it to make smooth UX.

**Comment by Razviar** [comment]
We just added explanation text, for now we will leave it there.
