### ISSUE TITLE
MTGA Update Breaking Changes? (again)

### ISSUE THREAD

**Issue by belugas64** [Razviar/mtgap#233]
MTGA Pro link: mtga.cc/u/Artoo_Detoo
MTGA Pro ID: 189339
MTG Arena ID: Artoo_Detoo#87904

Desktop: Windows 10
App version: 2.1.22

The newest MTGA update may have broken everything again.  Everything was tracking fine today until the update.  I finished 15 wins but only the first 7 wins were recorded:

![image](https://user-images.githubusercontent.com/74467345/112342396-90f7ab00-8c98-11eb-93c9-53554a631d11.png)

![image](https://user-images.githubusercontent.com/74467345/112342628-c2707680-8c98-11eb-868c-93cc0e0ab018.png)

This time the program is parsing the logs so I'm not sure what changes were made in the update:

![image](https://user-images.githubusercontent.com/74467345/112342799-eaf87080-8c98-11eb-880c-6011cd16c42c.png)

Sorry if this issue is something on my end and not actually linked to the newest update.

**Comment by Razviar** [comment]
This time no breaking changes. This is known issue, sometimes MTGA tracking is getting messy right after update (when game is running with elevated permissions needed for update installation). You just need to get update, run MTGA, close it, then run again and everything will work fine. Also you could try to wipe tracker settings, it might help to pick up missing matches.

**Comment by belugas64** [comment]
I do restart both the tracker and Arena after each update, but only this time it didn't update.  I will wipe settings and try again.  Thanks.

**Comment by belugas64** [comment]
It did work after wiping settings.  Thank you very much, sorry for bothering you!

**Comment by Razviar** [comment]
@belugas64 you need to restart Arena only after update.

**Comment by belugas64** [comment]
Yes, I know, that's what I do and that's what I did, but it didn't work this time until only after I wiped settings.  Thanks again!
