### ISSUE TITLE
Win/Loss column on My Decks page not sorting correctly

### ISSUE THREAD

**Issue by lrgrego** [Razviar/mtgap#238]
**Detailed context (ISSUES WILL NOT BE INVESIGATED WITHOUT IT!):**
- mtga.cc/u/Lee Gregory
- https://mtgarena.pro/decks/?my

**Your Desktop:**
 - OS: [Windows 10]
 - App type: Standalone

**Describe the bug**
This was working last week.  Today when you click on the Win/Loss column it is not sorting by win/loss percentage.  It's pretty easy to see.

**To Reproduce**
1. Go to My Arena/My Decks
2. Click on W/L Column to sort either ascending or descending, both are broken.
3. See error

**Comment by Razviar** [comment]
Winloss sorting is now fixed.

**Comment by Tr0ll13n** [comment]
Works well, thx!
