### ISSUE TITLE
Deck sort on win/loss ratio no longer working

### ISSUE THREAD

**Issue by Tr0ll13n** [Razviar/mtgap#239]
**Detailed context (ISSUES WILL NOT BE INVESIGATED WITHOUT IT!):**
- Link to your MTGA Pro account: mtga.cc/u/Tr0ll13n
- Link to page/pages are in question: https://mtgarena.pro/decks/?my#srt-9;direct-2

**Your Desktop:**
 - OS: Windows 10
 - App type: Standalone
 - App Version: 2.1.24 

**Describe the bug**
Sorting deck by win/loss ratio is no longer working. The page displayed only contains a few subsets of decks, and trying to change time filter or other parameters doesn't change anything.

**To Reproduce**
1. Go to https://mtgarena.pro/decks/?my :: all decks are correctly displayed
2. Click on W/L colum header :: decks are properly sorted by w/l ratio, but only a handful of them

It has been working correctly since I reinstalled the app on April 4th this year.

**Comment by Razviar** [comment]
We just closed #238 this morning and issue was resolved. Try to update the page with ctrl+f5. We will investigate meanwhile

**Comment by Razviar** [comment]
Update: yeah, we can see the issue, it's confirmed. Investigating.

**Comment by Razviar** [comment]
Update: resolved. Try ctrl+f5 to see the fix. Thanks for reporting!
