### ISSUE TITLE
Restore password not working

### ISSUE THREAD

**Issue by nightday88** [Razviar/mtgap#241]
I'm trying to restore/reset my password off the login page.  After entering my email, the "Requesting password reset" appears, but stays no matter how long I wait.  I've tried this on Windows 10 with Firefox, Internet Explorer, Edge and Chrome with the same result.  Also attempting on Android with Firefox and Chrome have the same result as well.

**Comment by Razviar** [comment]
Spam filters oftenly prevent mails to go though (mail might not reach even the spam folder, get zapped on the server). Let me know your email and username, I'll make a new password for you.

**Comment by nightday88** [comment]
Is there a place I can message you directly, don't want to pot it on GH.  Thanks

**Comment by Razviar** [comment]
Please use admin@mtgarena.pro
Also you should try again, we fixed global issue, maybe you'll be able to login

**Comment by Razviar** [comment]
Everyone having this issue should clear cache (reload site with Ctrl+f5) and try again with old credentials

**Comment by Razviar** [comment]
fixed
