### ISSUE TITLE
Meta not loading

### ISSUE THREAD

**Issue by Tsmithjr9** [Razviar/mtgap#242]
**Detailed context (ISSUES WILL NOT BE INVESIGATED WITHOUT IT!):**
- mtga.cc/u/Thomas Smith
- https://mtgarena.pro/cards/#rulings-2;srt-1;direct-0
- 
![image](https://user-images.githubusercontent.com/83510144/116789079-1c741100-aa7b-11eb-8fb9-4cd5fa714f69.png)

**Your Desktop:**
 - OS: Windows 10
 - App type: Not using App
 - App Version Not using App

**Describe the bug**
When viewing the Meta of Cards, only Tier A & first part of Tier B display, then there is the spinning symbol in the screenshot. I wait up to 10 minutes and the rest of the page won't display. Refreshing the browser window does nothing.

**To Reproduce**
1. Go to the Meta of Cards link & open the page
2. Scroll down to Tier B and you will see the spinning symbol

**Comment by Razviar** [comment]
Thanks for reporting! Now it's fixed. Please use ctrl+f5 to see the difference.
