### ISSUE TITLE
Stuck at Play 1 match (Even with Sparky)

### ISSUE THREAD

**Issue by Nikralx** [Razviar/mtgap#254]
**Detailed context (ISSUES WILL NOT BE INVESIGATED WITHOUT IT!):**
- None
- NA
- NA

**Your Desktop:**
 - OS: Win 10
 - App type: Standalone
 - App Version: 2.1.25

**Describe the bug**
Installed the tracker, setup the location of MTGA log and files. It says I need to "Play 1 match" for the overlay to start working.
Played 2 vs Sparky and 1 vs Human, still the same message.
Enable Overlay is turned on. Tried rebooting the game and the tracker. 

**To Reproduce**
1. Installed
2. Open MTGA/Open Tracker
3. Start Game

**Comment by rmjohnson144** [comment]
Same here.  I played sparky, 5-6 matches vs real opponents in Bo1

**Comment by Razviar** [comment]
WOTC messed up logs after updated, so we have to track down all changes and get it fixed. It will take some time.

**Comment by Razviar** [comment]
Update: for some incomprehensible reason WOTC removed user screen name from log. Meaning, there's no way to understand from log what is players screen name. And we used screen names for many reasons, so currently we will have to find some workaround, unfortunately.

**Comment by Razviar** [comment]
We were able to find the way to pick up screen name, so 2.1.26 is being deployed right now.

**Comment by Nikralx** [comment]
Works for me now. Thanks.
