### ISSUE TITLE
Matches are not counted correctly after July MTGA update

### ISSUE THREAD

**Issue by Thalanthier** [Razviar/mtgap#255]
**Detailed context (ISSUES WILL NOT BE INVESIGATED WITHOUT IT!):**
- mtga.cc/u/Thalanthier
- none
- none 

**Your Desktop:**
 - OS: Windows 10
 - App type: Standalone
 - App Version 2.1.26

**Describe the bug**
Card and gold gains are counted, matches dont. Wheter on mainprofile, nor in the matches section. This is happening since the new MTGA Arena Update. (the last described Bug also happend to me but is now fixed with the new version) 

**To Reproduce**
1. Installed
2. Open MTGA/Open Tracker
3. Start Game
4. Win or loose a game

**Comment by Razviar** [comment]
Wotc removed crucial data from log related to matches. We are working on the workaround.

**Comment by Thalanthier** [comment]
> Wotc removed crucial data from log related to matches. We are working on the workaround.

Thank you for the fast replie :) !! Good luck while fixing!

**Comment by Thalanthier** [comment]
Now some of the games seems to be shown but with wrong results

![image](https://user-images.githubusercontent.com/87185792/125176676-a821c080-e1d5-11eb-836e-e05e9890615b.png)

**Comment by Razviar** [comment]
We are currently looking for more reliable way to detect winner of match. This is temporary solution.

**Comment by Thalanthier** [comment]
But its not only date and gamelength. I Nearly won every of this games and it where a lot more

**Comment by Razviar** [comment]
@Thalanthier we did some updates this morning, which should improve accuracy of wins detection. Also, we know about date issues, WOTC removed timestamps from logs as well, so we will switch to user PC time as timestamp provider in upcoming release.

**Comment by Thalanthier** [comment]
Yes, just checked. Now win/loss is accurate. Good job mate. Thx!!

**Comment by Thalanthier** [comment]
After deleting my old Acc and trying to start a new one the following message doesnt dissapear (by following the instructions and logging in MTGA playing a game) (btw should i continue testing and deliver results or am i disturbing your fixing routine?) 

![image](https://user-images.githubusercontent.com/87185792/125200223-5d05bd00-e26a-11eb-81f5-2321c3cece9c.png)

**Comment by Razviar** [comment]
@Thalanthier try to restart everything, and then logout and login in mtga while tracker is running. We tested that internally and seen no issues. Right after you logout, you should see error message change. Also, your testing is very helpful, it's always good to have another set of eyes on this stuff

**Comment by Thalanthier** [comment]
Yes, with reboot it worked. Thx a lot. Have a nice evening :) !!

**Comment by Thalanthier** [comment]
Matches now work too. Also Boosterstats. Deckstats doesnt

**Comment by Razviar** [comment]
What do you mean by "Deckstats"? Winloss stats are not updating?

**Comment by Thalanthier** [comment]
Now the Win/Loss Stats are broken again. I think they just switched

**Comment by Razviar** [comment]
Should be working fine in latest tracker version.
