### ISSUE TITLE
Wins counted as losses

### ISSUE THREAD

**Issue by veritas324** [Razviar/mtgap#256]
I was playing best of one ranked historic. I won my last two games, but the tracker counted both of them as losses. I thought it might be a bug. I won by concession in both games.
![Screenshot 2021-07-12 183859](https://user-images.githubusercontent.com/65451955/125364727-facbbb80-e340-11eb-8387-96df2d50af4c.png)
![Screenshot 2021-07-12 184157](https://user-images.githubusercontent.com/65451955/125364730-fdc6ac00-e340-11eb-9029-cddc05a4654c.png)
![Screenshot 2021-07-12 184217](https://user-images.githubusercontent.com/65451955/125364732-ff906f80-e340-11eb-90e0-26945884597e.png)

**Comment by Razviar** [comment]
Unfortunately WOTC removed crucial data for detecting wins from logs. We detect wins only by circumstantial signs, to be specific - updates in daily/weekly wins. This is temporary situation while we are actively looking for workaround.

**Comment by veritas324** [comment]
Thank you for the reply. Indeed, I was beyond daily and weekly wins when this happened yesterday. Wizards is the worst. Best wishes.

**Comment by Razviar** [comment]
After latest MTGA patch it's resolved.
