### ISSUE TITLE
Error on deck page

### ISSUE THREAD

**Issue by Isotera** [Razviar/mtgap#257]
**Detailed context (ISSUES WILL NOT BE INVESIGATED WITHOUT IT!):**
- n/a (no account registered yet)
- https://mtgarena.pro/decks/mono-black-snow-control-2022
- https://prnt.sc/1bv08y1

**Your Desktop:**
 - OS: win 10
 - App type: firefox
 - App Version: up to date as of 7/16/21 (unsure of build)

**Describe the bug**
Error occurred persisting on link; causes this same error to spread to the next black deck you open on the featured black page, after opening the bugged page; disappears on the next deck if you hit refresh

**To Reproduce**
1. Open firefox
2. Open link to decklist listed above
3. Back out of page to featured black decks
4. click on another deck

**Comment by FilthySerf** [comment]
I'm getting this as well on Firefox and Chrome.

It does this when trying to view a deck and when trying to get data from a match. I haven't seen it happen with anything else though.

**Comment by Razviar** [comment]
Issue resolved, thanks for reporting
