### ISSUE TITLE
error occured on specific deck url

### ISSUE THREAD

**Issue by SnickerZorMarZ** [Razviar/mtgap#258]
**Detailed context (ISSUES WILL NOT BE INVESTIGATED WITHOUT IT!):**
- Link to your MTGA Pro account
- [](https://mtgarena.pro/decks/control-center-color-challenge)
![Unbenannt](https://user-images.githubusercontent.com/87564220/126031706-e95d5b3a-b78a-4aeb-adf4-73e05462a76e.JPG)

**Your Desktop:**
 - OS: Windows 10
 - App type: Chrome
 - App Version newest

**Describe the bug**
[](https://mtgarena.pro/decks/control-center-color-challenge) this url doesnt load, only error messaging also when: refreshing, adblockers off, cookies delete, I tried everything
**To Reproduce**
1. Go to [](https://mtgarena.pro/decks/control-center-color-challenge)

**Comment by Razviar** [comment]
This is the same issue as  #257 . We are investigating
