### ISSUE TITLE
Can't sync account

### ISSUE THREAD

**Issue by maciejga** [Razviar/mtgap#26]
Hi,

after i remove account from website and create anohter i can't sync tracker 

_Curent user: null_

On accounts list i have:
Nick: null 

Click "unlink" on this list. open page:

_Invalid request
Provided token is not valid or already have been activated._

**Comment by Razviar** [comment]
What is your mtga Nick?

**Comment by Razviar** [comment]
You can now wipe settings in tracker and re-sync you tracker with new account.

**Comment by maciejga** [comment]
Awesome!
Your tracker is ready to work!

Thanks :)
