### ISSUE TITLE
AFR Cards Missing in Card Tracker

### ISSUE THREAD

**Issue by socksinbirkenstocks** [Razviar/mtgap#261]
Sorry if this is not the right place to raise this issue

Cards missing:
'Aberrant Mind Sorcerer', 
'Goblin Morningstar',
'Lightfoot Rogue',
'Loathsome Troll',
'Power of Persuasion'

Profile
- https://mtgarena.pro/u/mateofeo

**Comment by Razviar** [comment]
Hello! What do you mean by 'missing'? You have those in collection, but it's not rendered in account?

**Comment by socksinbirkenstocks** [comment]
Yeah, and when searching in the card library, these cards don't show up as well.

**Comment by Razviar** [comment]
Issue is resolved, try ctrl+f5 to see cards rendering properly.
