### ISSUE TITLE
Can't see my collection

### ISSUE THREAD

**Issue by Superkurtje** [Razviar/mtgap#262]
When I want to see my collection of cards, I get this
![image](https://user-images.githubusercontent.com/89470851/130642752-8bba78be-c20f-41c7-bca2-9d79f43fce6f.png)

**Comment by Razviar** [comment]
Hello! What is your mtga.pro username?

**Comment by Razviar** [comment]
The issue is related to game patch being rolled out: https://magicthegatheringarena.statuspage.io/
We applied the patch to fix Collection for now, and will make needed fixes after patch.
