### ISSUE TITLE
Vault progress on web page off by power of 10

### ISSUE THREAD

**Issue by mahamoti64** [Razviar/mtgap#264]
https://mtgarena.pro/progress/?Mahamoti64#tab-Vault

I opened a bunch of packs yesterday, and my vault progress went from 370% to 490%.  However on mtgarena.pro web page, my vault progress spiked up to 4904%.  Looks like it missed the decimal point?

Then today I logged in and redeemed the vault three times to bring it down to 190% in hopes that would help.  Well, it did lower it, but it's still off by a power of 10 as the web page link above will show.

I'm running Windows 10.

Arena vault stats:
![image](https://user-images.githubusercontent.com/72120622/131592769-23ffcd30-dac7-419d-b482-4935e69eac88.png)

web page vault stats:
![image](https://user-images.githubusercontent.com/72120622/131592820-2a3d2455-3c32-443f-9d74-604d13dd33c3.png)

Thanks,
Jeff

**Comment by Razviar** [comment]
That's consequences of recent mtga update, which broke pretty much everything in log. Thanks for reporting, we'll fix it

**Comment by mahamoti64** [comment]
This looks like it is fixed now, so I'll close it.  Thanks.
