### ISSUE TITLE
Profile not working

### ISSUE THREAD

**Issue by Norua88** [Razviar/mtgap#265]
**Detailed context (ISSUES WILL NOT BE INVESIGATED WITHOUT IT!):**
Norua#48645
https://mtgarena.pro/u/
<img width="2048" alt="Screen Shot 2021-09-06 at 11 46 57" src="https://user-images.githubusercontent.com/31585005/132181346-36cb93b6-b1dc-401f-9ba0-dac38810310b.png">

**Your Desktop:**
macOS Big Sur (but the issue is on the browser)

**Describe the bug**
As for the attached screenshot, I'm getting that error

**To Reproduce**
Steps to reproduce the behaviour:
1. Just go on the profile
2. When is loading the data I'm getting the error, if I don't scroll i don't get the error

**Comment by Razviar** [comment]
I just checked, the profile https://mtgarena.pro/u/Matteo%20Spica is working fine, no errors detected. If you are still having the issue, please try to disable adblock, clear the cache and try to reload the page.
