### ISSUE TITLE
The 'Bugs and Suggestions' link at the bottom of the page is incorrect

### ISSUE THREAD

**Issue by johnprobable** [Razviar/mtgap#269]
**Detailed context (ISSUES WILL NOT BE INVESIGATED WITHOUT IT!):**
- Link to your MTGA Pro account (not relevant)
- Link to page/pages are in question (at the bottom of every page)
- Screenshots of issue if applicable  (not relevant)

**Describe the bug**
The link to 'Bugs and Suggestsion' doesn't work because it has the address of the current page at the beginning of it.

**To Reproduce**
1. Go to any page
2. Click on Bugs and Suggestions at the bottom of the page
3. Observe where you get sent to
4. I.e. the link on the homepage is https://mtgarena.pro/https://github.com/Razviar/mtgap/issues instead of https://github.com/Razviar/mtgap/issues

**Comment by Razviar** [comment]
Fixed! Thanks for noticing
