### ISSUE TITLE
[Feature request] Add setting for not adding a desktop shortcut upon update

### ISSUE THREAD

**Issue by Mikaill** [Razviar/mtgap#271]
The desktop icon is added automatically with each update (at least on Windows 10) and recently the updates are more often, to a point that I have to remove the icon at least daily.
I would like to request on option to disable the automatic addition of the desktop shortcut upon update.

**Comment by Razviar** [comment]
This is actually a regression, we had this fixed before, but it got broken again. We'll revisit this issue

**Comment by Razviar** [comment]
Fixed with latest release
