### ISSUE TITLE
tracker doesn't do anything v2.0.15

### ISSUE THREAD

**Issue by necromanek** [Razviar/mtgap#28]
I just updated the tracker but it doesn't collect any data, games are not tracked, W/L ratio for decks stays the same. I synced account, read old log, all automatically and manually, nothing happens.

**Comment by Razviar** [comment]
Try to wipe settings, restart tracker and re-sync again

**Comment by Razviar** [comment]
I can see data uploading from your account, so I suppose I can close this.
