### ISSUE TITLE
settings page isn't scalable, or accessible on its own page

### ISSUE THREAD

**Issue by Prismzet** [Razviar/mtgap#280]
because of this, I'm unable to access certain settings or tabs when things are open, including applying the settings.

Making this its own page, or through the desktop app would be nice

![image](https://user-images.githubusercontent.com/44408896/140661609-72433a3f-52c2-4667-96a7-441af4ebf2b2.png)

**Comment by Razviar** [comment]
Art selectors blocking Apply button are fixed, separate page is under construction right now. Try ctrl+f5 to get fixed page.

**Comment by Razviar** [comment]
Page is ready, now settings are also available at https://mtgarena.pro/settings/
