### ISSUE TITLE
Site: Meta (Any meta's) are severly out of date.

### ISSUE THREAD

**Issue by AradynGaming** [Razviar/mtgap#283]
**Detailed context (ISSUES WILL NOT BE INVESIGATED WITHOUT IT!):**
- Link to your MTGA Pro account: MTGAPro User Nick: Aradyn
Page Links -> Meta Live Standard: https://mtgarena.pro/meta/decks/#rank-28;sort-W
- Screenshots of issue if applicable: Ill try to get one later.

**Your Desktop:**
 - OS: Win 10
 - App type: Standalone
 - App Version: 2.2.13

**Describe the bug**
On MTGArena.Pro, when looking at meta, the "Live (Latest Matches)" has not been updating since July. Attempting to pick "older meta snapshots" does not produce any semi-recent results either.  Stable seems to produce somewhat reasonable timelines, but there is no way to see any current (as of the past month) meta's. I apologize if this was already posted, but I could not find a bug report for it.

**To Reproduce**
1. Go to 'MTGArena.Pro'
2. Click on 'Meta' -> 'Live Standard'
3. See 'Jul 01 - Jul 04' (as well as meta that looks to be about 2 sets behind)

Extra Notes: It seems like all meta is broken/not updating. Current/Stable meta shows sep 16 - Oct 11 (roughly for most categories). I am not sure what the criteria would be there.

**Comment by Razviar** [comment]
We have some issues with meta updates, but you can get alternative meta decks from here: https://mtgarena.pro/decks/?meta

**Comment by AradynGaming** [comment]
It seems like that meta isn't showing properly either.  When I click that link, I only see decks that contain last edition's cards.

**Comment by Razviar** [comment]
We solved meta auto updates issue, now all meta reports are current.
