### ISSUE TITLE
Latest install was pinged by anti-virus software

### ISSUE THREAD

**Issue by MikeTheLiberal** [Razviar/mtgap#284]
Hello, I was surprised this afternoon when the software security team at work sent me this email message:

> Hi Michael,
> 
> We received below antivirus alert for the file " fastlist-0.3.0-x86.exe" on the workstation "<workstation>". Please let us know if this is valid/legitimate file or action.
> 
> Description: This file meets the machine learning-based on-sensor AV protection's low confidence threshold for malicious files.
> Host name: <workstation>
> File name: fastlist-0.3.0-x86.exe
> File path: \Device\HarddiskVolume4\Users\<username>\AppData\Local\mtgaprotracker\app-2.2.13\resources\app\.webpack\main\native_modules\fastlist-0.3.0-x86.exe
> Command line: C:\Users\<username>\AppData\Local\mtgaprotracker\app-2.2.13\resources\app\.webpack\main/native_modules/fastlist-0.3.0-x86.exe
> SHA 256: 6e2802017e5ce324df7a520e3f79e39369ad2a1b6a66c720e951d96bfaeea2c1
> MD5 Hash data: 9c5a908b1a4751f0e1a7fe8d5abfab3c
> Full detection details: https://falcon.crowdstrike.com/activity/detections/detail/a560b3f3e458407baa21ad0fb3936155/77313001124?pid=2483585598934
> Platform: Windows
> IP address: 73.126.84.181
> User name: QUESTUS\<username>
> Detected: Nov. 15, 2021 05:36:01 local time, (2021-11-15 00:06:01 UTC)
> Last behavior: Nov. 15, 2021 05:36:01 local time, (2021-11-15 00:06:01 UTC)

I have deleted my real name and workstation identification for privacy. 

This is an issue, since I have been using this laptop for work for at least two years, and until today, I'd never had a problem with this program.  Needless to say, work is much more important than any game, so I removed the ProTracker from my machine,  Now, I really like the ProTracker, I'm hoping you can fix this issue so I can install a later version of the software. 

You can contact me via email, if you need to get more information.

Thanks for a good web site, and hopefully you'll get this software problem fixed.

**Comment by Razviar** [comment]
Hello! As we explained many times before, this is false positive. https://www.reddit.com/r/MagicArena/comments/qu04bd/malware_warning_turning_up_associated_with/?utm_medium=android_app&utm_source=share
