### ISSUE TITLE
Collection not syncing in Windows

### ISSUE THREAD

**Issue by pedrovgp** [Razviar/mtgap#285]
**Detailed context**
When I access
mtga.cc/collection/?Pedro%20Viana

and filter Owned, I see no cards (see picture below)
![image](https://user-images.githubusercontent.com/2333868/143241586-88f93a8f-6236-4fe2-a61c-6be0ef068bcb.png)

But everything seems to be working fine:
![image](https://user-images.githubusercontent.com/2333868/143241654-63f635e6-c11b-47fe-a8ad-8c506956951e.png)

**Your Desktop:**
 - OS:Windows 10
 - App type: Overwolf
 - App Version 2.2.13

**Describe the bug**
My collection does not sync. It appears empty in mtgarena.pro site, though I have cards in it.

**To Reproduce**
1. Open MTGA Pro Tracker
2. Open MTG Arena
3. Wait for MTGA Pro Tracker to sync
4. Click My Collection
5. Filter Owned Cards
6. See that it is empty

**Comment by Razviar** [comment]
Make sure antivirus is not blocking SharpMonoInjector.dll and other tracker parts.

**Comment by pedrovgp** [comment]
Yes, that worked, that file was being blocked.
