### ISSUE TITLE
Tojan detected by Windows in MGTArena.PRO

### ISSUE THREAD

**Issue by St4r8ucK** [Razviar/mtgap#286]
**Detailed context (ISSUES WILL NOT BE INVESIGATED WITHOUT IT!):**
- Link to your MTGA Pro account : 12181
- Link to page/pages are in question : N/A
- Screenshots of issue if applicable : [http://doitoliv.free.fr/Trojan.PNG](url)

**Your Desktop:**
 - OS: Windows 10 up-to-date
 - App type: Standalone
 - App Version: 2.2.14

**Describe the bug**
"C:\Users\olivi\AppData\Local\mtgaprotracker\packages\mtgaprotracker-2.2.13-full.nupkg" is reported as trojan (Trojan:Win32/Vigorf.A) by Windows 10

**To Reproduce**
Perform a quick security scan with Windows 10

**Comment by Razviar** [comment]
Hello! As we explained many times before, this is false positive. https://www.reddit.com/r/MagicArena/comments/qu04bd/malware_warning_turning_up_associated_with/?utm_medium=android_app&utm_source=share
