### ISSUE TITLE
Account sync not working

### ISSUE THREAD

**Issue by realJohnDoe** [Razviar/mtgap#29]
Hi Razviar,

I just downloaded the new version and the account sync seems to not work. When I click on sync account nothing happens. I think a Browser tab should open to confirm the sync.

**Comment by Plex0n** [comment]
Same happened to me too. Have version 2.0.15, and clicking on sync in app, will not open any website in chrome. Tried to unsync with url mtgarena.pro/sync that allowed me to do that, but now i get an invalid request when trying this url again.

**Comment by Razviar** [comment]
Please go to settings and click WIPE SETTINGS button

**Comment by Plex0n** [comment]
Hi Razviar.

That worked. Thanks for quick response.

**Comment by realJohnDoe** [comment]
For me too :)
Is there a way I can test the new overlay? As far as I understand, it should be implemented again but I could not get it to show up.

**Comment by Razviar** [comment]
Switch it on in overlay settings and then go to game. If you see text "mtga pro overlay" in left bottom corner, it's working. In the next match it'll show up

**Comment by realJohnDoe** [comment]
Nope, no text for me and no overlay in the games. The button is switched on.

**Comment by Razviar** [comment]
Next release it will be there then :)

**Comment by TXSoulja** [comment]
I ran into the sync problem and then did what you said.  That worked.  I just opened a pack (from season rewards)  but the results of my pack opening does not appear on my profile on the site.

**Comment by Razviar** [comment]
v16 with this issue fix is rolled out
