### ISSUE TITLE
Client fails to detect the MTGA connected user and fails to upload data with manual syncing

### ISSUE THREAD

**Issue by MAC-GH** [Razviar/mtgap#290]
**Detailed context (ISSUES WILL NOT BE INVESIGATED WITHOUT IT!):**
- Link to your MTGA Pro account: Allirog#15154 and Pufuletz#40518
- Link to page/pages are in question
- Screenshots of issue if applicable 

**Your Desktop:**
 - OS: Windows 10 x64 v1909
 - App type: Standalone
 - App Version 2.2.14

**Describe the bug**
1. Client fails to detect the MTGA connected user => Awaiting User ID. It will take up to 30s for either case when MTGA starts before or after the tracker and regardless the MTGA connected user. The last version has been problematic and had holes in uploading data to the server although I use the both accounts daily but since a few days it fails to detect them both.
2.  If I choose to sync old logs or I manually pick the logs to parse I get the message "Old logs are uploaded" but most of the data seems missing from the server. Today it finally managed to upload the matches for Allirog#15154 but not the rewards (Jump In event) after a 3 days break.

Modifying the log files (the date and time in their name and the last modification time) did not help to cheat the tracker to upload data with either "Pick log to parse" or "Sync Old Logs" (and btw, why the caps for Old Logs ?).

I use to let the MTGA running while taking breaks and when I return I sometimes get the message "You have been disconnected. Click to reconnect" which I indeed do. I wonder if this case and the user change after reconnect could fool the tracker.

Attached here the today's logs.

[Logs 20211230.zip](https://github.com/Razviar/mtgap/files/7791392/Logs.20211230.zip)

Please let me know if further logs/details are needed.

Kind regards

**Comment by Razviar** [comment]
It's because of injection we use. When tracker is running, we inject our library which makes MTGA to write the data we need into the log, including player ID and screen name. When you pick log manually, and it was generated without tracker injection in place, we can't parse it, because it has no markers we depend on. Unfortunately, WOTC is messing the log update after update, removing crucial data from it, so we were forced to do injection. There's no fix for this issue.

**Comment by MAC-GH** [comment]
Hello,

Thanks for your reply but I'm not sure I understand your worries here: on MTGA account switch, the MTGA starts a new log file which clearly contains the login information:

[Accounts - Login] Logged in successfully. Display Name: Pufuletz#40518

I still wonder why the tracker cannot detect this ? Even if I restart the tracker it persists on showing Current user: Allirog/MTGA nick: Allirog#15154.

Cheers
