### ISSUE TITLE
Overlay not showing

### ISSUE THREAD

**Issue by realJohnDoe** [Razviar/mtgap#3]
First: Thanks for your work and also for updating so quickly after a breaking game update! I appreciate your work.

With the new version I cannot get the overlay to work and the settings to show the overlay are also not saved after a restart of the tracker. Am I missing something? The sync of my collection worked, however.

**Comment by Razviar** [comment]
Overlay is temporary missing since we release this version of tracker very early and didn't finish it yet. It will appear in upcoming releases (I hope by Monday)

**Comment by realJohnDoe** [comment]
Just saw your reddit post. Thanks! :)

**Comment by Razviar** [comment]
I'll reopen it here for better visibility.

**Comment by Toybear1986** [comment]
@Razviar it's showing, but it's empty https://user-images.githubusercontent.com/50303627/71033430-55cb0b80-2128-11ea-85c9-3368112687f3.png

**Comment by Razviar** [comment]
@Toybear1986 that's another issue, and it's not happening in every case

**Comment by Toybear1986** [comment]
@Razviar Do you need a separate report?

**Comment by Razviar** [comment]
@Toybear1986 not really, we know about this issue and working on it
