### ISSUE TITLE
Something happened in 1970....

### ISSUE THREAD

**Issue by Jelly-Flinger** [Razviar/mtgap#30]
My collection data is corrupted. The progress chart shows data beginning in 1970 (maybe 80% complete) and then ramps down to the actual start of my data in July this year.

I think that one data point from this year has the wrong date in 1970?

**Comment by Razviar** [comment]
Are you sure that you were not traveling back in time while using tracker? Cleared some data from 1970 from DB and applied a patch, let's see if it helps.

**Comment by Jelly-Flinger** [comment]
Maybe time travelling, my pc feels like its from the 70s

Looks like its fixed though! Many thanks!
