### ISSUE TITLE
Rewards page not working

### ISSUE THREAD

**Issue by hoplaaaa** [Razviar/mtgap#302]
MTGA Pro account: https://mtgarena.pro/u/Mike.124787
MTG Arena ID: Mike#00490
link to page: https://mtgarena.pro/rewards/

OS: Windows 10
App type: Standalone 
App Version: 2.2.15

Bug:
When I open the rewards page, nothing is displayed and the calendar won't let me select a date (see screenshot below). I tried on Vivaldi and Firefox and the result is the same on both browsers. 

![screenshot](https://user-images.githubusercontent.com/47716448/158059828-f1bea54a-ca7d-475f-8169-68e86868f1fe.PNG)

**Comment by Razviar** [comment]
Fixed.
