### ISSUE TITLE
Webpage (My User Collection): "Error Occured" 

### ISSUE THREAD

**Issue by odbo255** [Razviar/mtgap#305]
Link to account - https://is.gd/DwBUZZ
Link to page - https://mtgarena.pro/u/
![image](https://user-images.githubusercontent.com/102695951/160924677-816dc695-9aee-4792-ad4b-24c62ab82eb0.png)

Edition	Windows 10 Pro
Version	21H2
OS build	19044.1586
Experience	Windows Feature Experience Pack 120.2212.4170.0
Browsers: MS Edge Version 99.0.1150.55 (Official build) (64-bit), Chrome Version 99.0.4844.84 (Official Build) (64-bit)
Standalone App 2.2.15

When either manually going to the "My User Collection" web page, or by using the app links "My Account" or "Profile Settings" the error message appears. I believe only part of the expected user content is shown on the page.

1. Be logged in
2. From the standalone app use either link "My Account" or "Profile Settings"
3. Scroll down
4. Error appears
Or
1. Be logged in
2. Go to https://mtgarena.pro/u/ from browser
3. Scroll down
4. Error appears

**Comment by Razviar** [comment]
Fixed. Thanks for reporting.
