### ISSUE TITLE
Downloading collection from the site I get an empty file

### ISSUE THREAD

**Issue by Lohoris** [Razviar/mtgap#306]
**Detailed context (ISSUES WILL NOT BE INVESIGATED WITHOUT IT!):**
- https://mtgarena.pro/collection/?Lohoris

**Your Desktop:**
 - OS: Mac OS 11.6.5
 - App Version 2.1.35

**Describe the bug**
Downloading collection from the site I get an empty file with just the headers and nothing else.

**To Reproduce**
1. Go to "My Arena" / "Collection"
2. Click on the download icon
3. Click on "MTGGoldfish CSV" (which is the only option available)
4. I get a file named "collection.csv"
5. The file only has the header "Card,Set ID,Set Name,Quantity,Foil" and nothing else

**Comment by Razviar** [comment]
Collection features are not avaliable on Mac after WOTC removed collection data from log in 2021.
