### ISSUE TITLE
Strange Event type in matches history

### ISSUE THREAD

**Issue by At0man** [Razviar/mtgap#308]
**Detailed context (ISSUES WILL NOT BE INVESIGATED WITHOUT IT!):**
- mtga.cc/matches/?Atoman
- mtga.cc/matches/?Atoman
- ![image](https://user-images.githubusercontent.com/103389694/162641889-c4d11e46-19ad-425f-a8bb-1759ad81ff02.png)

**Your Desktop:**
 - OS: Windows 11
 - App type: Standalone 
 - App Version 2.2.15

**Describe the bug**
Strange Event type in matches history with Event - Ladder (Nov 2018). Just play several Standart ranked games.

**Comment by Razviar** [comment]
This is how this event is called internally in the game. There's no issue
