### ISSUE TITLE
Unable to connect + connection-related issues

### ISSUE THREAD

**Issue by hoplaaaa** [Razviar/mtgap#309]
MTGA Pro account: https://mtgarena.pro/u/Mike.124787
MTG Arena ID: Mike#00490
link to page: https://mtgarena.pro/

OS: Windows 10
App type: Standalone
App Version: 2.2.15

Bug:

Hello.

I try to connect as usual, with the credentials stored in my password safe but the website says that the password isn't correct. Thus, I asked for an e-mail to be sent so that I change it (even though it shouldn't be necessary; I haven't changed it since I stored it) but even there, I don't receive the e-mail. Of course, I checked my spam folder, but it isn't there yet either.

Regards.

**Comment by Razviar** [comment]
Hello! I've sent you new temporary password.
