### ISSUE TITLE
How to enable detailed logs

### ISSUE THREAD

**Issue by Kender42** [Razviar/mtgap#31]
When I start the tracker it gives me an alert to enable detailed logs.
There is no setting for this, what do I need to do?

I just uninstalled and reinstalled and I get the same issue. Account not showing either. The above error is on every tab of the tracker and nothing else.

**Comment by Razviar** [comment]
Please follow steps from this manual to enable detailed logs https://mtgarena.pro/mtga-pro-tracker/

It's done in the game itself
