### ISSUE TITLE
Unable to log in to website and reset password

### ISSUE THREAD

**Issue by migerh** [Razviar/mtgap#310]
**Detailed context**
- Link to your MTGA Pro account: User ID based on the desktop app: 217789
- Link to page/pages are in question: Login page of https://mtgarena.pro
- - Screenshots of issue if applicable: n/a

**Your Desktop:**
 - OS: Windows 10
 - Browser: Firefox 99.0.1
 - App type: Standalone, directly from GitHub
 - App Version: 2.2.15, but the app works fine, it's the website I'm having issues with

**Describe the bug**
First of all: Thanks for maintaining this project!

My password is stored in a PW safe, so I haven't forgotten it and there's no typo since I copy&paste it. Still, the website says "Wrong credentials" when I try to log in and requesting a password restore email doesn't get me an email.

I also tried logging in with my MTGAPro user id instead of my email address, but it didn't work.

Looking at the request/response in the Browser dev tools, the request to `do3.php` appears to be successful (200 OK), but the response is just empty.

From what I can tell, it's basically the same issue as #309.

Any help is greatly appreciated.

**To Reproduce**
1. Go to https://mtgarena.pro
2. Click on 'Login' in the menu bar
3. Enter my correct email & my password
4. See 'wrong credentials'

**Comment by Razviar** [comment]
Issue with login is fixed, you should be able to login with old password now. If you already requested reset, I can manually give you your temporary password,

**Comment by migerh** [comment]
I can log in with my existing password again. Thanks for your support!
