### ISSUE TITLE
Exported collection (.csv) has incomplete card names

### ISSUE THREAD

**Issue by Senryoku** [Razviar/mtgap#311]
**Detailed context (ISSUES WILL NOT BE INVESIGATED WITHOUT IT!):**
- Link to your MTGA Pro account: https://mtga.cc/u/Senryoku
- Link to page/pages are in question: https://mtgarena.pro/collection/
- Screenshots of issue if applicable: See attached collection file: [collection.csv](https://github.com/Razviar/mtgap/files/8642932/collection.csv)

**Your Desktop:**
 - OS: Windows 10
 - App type: Standalone
 - App Version 2.2.15

**Describe the bug**
Exported collections from the website in the MTGGoldfish CSV format features some incomplete card names, limiting the interaction with other tools.
In looks like it's filtering some SQL keywords. Examples I've encountered:
 - "Selective Snare" (GRN) turns into "ive Snare"
 - "Join the Maestros" (SNC) becomes " the Maestros"
 - "Case the Joint" (SNC) turns into "Case the t"

I think the problem was introduced recently as I didn't notice it the last time I exported my collection (around the 24th of April I think?), and it definitely already contained "Selective Snare" for example.

**To Reproduce**
1. Go to the collection manager (or use mine as an example: https://mtgarena.pro/collection/?Senryoku)
2. Click on 'Export Collection'
3. Select MTGGoldfish CSV format
4. Inspect card names in the generated file (or lookup the attached [example](https://github.com/Razviar/mtgap/files/8642932/collection.csv))

**Comment by Razviar** [comment]
We performed db upgrade to MySQL 8.0.28, so those issues are quite possible. We will look into it

**Comment by Razviar** [comment]
Fixed.
