### ISSUE TITLE
Matches - Error Occurred!

### ISSUE THREAD

**Issue by max1c** [Razviar/mtgap#315]
**Detailed context (ISSUES WILL NOT BE INVESIGATED WITHOUT IT!):**
- [Link to your MTGA Pro account](https://mtgarena.pro/u/)
- [Link to page/pages are in question](https://mtgarena.pro/matches/?max1c)

**Your Desktop:**
 - OS: Windows 10
 - App type: Standalone
 - App Version 2.2.18

**Describe the bug**
When opening Matches section in profile I get the Error Occurred!
![image](https://user-images.githubusercontent.com/11587156/177022535-bd1b0241-bc8c-497e-a812-cb8450f33bd7.png)

**To Reproduce**
1. https://mtgarena.pro/matches/?max1c

**Comment by Razviar** [comment]
Hello! It's fixed. Please reload page with ctrl+f5
