### ISSUE TITLE
Rewards page displays error message and won't load

### ISSUE THREAD

**Issue by Mikaill** [Razviar/mtgap#319]
**Detailed context:**
- Account: mtga.cc/u/Mikail [Mikail#80317]
- [Rewards page](https://mtgarena.pro/rewards/)
![image](https://user-images.githubusercontent.com/17011135/180145223-980d4abf-0810-469b-9b9f-67b69e4d3506.png)

**Your Desktop:**
 - OS: Windows 10 Pro 21H2 64-bit
 - App type: Standalone
 - App Version: 2.2.20
 - Affects multiple browsers

**Describe the bug**
The Rewards page does not load for my account, it only displays an error pop up "Ouch! Something went wrong and we were unable to render this page properly." asking to reload (does not work) which cannot be closed (clicking the close button does not lead to any visible result).
I have tried all steps suggested in the message and the issue occurs on different browsers (Firefox, Edge with no addons, mobile)

**To Reproduce**
1. Go to https://mtgarena.pro/ and login
2. Click on 'My Arena' then 'Rewards'
3. See error message pop-up

**Comment by Razviar** [comment]
Fixed. Please reload the page using ctrl+f5
