### ISSUE TITLE
Website not updating after sync

### ISSUE THREAD

**Issue by Plex0n** [Razviar/mtgap#32]
Hi. 

Running app version 2,0,15m and have my account setup ok in the app.

I am playing every day, but on the website profile page will not show results of matches and or other activites on several days. I also tried to read old logs, and i get message that all of them is parsed. During this parsing it show in yellow "New user detected!".

So i think there must be something wrong somewhere.

Edit: Do you track historic ranked play and/or historic booster like dominaria?

What do you need to investigate this further?

Plex0n

**Comment by Razviar** [comment]
Try to wipe settings: go to settings tab, click Wipe and sync again.

**Comment by orcutt989** [comment]
Same issue. I just downloaded the app and created an account. I disabled Windows Defender and the WIndows Firewall, reinstalled, resynced, relaunched MTG Arena, relaunched the app, rebooted my computer, wiped data, and tried all of hte above again and none of my data will sync to the site.

**Comment by Razviar** [comment]
v16 with this issue fix is rolled out
