### ISSUE TITLE
Matches History page no longer shows Event and My Deck values

### ISSUE THREAD

**Issue by bobanm** [Razviar/mtgap#320]
**Detailed context (ISSUES WILL NOT BE INVESIGATED WITHOUT IT!):**
- Link to your MTGA Pro account: mtga.cc/u/Dude.271043
- Link to page/pages are in question: https://mtgarena.pro/matches/?Dude.271043

**Your Desktop:**
 - OS: Windows 10
 - App type: Standalone
 - App Version: 2.2.20

**Describe the bug**
Since a few days ago, my _Matches History_ page no longer shows any data in _Event_ and _My Deck_ columns. See attached screenshot. If it might help, it started happening after I cloned one of my decks.

I tried restarting the game, restarting the app, re-syncing the logs, picking log to parse. Nothing helped.

![2022-07-25 22_42_53](https://user-images.githubusercontent.com/2560022/180872734-9d709e6b-9f22-4833-9573-53b96f96f674.png)

**To Reproduce**
1. Go to _Matches History_ page
2. Look at the records from 24 July onwards
3. _Event_ and _My Deck_ columns are no longer populated

**Comment by Razviar** [comment]
Confirmed. We are investigating this issue.

**Comment by Razviar** [comment]
It's fixed

**Comment by bobanm** [comment]
Confirmed. New match records no longer have missing data.

What about the affected records? Would it be possible to somehow re-process the logs and re-construct the missing match details?

**Comment by Razviar** [comment]
You could try on your own risk: wipe settings of the tracker, re-sync it and it will upload all old logs, it might work. But overall we prefer not to try apply any retro-active patches, because practice shows that it leads to more mess and new issues.
