### ISSUE TITLE
Matches History page no longer shows users and opponents ranks/ranking column

### ISSUE THREAD

**Issue by bobanm** [Razviar/mtgap#321]
**Detailed context**
- Link to your MTGA Pro account: mtga.cc/u/Dude.271043
- Link to page/pages are in question: https://mtgarena.pro/matches/?Dude.271043

**Your Desktop:**
- OS: Windows 10
- App type: Standalone
- App Version: 2.2.21

**Describe the bug**

Since today, _My Rank & Rating_ and _Opponent Rank & Rating_ columns on _Matches History_ page don't show any data.

The issue started today after I updated both MTGArena.Pro to 2.2.21 and MTGA game to 0.1.4216.947450.

Tried restarting both the client and the game. Didn't help.

BTW, it is really an amazing feature that the tracker extracts both my and opponent's rating from the log. I haven't seen the other MTGA trackers showing that data in matches history. Love it 👍🏻

![2022-08-04 20_56_37](https://user-images.githubusercontent.com/2560022/182932928-bee47f2a-ae6e-46c2-9bd5-0e6796b94535.png)

**To Reproduce**

1. Go to my account's Matches History page
1. Look at today's matches
1. The values in _My Rank & Rating_ and _Opponent Rank & Rating_ columns are blank

**Comment by Razviar** [comment]
It might be removed from the log. We are investigating

**Comment by Razviar** [comment]
Yeah, rankings are gone from the log. That was really fast lol. We will see if we could extract this data as we do with all other missing data.

**Comment by bobanm** [comment]
Oh yes, it's in the patch notes:

https://mtgarena-support.wizards.com/hc/en-us/articles/8325233855892-Patch-Notes-2022-18-10

> Fixed a bug that wrote player ratings to logs

A bug? I don't understand why Wizards are so protective with ratings data. It's really more fun if you know yours and opponent's ratings.

And I also don't get it why they don't provide no in-game stats, so the community has to build solutions, like you did.

Anyhow, if there is no way to get ratings data anymore, we can close this issue.

**Comment by Razviar** [comment]
We restored tracking of general rankings (Ranking Class + Tier), and it's confirmed that there's no technical way to track mmr anymore. I'm closing the issue.

**Comment by bobanm** [comment]
Someone opened a feature request on MTGA forum, to bring back MMR data to logs.

Please vote and share. I hope the Wizards will listen.

https://feedback.wizards.com/forums/918667-mtg-arena-bugs-product-suggestions/suggestions/45515797-re-add-ratings-and-rank-data-to-logs

**Comment by Razviar** [comment]
Nah, they never listen. I'll vote tho. But they never listen
