### ISSUE TITLE
Card database still not containing all DMU cards?

### ISSUE THREAD

**Issue by rplatzman** [Razviar/mtgap#324]
platzman#29125 here, 
I noticed that for some reason, DMU card database is still week after release not containing all cards. You can see it e.g. when you filter all rare lands - you can see just 4 painlands for DMU, while there was 6 of them released.
(applies to collection manager , but also to general card search  - those cards are nopt there https://mtgarena.pro/collection/)

This of course affects other things like completion statistics - cards are treated as nonexistent...

 Thanks for good work, good luck catching this one.

**Comment by Razviar** [comment]
Hi! Thanks for reporting. Some cards were mistakingly marked as "non collectible" in the DB. Now it's fixed, but it might take some time until cache will update.
