### ISSUE TITLE
Deckbuilder and deck editing issues

### ISSUE THREAD

**Issue by Hifilo** [Razviar/mtgap#325]
**Detailed context (ISSUES WILL NOT BE INVESIGATED WITHOUT IT!):**
- Link to your MTGA Pro account
- Link to page/pages are in question
-[deckbuilder]( https://mtgarena.pro/deckbuilder/9d052cbfffe5796)
- Screenshots of issue if applicable 
Video uploaded

----
Hello, this is a great tool for new players like myself! 

I think something is broken with the deckbuilder because removing cards seems to want to open a new webpage? I tried this with firefox, chrome & brave and had the same issue. I'm almost certain the issue isn't on my end.

Cheers

https://user-images.githubusercontent.com/92943726/192123009-853ca209-8633-4784-a746-a8464139d9c1.mp4

**Comment by Razviar** [comment]
Hello! Thanks for reporting. It's fixed. Try ctrl+f5 to get updated version.

**Comment by Hifilo** [comment]
np @Razviar . I also found a few more bugs while using the site.

**1. deck builder:** not all cards seem to fully remove themselves? this seems to be an issue with saved decks, & not new ones? in the video I'm clicking to remove but nothing happens(I couldn't record the clicks). sometimes adding a card and then removing does the trick, but sometimes it doesn't lol.

https://user-images.githubusercontent.com/92943726/192185432-d0a5a969-855f-4f85-b9bb-e9d611adf8a5.mp4

**2. Autometa:** the containing cards search seems to search infinitely when looking for a card. I haven't been able to find a single card with it.


**3. quick edit deck**: clicking the deckbuilder button seems to be unresponsive from the quick edit deck menu:


https://user-images.githubusercontent.com/92943726/192186351-313fdebf-d50e-46ea-97b7-6a2b24f9f737.mp4

**I also had a question about a site feature:** if I have a deck I've built, and I want to view the card meta like in the [meta of cards](https://mtgarena.pro/cards/#rulings-2;srt-1;direct-0) page, is there a way to do that?


Cheers

**Comment by Razviar** [comment]
Thanks for more reports, we will look into those.

**Comment by Razviar** [comment]
Looks like bugs you've mentioned are fixed. Thanks for detailed video reports. Try ctrl+f5 to get updated version.

**Comment by Razviar** [comment]
Since there's no updates here, I'm closing this issue. Please open new one if you notice something else.
