### ISSUE TITLE
Definition of "Budget".

### ISSUE THREAD

**Issue by orcutt989** [Razviar/mtgap#33]
I see that "Budget" is meaning `Decks with 16% limit for Rares and Mythics quantity`.  I'm seeing decks with lots of mythics returning from the "Budget" selection on the site. Top "Budget" decks having 6 or more mythics and 25 rares! That seems wild to me for a "budget" deck.

![image](https://user-images.githubusercontent.com/5608027/70022254-912edd00-1561-11ea-9921-dc1d08127294.png)

![image](https://user-images.githubusercontent.com/5608027/70022088-e4546000-1560-11ea-8c81-86db65380c6a.png)

**Comment by orcutt989** [comment]
![image](https://user-images.githubusercontent.com/5608027/70022018-b4a55800-1560-11ea-9ee0-02e9fdf4c9ae.png)

**Comment by orcutt989** [comment]
![image](https://user-images.githubusercontent.com/5608027/70022088-e4546000-1560-11ea-8c81-86db65380c6a.png)

**Comment by orcutt989** [comment]
Strange! It appears to have updated itself after some time.

![image](https://user-images.githubusercontent.com/5608027/70022416-2e8a1100-1562-11ea-9037-3fe61d86b0c6.png)

**Comment by realJohnDoe** [comment]
All the filtering, also in My Decks, seems to be a bit buggy. For me a page reload always solved the problem.
