### ISSUE TITLE
Error: Parsing paused: newly detected user account must be synced or skippeed

### ISSUE THREAD

**Issue by dcanamares** [Razviar/mtgap#335]
Some days ago I started with a connection error like that:

![imagen](https://user-images.githubusercontent.com/4290346/202866014-5b249c11-88ba-4ce8-bfb7-845740d5c2dc.png)

I tried to uninstall from Overwolf and then install again, and now the connection problem continues but I have another error

![imagen](https://user-images.githubusercontent.com/4290346/202866078-ba46b2ec-584b-4de3-8303-f2429ddd7b65.png)

I cannot click in any button or do something. How can I solve this problem?

Thank you.

**Comment by Razviar** [comment]
Hello! This issue is related to latest MTGA update. Please use standalone tracker, we have it fixed there  https://github.com/Razviar/mtgap/releases/tag/v2.2.23

**Comment by dcanamares** [comment]
Thank you @Razviar
