### ISSUE TITLE
Problem with matches.

### ISSUE THREAD

**Issue by realbadcoder** [Razviar/mtgap#339]
I get and error that says, "Ouch! Something went wrong and we were unable to render this page properly. First of all, please try reload this page with Ctrl+F5, clear browser cache manually, disable all adblocking software and try to reload the page. If the error still persists, please post an issue [on our GitHub](https://github.com/Razviar/mtgap/issues) to expedite solution for this problem." I have reloaded, cleared my cache, and have no adblocking software but this error has persisted throughout the whole day.

**Comment by Razviar** [comment]
Hello! What is your username?

**Comment by realbadcoder** [comment]
Hi Rzviar! User name is doodoo shoes, snap nick is doodooshoes#20463 if you need that also.

**Comment by realbadcoder** [comment]
Hey Raziar, I have resolved the issue and it was completely on me... (forgot to log back in to snap.pro after clearing cache....) Sorry for any inconvenience! Works fine now!
