### ISSUE TITLE
Cannot Enter Token into Tracker

### ISSUE THREAD

**Issue by stevenflo** [Razviar/mtgap#34]
**Describe the bug**
The tracker is not showing any way to input a token to sync accounts and the website is not showing any token to input into the tracker.

**To Reproduce**
1. Go to https://mtgarena.pro/mtga-pro-tracker/
2. See no token 

1. Go to new tracker
2. Click on the accounts tab
3. See no active accounts with no options to add anything

**Expected behavior**
A way to link my account to the new tacker (2.0.15)

**Screenshots**
![image](https://user-images.githubusercontent.com/22034355/70073971-7b500500-15bf-11ea-83e5-4baa6b9c2e5b.png)
![image](https://user-images.githubusercontent.com/22034355/70073997-860a9a00-15bf-11ea-8231-95bbe80dc9ff.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome and firefox
 - Version: 2.0.15

**Comment by Razviar** [comment]
You don't need token.
1. Go to settings
2. Click Wipe settings
3. Restart tracker and click Sync account on General tab
4. If you don't see it, start mtga
5. If you still don't see it, locate output_log.txt manually in settings

**Comment by stevenflo** [comment]
Thank you for the work around, I got the tracker working now. I really appreciate the work you have put into this app and am impressed with this project.

I will leave this issue open though, since the website pages need to be updated to show that no token is not needed. Specifically, https://mtgarena.pro/tutorial-for-mtgarenapro-tracker/ and https://mtgarena.pro/mtga-pro-tracker/ need to  be updated.
