### ISSUE TITLE
More Daily Challenges

### ISSUE THREAD

**Issue by MikeTheMet** [Razviar/mtgap#340]
I have noticed that the daily challenges have been the same for a long time. It would be great to have more daily challenge options. Here are some ideas:

- Cast X instances and sorceries
- Cast X enchantments
- Cast X artifacts
- Cast X multicolored spells
- Win X matches

The X being any number you feel is obtainable for the players.

These would be great additions to the online game and would give players more challenges to be engaged in.

**Comment by Razviar** [comment]
Hello! We are NOT Marvel Snap developers, we just create 3rd party support tool Marvel Snap Tracker for the game. So your request is legit and I really support it, but it's misplaced. Please post it on official Second Dinner social media like their Discord or write to support@marvelsnap.com
