### ISSUE TITLE
Issue Opening Snap Battles Page

### ISSUE THREAD

**Issue by HotDogDay82** [Razviar/mtgap#346]
Hello! I am having an issue opening the Marvel Snap Battles tab, and I have posted this per the error code's instruction! I have tried to solve the issue using the prompted solutions (reloading, turning off adblocker, etc.), but so far, nothing has worked. I have tried using multiple browsers (Microsoft Edge and Google Chrome), and am still getting the error. My account information is as follows:

![image](https://user-images.githubusercontent.com/125716811/219830173-a5f1082f-a733-4266-a126-a5f2ffadad70.png)

Thanks!

**Comment by Razviar** [comment]
Hi! It's fixed, you now will not see the error screen on this page https://marvelsnap.pro/battles/
But the thing is, you don't have any battles tracked. Battles are direct challenge fights, when you call someone by player tag. When you'll play at least one, you'll see it there.
