### ISSUE TITLE
Wrong GitHub repository linked on website.

### ISSUE THREAD

**Issue by orcutt989** [Razviar/mtgap#35]
`Open an issue on Git` links to the wrong repository. It should link to this one's issues section https://github.com/Razviar/mtgap/issues, but links to the old archived repository that does not have an issues section. https://github.com/Razviar/mtga-pro-tracker/issues  This can be confusing for new users. 

I would also suggest changing the wording to `Open an issue on GitHub`. Git and GitHub are 2 different things.

![image](https://user-images.githubusercontent.com/5608027/70077808-81e67880-15cf-11ea-9b24-1ab6c9a83833.png)

**Comment by Razviar** [comment]
Thanks, fixed.
