### ISSUE TITLE
Awaiting User ID

### ISSUE THREAD

**Issue by Drizzt893** [Razviar/mtgap#355]
Since March of Machines update today, the tracker always says "Awaiting User ID.  Switch into MTGA window and wait about 30s.  I've tried restarting the PC, restarting MTGA, and restarting the tracker all multiple times.  The draft overlay isn't appearing.  The program says I"m up to date.  Screenshot included.
![Screenshot (96)](https://user-images.githubusercontent.com/57761055/232963795-8aeb648e-6dbc-4855-98ae-4846181e7af2.png)

**Comment by Razviar** [comment]
Maybe wotc broke something again. I'll investigate

**Comment by Drizzt893** [comment]
Awesome, thanks!  I'm free to play and rely on the collection tracker to ensure I'm always drafting cards I'm missing from my collection, so I'm kind of stuck with an open bot draft that I can't do without wasting my F2P resources.

**Comment by Drizzt893** [comment]
wait no sorry, I didn't see that it closes it until I posted the comment

**Comment by Razviar** [comment]
Just updated the tracker to 2.2.26, issue should be resolved.

**Comment by Drizzt893** [comment]
Thanks!
