### ISSUE TITLE
Reloading the App

### ISSUE THREAD

**Issue by zbell92** [Razviar/mtgap#36]
**Describe the bug**
I have downloaded and ran the .exe file on two different computers. Every time I close the app down on my computer it will not reopen when I try to click on the file. Is this a common issue? 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by Razviar** [comment]
Exe is installer, not the app itself. You need to run tracker from start menu or desktop
