### ISSUE TITLE
Meta decks page not working 

### ISSUE THREAD

**Issue by FlamenKing** [Razviar/mtgap#365]
![Captura de pantalla (241)](https://github.com/Razviar/mtgap/assets/135840087/6847b57c-6d10-42b3-8737-8436ff41150a)

- https://marvelsnapzone.com/meta/

**Comment by Razviar** [comment]
Unfortunately, I was unable to replicate the issue you're encountering. The page loads correctly for me across different computers and devices. Could you please try accessing it from a different device and let me know if the problem persists?

**Comment by FlamenKing** [comment]
After a couple hours it got fixed, probably was just a connection drop in the site
