### ISSUE TITLE
Data corruption

### ISSUE THREAD

**Issue by mrfuggy** [Razviar/mtgap#37]
I have several identical lines in the rewards and boosters tab.
![Screenshot_2019-12-03 Rewards MTG Arena Pro](https://user-images.githubusercontent.com/31143422/70096916-15e03080-1620-11ea-9178-2164e83105ae.png)

I have wiped events data, but it didn't help. I cannot wipe only rewards or boosters data.

**Comment by Razviar** [comment]
We are fixing it, hold on

**Comment by Razviar** [comment]
Fix is implemented, but old data will remain as is.
