### ISSUE TITLE
Duplicated entries for draft events on Events History page

### ISSUE THREAD

**Issue by bobanm** [Razviar/mtgap#377]
**Detailed context**
- Your MTGA Pro username: Dude.271043
- Link to page/pages are in question: https://mtgarena.pro/events/
- Screenshots of issue if applicable

![2023-09-16 11 19 08](https://github.com/Razviar/mtgap/assets/2560022/a2182433-4690-441a-ba6c-6cc9dd70c352)

![2023-09-16 11 41 35](https://github.com/Razviar/mtgap/assets/2560022/5f837346-457d-4252-b19d-88d31616204d)

**Your Desktop:**
 - OS: Windows 11
 - App type: Standalone
 - App Version: 2.2.28

**Describe the bug**
After finishing a draft event, the Event History page always contains duplicate or multiple entries of the event.

Also, it would be nice if sorting of the event would be done based on the date when the player finished the event, not when they joined the event.

**To Reproduce**
1. Enter a draft event
2. Play until completed
3. Open History Events page
4. There will be multiple entries for the event, and only 1 of them will contain event prize.

**Comment by superpowered** [comment]
@bobanm This should be resolved on the web client. Are you still seeing the issue?

**Comment by bobanm** [comment]
With new version of the web client, the issue is gone. And all information is better presented, especially on the profile page. Great update 👍
