### ISSUE TITLE
Can't access the Settings page

### ISSUE THREAD

**Issue by bobanm** [Razviar/mtgap#381]
**Detailed context:**
- Your MTGA Pro username: Dude.271043
- Link to page/pages are in question: https://mtgarena.pro/settings/
- Screenshots of issue if applicable 

![2023-10-06 19 28 04](https://github.com/Razviar/mtgap/assets/2560022/5772f461-553f-45e1-9b8b-1da30295a420)

**Your Desktop:**
- OS: Windows 11
- App type: Standalone
- App Version: 2.2.29

**Describe the bug**

Since a few days ago, I noticed that some of my settings have changed. On user profile page, the cards I received are shown again using images [default setting], although I have previously changed it to show them as card title. I tried to go back to settings to change it again, but I can't access the settings page anymore. I get the error message:

> Ouch! Something went wrong and we were unable to render this page properly. First of all, please try reload this page with Ctrl+F5, clear browser cache manually, disable all adblocking software and try to reload the page. If the error still persists, please post an issue on our GitHub to expedite solution for this problem.

I tried several things:
- Refreshed the page
- Logged out, and logged back in
- Opened the site in incognito mode and logged in
- Tried different web browsers

Whatever I tried, I always get the same error message.

**To Reproduce**

1. Go to your profile page
2. Click on _Settings_

**Comment by superpowered** [comment]
This should now be resolved

**Comment by bobanm** [comment]
Confirmed. I can access the settings, but also website displays the cards using my existing, non-default settings 👍🏻
