### ISSUE TITLE
No Data on Website

### ISSUE THREAD

**Issue by 0Bane0** [Razviar/mtgap#383]
**Detailed context (ISSUES WILL NOT BE INVESIGATED WITHOUT IT!):**

I linked my account and set the Data location. Ingame I have the deck tracker. But It doesn't show me any data on the website and tracks nothing.
- Link to your MTGA Pro account: mtga.cc/u/Bane.283204
- Link to page/pages are in question: https://mtgarena.pro/decks/?my

**Your Desktop:**
 -  Windows 10
 - App type: Standalone
 - App Version 2.2.29

**Describe the bug**
As mentioned. Screenshots showing the state of my client.

![pro2](https://github.com/Razviar/mtgap/assets/149219525/5e064f4f-d280-4e46-a0a1-4913f2ee2ea6)

![Deck](https://github.com/Razviar/mtgap/assets/149219525/20dfd5b5-c19b-418a-b9dd-f30dc333e8a6)

![pro1](https://github.com/Razviar/mtgap/assets/149219525/7bf655a4-d2c4-4ea8-8be3-d5cdbea6d997)

**Comment by juansbb25** [comment]
Also, what has happened to me is that when I download my collection, it comes out empty

**Comment by 0Bane0** [comment]
can be closed. Mtga acc was linked to an old mtg pro acc.
