### ISSUE TITLE
Overlay isn't working

### ISSUE THREAD

**Issue by Drizzt893** [Razviar/mtgap#39]
The overlay doesn't show up at all.
I'm using Windows 10.
It doesn't start up with windows either, but that's not a big deal.
![Screenshot (12)](https://user-images.githubusercontent.com/57761055/70242119-43bb9700-173e-11ea-89f0-176a5e5b9b57.png)
![Screenshot (13)](https://user-images.githubusercontent.com/57761055/70242133-4cac6880-173e-11ea-8d88-7e9356ee6905.png)
![Screenshot (14)](https://user-images.githubusercontent.com/57761055/70242135-4cac6880-173e-11ea-8210-c1ec9d305061.png)
![Screenshot (15)](https://user-images.githubusercontent.com/57761055/70242136-4cac6880-173e-11ea-958d-2a87c75905bf.png)

**Comment by Razviar** [comment]
Turned out in v2.0.15 overlay is broken. Will be fixed in next releases. For now tracker works only for data uploads.

**Comment by Drizzt893** [comment]
Thanks!
