### ISSUE TITLE
Progress syncs, collection doesnt (Windows 11)

### ISSUE THREAD

**Issue by AluraMTG** [Razviar/mtgap#394]
Can someone help me figure out why it's not syncing? It recognizes my account and syncs progress, but my collection remains 0. 

1. I've got Untapped running too, and thats able to sync my collection just fine.
2. I've checked Windows Defender and allowed mtgatracker.exe there
3. I've also allowed it in my antivirus
4. I've restarted my PC and the tracker and Arena multiple times

**Comment by Revilak** [comment]
Hello, I'm a user like you and version 2.29 works fine for me, also with the new Murders at Karlov Manor set. MTG Arena Pro website needs some hours, even a day, to update the collection with the new acquired cards. If after that time your collection is still 0 please check that some firewall isn't blocking the executable located in C:\Users\(your username)\AppData\Local\\mtgaprotracker\mtgaprotracker.exe. Also the tracker should show a green message that MTG Arena log is parsed till current time.
As a last resort you can try to wipe all settings (Tracker settings tab) and re-sync you account.

**Comment by Revilak** [comment]
I have to make a correction: I didn't know it but the cards just acquired are immediately visible on MTG Arena Pro Collection page if MTG Arena client is closed and restarted.

**Comment by AluraMTG** [comment]
Thanks for following up. After (in no particular order) shooting at random firewall settings, restarting arena, restarting the tracker, restarting my laptop, erasing all settings and some other attempts it finally clicked and now it works :)

**Comment by AluraMTG** [comment]
After (in no particular order) shooting at random firewall settings, restarting arena, restarting the tracker, restarting my laptop, erasing all settings and some other attempts it finally clicked and now it works :)

**Comment by Revilak** [comment]
Glad you solved your issue.
