### ISSUE TITLE
Installer size went from 2mb to 55mb ?

### ISSUE THREAD

**Issue by Mordalak1999** [Razviar/mtgap#4]
I have a couple of question concerning the v2
Why is the installer is now so large ?
Main application exe was 5.8mb, now about 100 ?
Also, why does it include ffmpeg ?

**Comment by Razviar** [comment]
It's because we changed platforms. Now it's electron js. We'll investigate ffmpeg and if it's possible to disabled it. And we'll see if it's possible to reduce size of electron package

**Comment by bdbosman** [comment]
Electron basically comes with a Chromium browser which is like 60MB.
Apart from the increased size it's actually a good improvement going from C# to TypeScript, I fully support this.

**Comment by Razviar** [comment]
With current platform package size is as small as it gets. Nothing can be done here. Closing the issue.
