### ISSUE TITLE
tracker doesn't track a few first games

### ISSUE THREAD

**Issue by necromanek** [Razviar/mtgap#40]
as in the title. It happens repeatedly, today twice with different decks. Once after I started, then when I changed my deck. It also happened before. Sometimes it's one game, sometimes more

v2.0.15

**Comment by necromanek** [comment]
also, one deck was left out completely, or maybe 1 of 10 games tracked, it says that it was not captured

I tried to wipe all settings prior to that it was tracking a while but then when I changed my deck it stopped
![Screenshot](https://user-images.githubusercontent.com/54915405/70274813-240f8780-17ad-11ea-808c-409d01b8c3c6.png)

**Comment by Razviar** [comment]
We are working on next release which should improve stability of tracker

**Comment by Razviar** [comment]
v16 with this issue fix is rolled out
