### ISSUE TITLE
Cards Don't Show On Site

### ISSUE THREAD

**Issue by lemabr01** [Razviar/mtgap#400]
**Detailed context (ISSUES WILL NOT BE INVESIGATED WITHOUT IT!):**
- [Link to your MTGA Pro account](https://mtgarena.pro/u/TrainDubs/)
- [Link to page/pages are in question](https://mtgarena.pro/u/TrainDubs/)

**Your Desktop:**
 - OS: Windows 11
 - App type: Standalone (Website)
 - App Version 2.2.29

**Describe the bug**
On the MTGA Pro website no cards appear in the user profile/history when awarded.

**To Reproduce**
1. Go to User Profile
2. Scroll to any entry that shows cards being tracked
3. See broken card image

![image](https://github.com/Razviar/mtgap/assets/25397001/08e12e99-34d6-417e-b8bf-7d5a1a7adb09)

**Comment by Revilak** [comment]
Hello, 3 days ago I've posted on official Discord https://discord.gg/auHdwKD a similar issue (Collection cards not loading) but the issue hasn't fixed yet.

**Comment by Revilak** [comment]
Razviar, the developer, has answered me on Discord so hopefully the issue will be fixed.

**Comment by Revilak** [comment]
Cards not loading issue should be fixed now.
