### ISSUE TITLE
Completed matches are no longer recognized, probably because of the log file change

### ISSUE THREAD

**Issue by bobanm** [Razviar/mtgap#403]
**Detailed context**
- Link to your MTGA Pro account: https://mtgarena.pro/u/Dude.271043/
- Link to page/pages are in question: https://mtgarena.pro/matches/ and https://mtgarena.pro/u/

**Your Desktop:**
 - OS: Windows 11
 - App type: Standalone
 - App Version: 2.2.30

**Describe the bug**

Since the latest update from 7 May, the completed matches are no longer recognized by the app. I noticed that Arena once again populates the log file with usernames in short format, without numbers. E.g. instead of `username#12345` for most of the entries it only shows `username`. This happened already when update of 26 March introduced the same log file change, but Arena reverted that change in a later update.

I don't know if Wizards want to populate the log file with short or long username format. Rumors are they want to switch to short format, to prevent users from sending friend requests after completing a match, by reading the full username from the log. For MTGA Pro, I think it would be the best and future-proof solution to modify the code to match its users based on a short username format. Untapped.gg still works correctly and I don't think they use long format of Arena usernames.

**To Reproduce**
1. Play a match in the Arena
2. Verify that the log has been parsed
3. Go to https://mtgarena.pro/matches/ or https://mtgarena.pro/u/
4. The match is not registered

Except for missing matches, everything else seems to work OK. Collection is updating and Profile page shows new cards obtained.

**Comment by Revilak** [comment]
Hello,
about this problem Razviar replied on Discord server that the issue might be harder to fix .
