### ISSUE TITLE
Is it just me or is this app completely boned since that last Arena Update?

### ISSUE THREAD

**Issue by SedrynTyros** [Razviar/mtgap#413]
Rather than waste time listing the details, I'm curious if it's working for anyone else. I get various different error messages about it trying to find the User ID but even after playing multiple matches it never does. And wiping the settings seemed to remove anything it knew about my Arena instance. Problem started after the recent update on September 12.

**Comment by Razviar** [comment]
Yes, WOTC broke stuff, just deployed the fix
