### ISSUE TITLE
Can't install or update to newest EXE

### ISSUE THREAD

**Issue by Sidefxmayinclde** [Razviar/mtgap#414]
- mtga.cc/u/SideFx
Then when using the installer, i just get a crash right before it even starts.

**Your Desktop:**
 - OS: [e.g. Windows 10]
 - App type: Standalone
 - App Version [e.g. 2.2.32]

**Describe the bug**
**Program won't update or install after 2.2.32 :** 
- https://i.imgur.com/N6esEPA.png

**To Reproduce**
I went to install the new exe but it crashes right when it launches, so installed the previous version: installs but isnt logging or working overlay wise, seen bottom right about update: went to do it and it errors there as well.

**Comment by Revilak** [comment]
Hello,
I'm not a developer but judging from the screenshot you posted maybe a firewall is blocking the connection of a MTG Arena Pro tracker executable file, probably the file update.exe located in folder C:\Users\{your Windows username}\AppData\Local\mtgaprotracker.  Also please check that  your antivirus isn't blocking or has already quarantined the file SharpMonoInjector.dll which is located, if you have intalled 2.2.32, in folder C:\Users\{your Windows username}\AppData\Local\mtgaprotracker\app-2.2.32\resources\app.webpack\main\native_modules
You have to update to version 2.2.33 because 2.2.32 isn't compatible with the current MTG Arena client.

**Comment by Sidefxmayinclde** [comment]
> Hello, I'm not a developer but judging from the screenshot you posted maybe a firewall is blocking the connection of a MTG Arena Pro tracker executable file, probably the file update.exe located in folder C:\Users{your Windows username}\AppData\Local\mtgaprotracker. Also please check that your antivirus isn't blocking or has already quarantined the file SharpMonoInjector.dll which is located, if you have intalled 2.2.32, in folder C:\Users{your Windows username}\AppData\Local\mtgaprotracker\app-2.2.32\resources\app.webpack\main\native_modules You have to update to version 2.2.33 because 2.2.32 isn't compatible with the current MTG Arena client.

Well you should be a developer because you were correct, It had 2 files in like antivirus hell i had to "approve" then BOOM worked fine <3  Now I need to figure out how to Read my log file, its directed correctly, and the detailed logs is turned on in game (was using untapped just fine)

**Comment by Revilak** [comment]
Always be sure to start MTG Arena Pro tracker first and after you have done it you should start MTG Arena client. When MTG Arena is opened you can check  the tracker's status by switching to its window with alt+tab. If the tracker is working fine you should see a green message that the log is parsed to the current time. If the tracker isn't working you should see a red message instead. If you see a red message the reasons could be the following: if you have Steam or Epic MTG Arena client or if you install the normal WOTC client in a different directory that the default one you have to manually locate the correct folder for MTGA_Data path in tracker's "Settings" tab as the tracker doesn't do it automatically. For Steam version the folder should be under your Steam games folder, for example C:\SteamLibrary\steamapps\common\MTGA\MTGA_Data.

**Comment by Sidefxmayinclde** [comment]
> Always be sure to start MTG Arena Pro tracker first and after you have done it you should start MTG Arena client. When MTG Arena is opened you can check the tracker's status by switching to its window with alt+tab. If the tracker is working fine you should see a green message that the log is parsed to the current time. If the tracker isn't working you should see a red message instead. If you see a red message the reasons could be the following: if you have Steam or Epic MTG Arena client or if you install the normal WOTC client in a different directory that the default one you have to manually locate the correct folder for MTGA_Data path in tracker's "Settings" tab as the tracker doesn't do it automatically. For Steam version the folder should be under your Steam games folder, for example C:\SteamLibrary\steamapps\common\MTGA\MTGA_Data.

Yea i have it aimed at the correct data folder, but it's not reading it, i wonder if there is more perms i need to pass it?

**Comment by Revilak** [comment]
I remember from MTG Arena Pro Discord server that some user had to run the tracker as Admin, maybe MTG Arena client too. I don't run them that way but maybe, if you wish ti could worth a try.

**Comment by Revilak** [comment]
Also please check that the file player.log is located in folder C:\Users\Utente\AppData\LocalLow\Wizards Of The Coast\MTGA\ otherwise you have to change its location in MTG Arena Pro Tracker "Settings" tab.

**Comment by Revilak** [comment]
![MTG Arena Pro tracker settings](https://github.com/user-attachments/assets/fa881bdd-b2e3-4129-93f0-79743a7774a5)

**Comment by Sidefxmayinclde** [comment]
https://i.imgur.com/K2woe4W.png

I have both running in admin mode, even turned off the firewall for now, but still wont read the log file? I dont know what im doing wrong

**Comment by Revilak** [comment]
The tracker always starts with a red message. Do you have also started MTG Arena and switched to MTG Arena Pro tracker window  with alt+ tab ?

**Comment by Sidefxmayinclde** [comment]
https://i.imgur.com/HvGn9BH.png    played about 5 now.

**Comment by Revilak** [comment]
That's weird. Can I see your tracker settings tab ?

**Comment by Sidefxmayinclde** [comment]
https://i.imgur.com/lPPE87k.png

**Comment by Revilak** [comment]
I presume you have also checked that MTGA_Data folder is really in that directory. Also please check if after logging to your personal account in https://mtgarena.pro/ the Matches and Rewards sections are updated or not.

**Comment by Sidefxmayinclde** [comment]
Nothing on the website has logged, it wont even give me a "account" in the accounts tab,

https://i.imgur.com/XGtkHqj.png this is the path for the MTGA_Data. idk i might uninstall the program and see if they are installed on 2 different harddrives if that would matter.

**Comment by Sidefxmayinclde** [comment]
Oh it wont even allow me to pick where to install it. :(

**Comment by Revilak** [comment]
Sorry if I'm asking but do you have created a free account on MTG Arena Pro website ? I'm asking because the tracker's account tab shouldn't be empty (it should show in order: MTG Arena PRO nickname, MTG Arena nickname, MTGA ID and MTGA Pro userID)

**Comment by Sidefxmayinclde** [comment]
https://i.imgur.com/89oIQOd.png

**Comment by Sidefxmayinclde** [comment]
https://i.imgur.com/2NsEiwQ.png

**Comment by Revilak** [comment]
As you could try to "wipe all settings" in MTG Arena Pro settings tab and re-sync your account.

**Comment by Sidefxmayinclde** [comment]
I dont know what you mean by "re-sync" I never seen a spot to even sign in to my account or a way to even link them,

but i have tried the wipe all, did nothing

**Comment by Revilak** [comment]
After you have wiped all settings and restarted the tracker , it should show a button to sync / link you account (I don't remember if in general tab or setting tab)

**Comment by Sidefxmayinclde** [comment]
nope, never seen that option ever.

**Comment by Revilak** [comment]
That's fundamental for the tracker to work. Maybe a complete MTG Arena Pro tracker uninstall from Windows settings - Apps - Installed app and reinstalling 2.2.33 version could solve your issue.

**Comment by Sidefxmayinclde** [comment]
Done it 3 times now but will do it again.

**Comment by Sidefxmayinclde** [comment]
Nope nothing even a pc restart.

**Comment by Sidefxmayinclde** [comment]
https://i.imgur.com/CJFUAet.png

Ok so i went in and manually deleted all the files, I then did a pc restart, i then looked into my firewall and found 2/3 things in "quarentine" i removed those back to where they go, and then task manager close the program *(noticed it likes to stay going) and boom now it works. idk

**Comment by Revilak** [comment]
As you have installed 2.2.23 please check that Sharpmonitor.dll is present in folder C:\Users{your Windows username}\AppData\Local\mtgaprotracker\app-2.2.33\resources\app.webpack\main\native_modules  Anyway if the button to sync / link tracker to MTG Arena Pro websit doesnt' show when you start MTG Arena after starting firs the tracker  I don't know what can we do  as I think we have tried all possible solutions.

**Comment by Sidefxmayinclde** [comment]
> Do you have managed to sync tracker to account ?

I did, and it seems to be working now.

**Comment by Revilak** [comment]
Nice, if you alt-tab from MTG Arena to MTG Arena Pro tracker window, it should show a green message that the log is parsed till the current time.

**Comment by Sidefxmayinclde** [comment]
It is, yes.

**Comment by Sidefxmayinclde** [comment]
I appreciate you helping me out with this, but its 4:40am for me so bed time! hah
