### ISSUE TITLE
Error trying to create a new deck at ptcgpocket.gg

### ISSUE THREAD

**Issue by ayonsky** [Razviar/mtgap#427]
**Detailed context (ISSUES WILL NOT BE INVESIGATED WITHOUT IT!):**
- Link to page/pages are in question: https://ptcgpocket.gg/builder/xfc9l7a283
- Screenshots of issue if applicable 
![image](https://github.com/user-attachments/assets/24654276-9258-466a-b465-d78e1f316d0b)
![Captura de pantalla 2024-11-29 a las 13 12 11](https://github.com/user-attachments/assets/94a381a1-5829-4b14-8c5f-ba77706a1eac)

**Your Desktop:**
 - OS: macOS Sonoma 14.5
 - App type: Web
 - App Version: Web

**Describe the bug**
When I click on create a new deck it shows a render error

**To Reproduce**
1. Go to 'Decks'
2. Click on 'Create Deck'
3. See error

**Comment by Razviar** [comment]
It's fixed
