### ISSUE TITLE
Collection & Stats Not Updating - Even after new build

### ISSUE THREAD

**Issue by imaginarycrane** [Razviar/mtgap#43]
I have been waiting to use this tracker since before the new build because collection and stats information still do not seem to be updating.

I have Windows Defender and Windows firewall both disabled and I also tried wiping settings and no dice. This happens on 3 Windows 10 computers. Ive reastarted the clients, computers, and reinstalled the trackers in all possible orders.

![image](https://user-images.githubusercontent.com/5608027/70852481-b4f1fd00-1e56-11ea-9a16-7d50d6cb5328.png)

![image](https://user-images.githubusercontent.com/5608027/70852491-c9ce9080-1e56-11ea-97c8-8d040405cdc8.png)

![image](https://user-images.githubusercontent.com/5608027/70852497-d652e900-1e56-11ea-8a5c-6815bcf49798.png)

**Comment by Razviar** [comment]
I just checked from server-side, and it seems that your account was properly synced and ready to upload data. Just keep it running and it should get synced.

If it doesn't, try to go to settings and click WIPE SETTINGS button. 

If wipe does not help, then there's not much we can do to help.

**Comment by imaginarycrane** [comment]
Ok thanks for the quick response @Razviar! I will wait and report back if it syncs.

**Comment by imaginarycrane** [comment]
@Razviar I updated the log path sholud I set it back to default?
![image](https://user-images.githubusercontent.com/5608027/70852838-f2f12000-1e5a-11ea-8fc9-f85bc9879235.png)

**Comment by Razviar** [comment]
Yep, you can set it to default.

**Comment by Toybear1986** [comment]
Same issue caused with me after last update of tracker.
![image](https://user-images.githubusercontent.com/50303627/70855400-5327a680-1edb-11ea-8548-9b196a8bf535.png)
Progress not updates, currently i have 12/15 daily wins
![image](https://user-images.githubusercontent.com/50303627/70855418-836f4500-1edb-11ea-9c02-a4f2abb09a8a.png)
"Wipe all settings" not helps me. Also i found some issues with parsing old logs, but i still check it

**Comment by imaginarycrane** [comment]
I let it run for a few hours and it seemed to have finally updated. Not sure on the combo of actions I did to get it to update.

**Comment by Toybear1986** [comment]
@imaginarycrane i guess, that it's bug, but seems it's not to easy for check)

**Comment by Toybear1986** [comment]
@Razviar i found, that stats of "gold/diamonds", "constructed rankings" updates correctly, because It's same on https://mtgarena.pro/progress/#Toybear and in game.
But matches not tracking overall.
In adddition to previous screeshots please see this -  
![image](https://user-images.githubusercontent.com/50303627/70856945-672cd180-1ef6-11ea-8cb9-2f42941f5cb7.png)
part of the data for December 14 has been lost, and there is no data for December 15 at all. So all data about mathes after updating tracker not updated.

**Comment by Razviar** [comment]
Can you please check tracker installation folder for error log? There should be text file in appdata/roaming/mtgaprotracker

**Comment by Toybear1986** [comment]
[2019-12-14_log.log](https://github.com/Razviar/mtgap/files/3964942/2019-12-14_log.log)
[2019-12-15_log.log](https://github.com/Razviar/mtgap/files/3964943/2019-12-15_log.log)
@Razviar logs attached, but seems it conatins only errors of parsing old logs

**Comment by Toybear1986** [comment]
Also confirm issue reported in #45 
https://mtgarena.pro/u/Toybear
![image](https://user-images.githubusercontent.com/50303627/70863667-7b56ea00-1f5b-11ea-8e3e-ff8dd2c6f537.png)
On profile page data about mathes also absent

**Comment by Razviar** [comment]
Resolved.
