### ISSUE TITLE
Read old log doesn't work properly

### ISSUE THREAD

**Issue by Toybear1986** [Razviar/mtgap#44]
**Describe the bug**
When i'll try read old logs, sometimes happen connection error.

**To Reproduce**
1. Go to tracker
2. Click on 'Read Old Log'
3. Select as many logs as you can
_5. Tracker trying again and again parse logs in a loop (seems this part already fixed)_

**Expected behavior**
All logs should parse successfully. But if it's impossible for some logs, tracker should display detailed properly error - reason and name of log file. For example, _log file [UTC_Log - 12-13-2019 22.29.25.log] empty_ or _log file [UTC_Log - 12-13-2019 22.29.25.log] broken_. And maybe suggest some tips for resolve issue

**Screenshots**
![image](https://user-images.githubusercontent.com/50303627/70855547-984cd800-1edd-11ea-88f0-9e318218b74d.png)

**Desktop (please complete the following information):**
 - OS: Win 10 Home 1909 build 18363.535
 - Browser: Chrome Canary x64 build 81.0.3996.0
 - Version of tracker 2.0.16

**Additional context**
For example i've try parsing 95 old logs and issues happens with 100% reproduction, but sometimes it happens with only one log.

[UTC_Log - 12-13-2019 22.29.25.log](https://github.com/Razviar/mtgap/files/3964422/UTC_Log.-.12-13-2019.22.29.25.log)

**Comment by Razviar** [comment]
In 2.0.28 it's fixed.

**Comment by Toybear1986** [comment]
@Razviar к сожалению, трекер так и не научился скипать "пустые" логи, весом 1KB, поэтому он не смог ни разу ничего скипнуть, и пытался их загрузить, но тщетно. После удаления всех таких логов - остальные загрузились без проблем.

**Comment by Razviar** [comment]
Как раз сегодня мы это тестировали и тоже заметили что есть проблема. В следующем релизе исправим

**Comment by Razviar** [comment]
в 2.0.29 много обновлений, связанных со старыми логами, и в том числе эта проблема решена.

**Comment by Toybear1986** [comment]
![image](https://user-images.githubusercontent.com/50303627/71766657-482cc880-2f13-11ea-834b-24a33e4c2016.png)
@Razviar не уверен, что сейчас оно работает лучше, потому что пропусков очень много.

**Comment by Razviar** [comment]
Пропусков может быть много, если раньше эти файлы уже парсились и оно их помнит.

**Comment by Toybear1986** [comment]
> Пропусков может быть много, если раньше эти файлы уже парсились и оно их помнит.

Ок, но есть еще одна странность, количество пропусков как-то странно прыгает туда сюда, то 30, то 40, то снова 30. Замечал такие скачки несколько раз.

**Comment by Toybear1986** [comment]
Надо сказать, что вот тут оно работает более очевидно 
![image](https://user-images.githubusercontent.com/50303627/71766760-73fc7e00-2f14-11ea-95a4-8e44ef9ae3c5.png)

**Comment by Toybear1986** [comment]
@Razviar смотри, нашел вот проблему в прогрессе у себя - 
![image](https://user-images.githubusercontent.com/50303627/71772073-de81de00-2f55-11ea-9edb-45690c705a19.png)
В матчах все вроде более менее корректно, но тут какой-то провал. Новая система чтения логов никак не дает прочитать логи за 17 декабря. Вот логи 
[Logs 17 December.zip](https://github.com/Razviar/mtgap/files/4022544/Logs.17.December.zip)
