### ISSUE TITLE
Matches don't updating

### ISSUE THREAD

**Issue by late-exairu** [Razviar/mtgap#45]
Other stats is updating as they should. But matches not tracking for some reason.

[output_log_1.txt](https://github.com/Razviar/mtgap/files/3964964/output_log_1.txt)
![Untitled-1](https://user-images.githubusercontent.com/5775252/70863427-a6880c00-1f50-11ea-8e53-087578de6606.jpg)

**Comment by Toybear1986** [comment]
@late-exairu already reported here - https://github.com/Razviar/mtgap/issues/43

**Comment by Razviar** [comment]
Can you see matches on https://mtgarena.pro/matches/ page?

**Comment by late-exairu** [comment]
> Can you see matches on https://mtgarena.pro/matches/ page?

Only till 14th of december, as on previous pic. But since then I've played a lot of matches, and draft.

![Untitled-2](https://user-images.githubusercontent.com/5775252/70863915-dd145580-1f55-11ea-864d-7ac282151f18.jpg)

**Comment by stormcat664** [comment]
me too.
Matches hadn't been updated from Dec 14.

**Comment by Razviar** [comment]
@stormcat664 please get the log from AppData\LocalLow\Wizards Of The Coast\MTGA and send it over to me using any cloud service.

**Comment by stormcat664** [comment]
https://www.dropbox.com/s/ry5wq6pvuv4lqq4/Logs.zip?dl=0

**Comment by Razviar** [comment]
thank you, we are looking into it.

**Comment by Razviar** [comment]
Small update: bug is replicated in testing environment, matches from your log are not getting synced properly indeed. Specifically, the fact of match being started is recorded, but event of match completion is not, that is why you can't see them. Working on it...

**Comment by stormcat664** [comment]
Is it a specification change, or issue of my environment?

**Comment by Razviar** [comment]
Most likely it's some uploading or server-side processing of uploads issue. No idea for now, I'll let you know when I'll find something.

**Comment by late-exairu** [comment]
Just an observation, but maybe it will help. For me everything was ok, untill second account was created.

**Comment by Razviar** [comment]
Second account in MTGA or on site? And can you let me know both mtga usernames?

**Comment by late-exairu** [comment]
Second MGTA account was created by my gf. She logged in only few times, before bug appeared. I don't know her username.
My username can be found in log attached in first message.

**Comment by kimitaka** [comment]
I encountered the same problem and found a quick solution for non-English speakers.
If you use MTGA in a non-English language, please try to change the language setting English.

**Comment by stormcat664** [comment]
I tried it.
I played a match in BO1-Play after changed to English.
The result was reflected correctly.
But old logs could not be reflected yet.

**Comment by Razviar** [comment]
It's confirmed that non-english MTGA breaks tracking of matches. We are investigating why...

**Comment by Toybear1986** [comment]
@kimitaka thanks, nice solution, but it's not helpful for upload missed logs. Today already fifth day((
So i'll play on Russian and wait fixes)
@Razviar if you need any help with testing, feel free ask me)

**Comment by late-exairu** [comment]
Same here. Russian translation.

**Comment by Razviar** [comment]
Господа, без паники, уже заливаю версию 2.0.18 ;)

**Comment by Razviar** [comment]
2.0.18 with this issue fix is out. Please update. И старые логи не забудьте закачать...

**Comment by Toybear1986** [comment]
@Razviar пиля, а чо можно было по-русски?)

**Comment by Razviar** [comment]
English practice never hurts, мухахаха

**Comment by kimitaka** [comment]
2.0.18 works correctly with MTGA in Japanese.
But 2.0.18 cannot read some of the old logs.
I supposed this is caused by changing the structure of log files.

But anyway, we can enjoy MTGA in his/her native language.
Thank you so much!

**Comment by Razviar** [comment]
@kimitaka you are very welcome!

**Comment by Toybear1986** [comment]
@kimitaka seems it can't read empty logs with size 1 KB. @Razviar maybe better skip empty log without error? Because now parsing process disrupted, if tracker find empty log. And would be great create some log with detailed information about parsed and not parsed log with reasons (if it's not parsed)

**Comment by kimitaka** [comment]
@Toybear1986 it's very helpful information. I tried to read old logs except for empty ones, and I checked it parsed all of them correctly.

> I supposed this is caused by changing the structure of log files.

The comment I wrote was miss leading... Sorry, please forget it.
