### ISSUE TITLE
Post 2.0.16 A single match still not updated

### ISSUE THREAD

**Issue by Cyp12** [Razviar/mtgap#46]
**Describe the bug**
After 2.0.16 matches are updating much better, however there was still a single game that did not updated for me.

Screen from Game, when I have 5 wins:
![image](https://user-images.githubusercontent.com/58980673/70996680-92b8e300-20d3-11ea-8a45-a12fc9849d58.png)

Screen from web, where only 4 wins are logged:
![image](https://user-images.githubusercontent.com/58980673/70996800-d6135180-20d3-11ea-8243-dd5d08854dd6.png)

**Comment by Toybear1986** [comment]
@Cyp12 please check #45 and #43, seems it's same issue. Please attach logs, requested by developer

**Comment by Cyp12** [comment]
Hi @Toybear1986, I am not sure if it is the same. #45 and #43 does not work at all. I have a single game missed... it looks different to me, but please decide on your own :).

[UTC_Log - 12-16-2019 20.59.29.zip](https://github.com/Razviar/mtgap/files/3975233/UTC_Log.-.12-16-2019.20.59.29.zip)

**Comment by Toybear1986** [comment]
@Cyp12 Sorry, seems, I have inattentively looked at your screenshot. So strange bugs((( 
I just want help developer fix it faster, so thanks for logs.

**Comment by Cyp12** [comment]
@Toybear1986 don't be sorry :) You're doing awesome job with this tool! I really love it! 👍

**Comment by Toybear1986** [comment]
@Cyp12 thanks of course, but I'm a simple user and I also like this wonderful tool) I think guys will fix bugs very quickly

**Comment by Cyp12** [comment]
@Razviar Would it be to much to ask for any kind of explanation why the issue was closed? Did I miss any conclusions being posted somewhere else?

**Comment by Razviar** [comment]
@Cyp12 because tracker may miss single matches from time to time, this is normal. If lost matches are not systematic, it's not an issue
