### ISSUE TITLE
Direct limited creates duplicate card pool in deck builder

### ISSUE THREAD

**Issue by zass30** [Razviar/mtgap#47]
When you create a direct limited tourney, the deck builder shows cards from both players' card pools. 
Instead, it should only show the cards assigned to each player.

For example, go to game "TEP" in the direct limited lobby. You can see that in the card pool viewer, there are 10 rares/mythics 

![image](https://user-images.githubusercontent.com/2244451/71021132-8a9c7b80-20b2-11ea-8dcd-6a8bfec220b3.png)

Then, go to the deck builder. You can see that there are 15 rares alone. The mythics page will show more mythics. 

![image](https://user-images.githubusercontent.com/2244451/71021257-cf281700-20b2-11ea-8cfd-6d624d3fffcc.png)

The cards circled in red should not show up in the deck builder, as they belong to the other player.

**Comment by zass30** [comment]
pinging on this. This should hopefully be a trivial fix.

**Comment by Razviar** [comment]
Still working on fix

**Comment by Razviar** [comment]
Fix implemented.

**Comment by zass30** [comment]
Not fixed. Now, the deck builder is completely empty. See game "TEP3"

![image](https://user-images.githubusercontent.com/2244451/72477382-3f09ea00-37a4-11ea-8cb9-911eb12057a3.png)

**Comment by Razviar** [comment]
This direct limited thing is probably cursed. We just can't make it work. Reopening issue, will investigate...

**Comment by Razviar** [comment]
Another patch applied, please check.

**Comment by zass30** [comment]
Now it won't let me export the deck. When I press the export button I get this:

![image](https://user-images.githubusercontent.com/2244451/72674477-ea78a000-3a2b-11ea-9593-38b0fb2a6cc1.png)

**Comment by Razviar** [comment]
@zass30 looks like it's global deckbuilder issue, not only for limited. We are investigating

**Comment by Razviar** [comment]
@zass30 what card language are you using?

**Comment by zass30** [comment]
I'm not sure what you mean by card language, but the pool is : https://mtgarena.pro/deckbuilder/?Zass&pool-1579404826

Then when you click on export deck, the url changes to: https://mtgarena.pro/deckbuilder/undefined/#Zass

**Comment by Razviar** [comment]
That starting to make sense, we'll try to fix it tomorrow

**Comment by Razviar** [comment]
We are actually in the middle of new deck builder implementation, probably fix will come when new one will be released. It will be tomorrow or in 2-3 days

**Comment by zass30** [comment]
I see the new deck builder implementation, but now the problem is that all cards owned in the collection show in the deck builder, instead of just the cards from the direct sealed pool.

https://mtgarena.pro/deckbuilder/ee8191b66412dbb#pool-#1579404826

**Comment by Razviar** [comment]
Just use different link format:
https://mtgarena.pro/deckbuilder/ee8191b66412dbb#pool-1579404826

**Comment by Razviar** [comment]
Or you can set pool manually, by opening deckbuilder and then clicking by little lock button in the filters row.

**Comment by zass30** [comment]
The point is that the button in the "cards" view does not link to the deckbuilder. The button in the cards view should take the user directly to the deck builder for his pool. 

![image](https://user-images.githubusercontent.com/2244451/73092723-f7651b80-3e91-11ea-8d63-bfbfde360bee.png)

This takes the user to the following url, which shows entire collection:

https://mtgarena.pro/deckbuilder/dc0f5fc734d1d20##pool-1579404826

![image](https://user-images.githubusercontent.com/2244451/73092821-27142380-3e92-11ea-90b2-c937209f04f6.png)

**Comment by Razviar** [comment]
Yeah, I see, it's because of error in link itself, there's double ##. We will fix it

**Comment by Razviar** [comment]
Patch applied, link should be working fine now.

**Comment by zass30** [comment]
This appears to work. There is still one issue, which is that clicking on a card at the bottom of the card list to put it in the deck scrolls you back at the top. It's annoying, because if I'm building a green deck, it keeps scrolling me back at the top to the white cards.

So for example, if I click here:
![image](https://user-images.githubusercontent.com/2244451/73095096-b9b6c180-3e96-11ea-94ed-08749f92e1b6.png)

Then it scrolls me back to here:
![image](https://user-images.githubusercontent.com/2244451/73095133-c9cea100-3e96-11ea-93c0-b5544a666ac9.png)

**Comment by Razviar** [comment]
This is known issue, but we don't have solution for that yet, it might take long time to figure this out. For now you can click on numbers below card to get needed amount and using color filters to reduce cards selection.

**Comment by Razviar** [comment]
This issue seems to be finally resolved, including "jumpy" scroll
