### ISSUE TITLE
Matches not tracking since December 13

### ISSUE THREAD

**Issue by uNight** [Razviar/mtgap#48]
On December 13 had a session and noticed only part of matches where tracked. During today's session no matches were tracked at all. Neither on https://mtgarena.pro/matches/ nor on https://mtgarena.pro/decks/?my. The only thing that is updating is the "Log parsed till XXX" after each match. Logs can be found [here](https://drive.google.com/drive/folders/1fdQDx5ig6hHhwdiVY33uw4xFOv6SoWgd).

Additional info:
- I have two pcs, both have mtga pro tracker
- on one of pcs I may switch to another acc and back

**Comment by Razviar** [comment]
Closing on favor of #45
