### ISSUE TITLE
During draft match overlay displays incorrect cards.

### ISSUE THREAD

**Issue by Toybear1986** [Razviar/mtgap#49]
**Describe the bug**
Incorrect cards displayed in overlay during draft match. Seems it's cards from previous draft match. I can't check it because logs can't be parsed.

**Screenshots**
![image](https://user-images.githubusercontent.com/50303627/71101245-68e0e880-21c7-11ea-8457-40b64dab3569.png)
![image](https://user-images.githubusercontent.com/50303627/71101339-92017900-21c7-11ea-8bd7-e62833be97d2.png)

**Desktop (please complete the following information):**
 - OS: Win 10 Home
 - Browser Google Chrome ver. 81.0.4000.2 (official build), canary (64 bit)
 - Version [2.0.17]

**Comment by Toybear1986** [comment]
![image](https://user-images.githubusercontent.com/50303627/71103932-09d1a280-21cc-11ea-9755-67d1fb47ed46.png)
During traditional match after mulligan overlay displays incorrect deck - instead 4 "Murderous Rider" (as on screenshot) it should be 1 "Murderous Rider" and 3 "Duress" in deck. You can check attached log
[UTC_Log - 12-18-2019 10.30.26.zip](https://github.com/Razviar/mtgap/files/3979444/UTC_Log.-.12-18-2019.10.30.26.zip)

**Comment by Toybear1986** [comment]
![image](https://user-images.githubusercontent.com/50303627/71132472-9b5f0580-2208-11ea-81ed-6344f07dc48f.png)
Again on overlay displays cards from previous draft. Now i playing white|green deck - https://mtgarena.pro/decks/draftovaya-koloda-f47a3d0b-0a61-4852-9705-2f297a6632ce

**Comment by Toybear1986** [comment]
> ![image](https://user-images.githubusercontent.com/50303627/71103932-09d1a280-21cc-11ea-9755-67d1fb47ed46.png)
> During traditional match after sideboard overlay displays incorrect deck - instead 4 "Murderous Rider" (as on screenshot) it should be 1 "Murderous Rider" and 3 "Duress" in deck. You can check attached log
> [UTC_Log - 12-18-2019 10.30.26.zip](https://github.com/Razviar/mtgap/files/3979444/UTC_Log.-.12-18-2019.10.30.26.zip)

Here i metioned sideboard, not mulligan, sorry

**Comment by Razviar** [comment]
If you notice that while drafting overlay shows deck from previous draft, could you please get me the log?

**Comment by Toybear1986** [comment]
![image](https://user-images.githubusercontent.com/50303627/72188093-87bf4d00-340a-11ea-94b5-382c5c952308.png)
[UTC_Log - 01-10-2020 17.52.21.zip](https://github.com/Razviar/mtgap/files/4048118/UTC_Log.-.01-10-2020.17.52.21.zip)
@Razviar снова оверлей показывается карты из какого-то предыдущего драфта. Хотя на сайт загрузилась корректная дека - https://mtgarena.pro/decks/draftovaya-koloda-a270a85d-de14-435f-8d86-578c1b235118
А вот как раз дека с предыдущего драфта, которая отображалась https://mtgarena.pro/decks/draftovaya-koloda-08eb190f-7e18-4267-8718-5408d66a63fe
Думаю по скриншоту все понятно.

**Comment by Razviar** [comment]
@Toybear1986 да, есть такое дело, спасибо за лог, будем изучать...

**Comment by Razviar** [comment]
Finally it's fixed in v.2.0.31
