### ISSUE TITLE
Can't install to my software drive

### ISSUE THREAD

**Issue by Kender42** [Razviar/mtgap#5]
Can't install on my laptop. I have an SSD that is just for the OS and since space is VERY limited I install my software to another drive. How can I install this to a different drive?

My work has me onsite for most of our job (I travel for work) so I have to use my laptop to play games and such and I play MTGA on my off hours and it won't install to the built in software drive (D:\). The system is designed this way and I have no control over it.

**Comment by Razviar** [comment]
Since this is very early beta, there's no installation options. But they will be added in upcoming released on the best week.

**Comment by Kender42** [comment]
Awesome :)

**Comment by Razviar** [comment]
Unfortunately, it's not so awesome. Squirrel installer appears to be unable to install files into specific user-defined directory. So as long as we stick with squirrel, we will have installer working this way. For most users 50-60MB of disk space is irrelevant, so we will not change this for now.
