### ISSUE TITLE
Missed decks in match stats and as result missed data in "Deck Performance" stats.

### ISSUE THREAD

**Issue by Toybear1986** [Razviar/mtgap#50]
**Describe the bug**
In "Personal Deck Performance" i found totally missed stats about 16-17 December, then i've check feed and match stats and found, that information about deck is absent.
![image](https://user-images.githubusercontent.com/50303627/71125011-2fc06c80-21f7-11ea-939a-12d78afc7527.png)
![image](https://user-images.githubusercontent.com/50303627/71124311-a2304d00-21f5-11ea-8d07-f4a66c9b720e.png)
Also you can check attached logs.

**To Reproduce**
1. Go to https://mtgarena.pro/decks/rakdos-traitors-f3147
2. Click on 'Personal Deck Performance'
3. Check 16-17 December
4. Go to https://mtgarena.pro/u/Toybear and check feed for 16-17 December and found that "Deck not captured" for mush more matches

**Expected behavior**
В общем без статы по колодам стата в принципе не имеет особого смысла, т.к. без этой инфы будет сломана стата меты и множество другой полезной инфы. Нужно пофиксить.

**Desktop (please complete the following information):**
- OS: Win 10 Home
- Browser Google Chrome ver. 81.0.4000.2 (official build), canary (64 bit)
- Version [2.0.18]

[Logs 16-17 December.zip](https://github.com/Razviar/mtgap/files/3980654/Logs.16-17.December.zip)

**Comment by Toybear1986** [comment]
@Razviar обрати так же внимание на скрине с фидом, что там и в старых логах много где стоит пометка "Deck not captured"

**Comment by Razviar** [comment]
Issue seems to be resolved in latest versions (starting from 25th)
