### ISSUE TITLE
Issue with website deck descriptions

### ISSUE THREAD

**Issue by Kender42** [Razviar/mtgap#51]
When I try to edit the description of any of my decks, it will not let me enter text. There is no way for me to enter the description of the deck.

**To Reproduce**
1. Go to 'Decks'
2. Click on 'any deck'
3. Scroll down to 'Edit description'
4. There is no way to enter text in the description box

**Expected behavior**
Expect to be able to enter text into box but the text cursor never appears nor does it allow me to enter any text

 - OS: Win 7 
 - Browser: Firefox
 - Version: 71.0

Also just discovered if I change the setting to Show to Public, it will not save anything when pressing the save button.

**Comment by Razviar** [comment]
You should edit your deck's description using deckbuilder. Open deck for edition and input description.

**Comment by Kender42** [comment]
I am in the deck builder

**Comment by Razviar** [comment]
URL looks like this: https://mtgarena.pro/deckbuilder/7616b898e536456/ ?

**Comment by Kender42** [comment]
Yep, that's where I'm at

**Comment by Kender42** [comment]
https://mtgarena.pro/deckbuilder/71655f62fd17e54/

**Comment by Razviar** [comment]
and what happens when you click button EDIT DESCRIPTION below the deck?

**Comment by Razviar** [comment]
I just checked, input is active, text is getting inputted.

**Comment by Kender42** [comment]
It opens up a text box but I can't enter anything, will send screenie on discord

**Comment by Razviar** [comment]
make a screen with console open, there probably some JS errors

**Comment by Kender42** [comment]
How do I do that?

**Comment by Kender42** [comment]
Would it be under Web console or browser console?

**Comment by Razviar** [comment]
ctrl+shift+I
console tab

**Comment by Kender42** [comment]
Posted screenshot on discord

**Comment by Razviar** [comment]
New deckbuilder version resolves this issue.
