### ISSUE TITLE
The last match in an event is not shown on the event page

### ISSUE THREAD

**Issue by KHMaechel** [Razviar/mtgap#52]
The match is recorded and I can see it on the match page. 

![mtgap](https://user-images.githubusercontent.com/59063009/71195314-f38c1b00-228d-11ea-86bc-073d82045700.jpg)

**Comment by Razviar** [comment]
And what is the issue?

**Comment by KHMaechel** [comment]
The events in the screenshot last until 7 wins or 3 losses, the page doesn't show last match.

**Comment by Razviar** [comment]
Oh, I see. We will investigate.

**Comment by Toybear1986** [comment]
@Razviar seems now tracker incorrect wrote watches. Here you can see 100% winrate for 19 December https://mtgarena.pro/decks/rakdos-traitors-f3147 4:0
On https://mtgarena.pro/matches/ i don't see no one losed game in ladder 
![image](https://user-images.githubusercontent.com/50303627/71208070-55ae4580-22b9-11ea-952a-dd9cab5cebda.png), but really i has lost 1 game, please check this log 
[UTC_Log - 12-19-2019 17.44.40.zip](https://github.com/Razviar/mtgap/files/3985575/UTC_Log.-.12-19-2019.17.44.40.zip)

And i already have 4/15 daily wins after refresh in 12:00 Moscow time for today, but tracked only 1 game 2:0. So seems missed one win and one lose.
Tracker version 2.0.19

**Comment by Razviar** [comment]
@Toybear1986 this is some local bug, we will investigate it later, because it's very time consuming. There always been missed matches in tracking, and if it's not 100% repeatable pattern there's not much we can do about it

**Comment by Toybear1986** [comment]
@Toybear1986 I do not know what happened, but now it's was updated and seems correct. I did not do anything

**Comment by Razviar** [comment]
Issue is fixed, all new event will be tracked correctly.
