### ISSUE TITLE
Tracker launching error

### ISSUE THREAD

**Issue by Pierreob** [Razviar/mtgap#53]
**Describe the bug**
When I try to sync my account, I have this message : "Error : Awaiting log id"

**To Reproduce**
I have launched the game, then the tracker. I had to look manually for the output_log.txt file but found it. Then the message appear in General, instead of (I presume) : Sync Account.

**Screenshots**
![image](https://user-images.githubusercontent.com/59069108/71212199-21368b80-22b1-11ea-98b5-02b0c73c5bc5.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 71.0.0.7275

**Comment by Razviar** [comment]
Do you have details logs enabled in mtga?

**Comment by Pierreob** [comment]
Thanks a lot, it works just fine. Great job you're doing by the way, thank you very much !
