### ISSUE TITLE
Tracker recorded wrong game count.

### ISSUE THREAD

**Issue by stormcat664** [Razviar/mtgap#57]
![2019-12-24 181623](https://user-images.githubusercontent.com/52299273/71406039-67596980-267a-11ea-91d6-e0c53128b081.jpg)
Tracker recorded wrong game count(2-4).

Log is here.
https://www.dropbox.com/s/dran4r5f8475zt0/UTC_Log%20-%2012-24-2019%2007.33.47.zip?dl=0

**Comment by Razviar** [comment]
Known bug, closing in favor of #52
Thanks for the log tho
