### ISSUE TITLE
Disable or change global hotkeys

### ISSUE THREAD

**Issue by metrip** [Razviar/mtgap#59]
**Describe the bug**
MTGAP globally captures alt-q and alt-w. I do not want this. I use these key combinations in other apps.

MTG Arena is not running and the overlay is disabled, but the hotkeys are always captured.

**To Reproduce**
1. Press alt-q or alt-w in another app that uses the key combination
2. MTGAP, running in the background, captures the key combination and other apps do not work as expected

**Expected behavior**
- Hotkeys are not captured by surprise
- User is able to enable/disable hotkeys or rebind them

**Comment by Razviar** [comment]
Rebinding is not going to happen unfortunately, but we will add hotkeys disable in settings in the next release

**Comment by Razviar** [comment]
v.2.0.26 implements better hotkeys handling: they are active only when in MTGA and overlay is active. Also, there's a setting to disable hotkeys at all.
