### ISSUE TITLE
Tracker is not recording reward info and only some matches

### ISSUE THREAD

**Issue by Jelly-Flinger** [Razviar/mtgap#6]
Hi

Installed the updated tracker!

Initially no info  was coming through to my profile but now I see some (but not all ) matches. None of the the reward data is showing. 

Not sure where to access error files etc? Let me know if I can provide additional information to help!

**Comment by Razviar** [comment]
Rewards tracking is fixed. To get it tracked, just restart your tracker (Stop Tracker in the app interface and launch again then)
