### ISSUE TITLE
Collection isn't synched after draft

### ISSUE THREAD

**Issue by stijndp** [Razviar/mtgap#60]
Before draft collection on site is current collection in game.
After the draft is done, the collection doesn't get updated.
It's only after playing a match, that the draft gets synched.

This is a problem when you leave the draft without playing a match. Because if you then start a new draft, the collection isn't showing updated.
After you play any match, the collection does get synched. On "MatchGameRoomStateType_MatchCompleted" or "PostMatch.Update" or whatever you're using.

So "Event.CompleteDraft" should be added to the log tracker and trigger a synch of the collection.
Even better would be a synch after each "Draft.MakePick" event but I understand if that would cause too much traffic to handle.

**Comment by Razviar** [comment]
It's how collection renders in game log. As soon as <== PlayerInventory.GetPlayerCardsV3 event fires, we update collection. Until then we can't update it. So this is not an issue.

**Comment by stijndp** [comment]
Can you use "Inventory.Updated" to update the local collection until a full sync does get triggered?

[UnityCrossThreadLogger]==> Event.CompleteDraft {"id":133,"request":"{\r\n  \"jsonrpc\": \"2.0\",\r\n  \"method\": \"Event.CompleteDraft\",\r\n  \"params\": {\r\n    \"eventName\": \"QuickDraft_ELD_20191011\"\r\n  },\r\n  \"id\": \"133\"\r\n}"}
[UnityCrossThreadLogger]<== Event.CompleteDraft {"id":133,"payload":{"Id":"08ade64b-db14-4b97-8fbb-298559d82d22","InternalEventName":"QuickDraft_ELD_20191011","PlayerId":null,"ModuleInstanceData":{"HasPaidEntry":"Gold","DraftInfo":{"DraftId":"ISV3LTQV3JA7DEIKNR443OSPM4:QuickDraft_ELD_20191011:Draft"},"DraftComplete":true,"HasGranted":true},"CurrentEventState":"PreMatch","CurrentModule":"DeckSelect","CardPool":[70191,70390,70349,70170,70348,70282,70327,70188,70304,70188,70351,70393,70300,70366,70344,70331,70370,70340,70396,70176,70171,70331,70340,70151,70230,70351,70183,70178,70167,70348,70359,70364,70333,70305,70162,70392,70181,70305,70314,70327,70238,70394],"CourseDeck":null,"PreviousOpponents":[]}}
[UnityCrossThreadLogger]==> Inventory.Updated {"id":-1,"payload":{"context":"Event.GrantCardPool","updates":[{"delta":{"gemsDelta":40,"goldDelta":0,"boosterDelta":[],"cardsAdded":[70191,70390,70349,70170,70348,70282,70327,70188,70304,70188,70351,70393,70300,70366,70344,70331,70370,70340,70396,70171,70331,70340,70151,70351,70183,70178,70167,70348,70359,70364,70333,70305,70162,70392,70305,70314,70238,70394],"decksAdded":[],"starterDecksAdded":[],"vanityItemsAdded":[],"vanityItemsRemoved":[],"draftTokensDelta":0,"sealedTokensDelta":0,"vaultProgressDelta":0.6,"wcCommonDelta":0,"wcUncommonDelta":0,"wcRareDelta":0,"wcMythicDelta":0,"artSkinsAdded":[],"artSkinsRemoved":[],"voucherItemsDelta":[]},"aetherizedCards":[{"grpId":70191,"goldAwarded":0,"gemsAwarded":0,"set":""},{"grpId":70390,"goldAwarded":0,"gemsAwarded":0,"set":""},{"grpId":70349,"goldAwarded":0,"gemsAwarded":0,"set":""},{"grpId":70170,"goldAwarded":0,"gemsAwarded":0,"set":""},{"grpId":70348,"goldAwarded":0,"gemsAwarded":0,"set":""},{"grpId":70282,"goldAwarded":0,"gemsAwarded":0,"set":""},{"grpId":70327,"goldAwarded":0,"gemsAwarded":0,"set":""},{"grpId":70188,"goldAwarded":0,"gemsAwarded":0,"set":""},{"grpId":70304,"goldAwarded":0,"gemsAwarded":0,"set":""},{"grpId":70188,"goldAwarded":0,"gemsAwarded":0,"set":""},{"grpId":70351,"goldAwarded":0,"gemsAwarded":0,"set":""},{"grpId":70393,"goldAwarded":0,"gemsAwarded":0,"set":""},{"grpId":70300,"goldAwarded":0,"gemsAwarded":0,"set":""},{"grpId":70366,"goldAwarded":0,"gemsAwarded":0,"set":""},{"grpId":70344,"goldAwarded":0,"gemsAwarded":40,"set":"ELD"},{"grpId":70344,"goldAwarded":0,"gemsAwarded":0,"set":""},{"grpId":70331,"goldAwarded":0,"gemsAwarded":0,"set":""},{"grpId":70370,"goldAwarded":0,"gemsAwarded":0,"set":""},{"grpId":70340,"goldAwarded":0,"gemsAwarded":0,"set":""},{"grpId":70396,"goldAwarded":0,"gemsAwarded":0,"set":""},{"grpId":70176,"goldAwarded":0,"gemsAwarded":0,"set":""},{"grpId":70171,"goldAwarded":0,"gemsAwarded":0,"set":""},{"grpId":70331,"goldAwarded":0,"gemsAwarded":0,"set":""},{"grpId":70340,"goldAwarded":0,"gemsAwarded":0,"set":""},{"grpId":70151,"goldAwarded":0,"gemsAwarded":0,"set":""},{"grpId":70230,"goldAwarded":0,"gemsAwarded":0,"set":""},{"grpId":70351,"goldAwarded":0,"gemsAwarded":0,"set":""},{"grpId":70183,"goldAwarded":0,"gemsAwarded":0,"set":""},{"grpId":70178,"goldAwarded":0,"gemsAwarded":0,"set":""},{"grpId":70167,"goldAwarded":0,"gemsAwarded":0,"set":""},{"grpId":70348,"goldAwarded":0,"gemsAwarded":0,"set":""},{"grpId":70359,"goldAwarded":0,"gemsAwarded":0,"set":""},{"grpId":70364,"goldAwarded":0,"gemsAwarded":0,"set":""},{"grpId":70333,"goldAwarded":0,"gemsAwarded":0,"set":""},{"grpId":70305,"goldAwarded":0,"gemsAwarded":0,"set":""},{"grpId":70162,"goldAwarded":0,"gemsAwarded":0,"set":""},{"grpId":70392,"goldAwarded":0,"gemsAwarded":0,"set":""},{"grpId":70181,"goldAwarded":0,"gemsAwarded":0,"set":""},{"grpId":70305,"goldAwarded":0,"gemsAwarded":0,"set":""},{"grpId":70314,"goldAwarded":0,"gemsAwarded":0,"set":""},{"grpId":70327,"goldAwarded":0,"gemsAwarded":0,"set":""},{"grpId":70238,"goldAwarded":0,"gemsAwarded":0,"set":""},{"grpId":70394,"goldAwarded":0,"gemsAwarded":0,"set":""}],"xpGained":0,"context":{"source":"ModifyPlayerInventory","sourceId":"08ade64b-db14-4b97-8fbb-298559d82d22GrantCardPool"}}]}}

**Comment by Razviar** [comment]
We can, but we won't,  since it may potentially lead to inaccurate numbers
