### ISSUE TITLE
Wildcard not matches in game count

### ISSUE THREAD

**Issue by rijkaard90** [Razviar/mtgap#61]
Hi,
The count of rare wildcards in game doesn't match the count in the site "https://mtgarena.pro/collection/".

i have the 2.0.26 version of the tool.
i tried to wipe all data, but nothing changed.

**Comment by Razviar** [comment]
It will update when you'll earn another wildcard

**Comment by rijkaard90** [comment]
ok, thanks! now it's all ok

**Comment by fenhl** [comment]
I have this issue and earning another wildcard did not fix it. Please reopen.

**Comment by Razviar** [comment]
@fenhl it will get synced, just give it some time.

**Comment by fenhl** [comment]
Looks like I just misunderstood. The issue fixes itself once you earn a wildcard **of the appropriate rarity**.
