### ISSUE TITLE
The booster adviser is not working properly (for me at least)

### ISSUE THREAD

**Issue by mcmaximiano** [Razviar/mtgap#62]
The booster adviser on my account is not working properly, it says i am missing cards that are not present in any of the decks on my craft list, or any of my decks at all.

 It is saying i'm missing cards from decks i deleted months ago. Here is an imgur album with 2 screenshots to show my point: https://imgur.com/a/7OaQElp

You can see that in the booster adviser tab it shows cards like kaya's wrath, from when Esper control was a thing, and in my craft list i don't even have a BW deck...

This has been an issue for months now, i hoped the 2.0 version would fix it but it didn't. I have detailed logs on and everything setup correctly, it just stopped working somewhere in the past.

**Comment by Razviar** [comment]
Can you please give me a link to your account? Or let me know your nick

**Comment by mcmaximiano** [comment]
Sure.  thanks for the quick reply! https://mtgarena.pro/u/110110010011

**Comment by Razviar** [comment]
Thanks, we are looking into it

**Comment by mcmaximiano** [comment]
Thank YOU! I really love your tracker even though I don't play mtga that much, so I'd really like it to work :)

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Razviar** [comment]
I just manually wiped your craft list. Try to fill it again

**Comment by mcmaximiano** [comment]
Yep that fixed it! Thank you so much!
