### ISSUE TITLE
Digit: Draft Eval

### ISSUE THREAD

**Issue by Ginso** [Razviar/mtgap#63]
Hello,
can someone explain to me the meaning of the digits "Draft Eval by Picks(or W/L)" in the overlay settings?

**Comment by Razviar** [comment]
It means that card being evaluated by number of picks or it's win/loss.
"By picks" shows average probability of this card to get picked in draft when it shows up in pack among MTGA Tracker users who did successful draft (meaning 3 victories or more).
"By W/L" shows average win/loss in draft matches for decks with this card included.
