### ISSUE TITLE
tracker not uploading card and deck collections.

### ISSUE THREAD

**Issue by Rhenin** [Razviar/mtgap#65]
**Describe the bug**
Tracker is not uploading info about decks and collections but on the website i see uploaded info about gold and vault progress. I've checked logs in AppData/Roaming/MTGAproTracker and there is error with path. I have game installed in other place than program files

Log file:
https://pastebin.com/0qkpUVAG

**Screenshots**

![image](https://user-images.githubusercontent.com/36161527/71542404-6704eb00-2966-11ea-8f7c-d18af10990d1.png)
![image](https://user-images.githubusercontent.com/36161527/71542418-961b5c80-2966-11ea-9008-b2a2d6ddf217.png)
![image](https://user-images.githubusercontent.com/36161527/71542425-a4697880-2966-11ea-98d9-c7b73a8f50be.png)

**Desktop (please complete the following information):**
 - OS: win 10

**Comment by Razviar** [comment]
How long was you using tracker?

**Comment by Razviar** [comment]
Have you tried to wipe settings and re-sync again?

**Comment by Rhenin** [comment]
I've tried reinstal, re-sync and has changed path to logs, it did nothing at first but after 2 hours of playing arena it starded working.

**Comment by Razviar** [comment]
Then it's working as intended. Collection updates are not happening that often in log these days :)

**Comment by Razviar** [comment]
Also, if you changed path to logs, please make sure it's correct (appdata folder, output_log.txt file) because if you located log in program files folder, it won't update as it should
