### ISSUE TITLE
Tracker hogging CPU

### ISSUE THREAD

**Issue by PaeP3nguin** [Razviar/mtgap#66]
**Describe the bug**
After launching the tracker, it starts launching a bunch of "fastlist.exe" processes and using up all of the CPU.

**To Reproduce**
1. Open MTG Arena
3. Open the tracker

**Expected behavior**
Tracker works normally without hogging CPU :)

**Screenshots**
Screenshot from task manager:
https://i.imgur.com/DHstxo2.png

**Desktop (please complete the following information):**
 - OS: Windows 10 (10.0.18363 Build 18363)
 - Tracker version: tracker v2.0.28

**Additional context**
This is off a newly installed version of the v2 tracker. FWIW, I do still have an old v1 version of the tracker installed as well, but not running during any point of this.

**Comment by Razviar** [comment]
This is rare floating but which we aware of, but can't reproduce and, therefore, fix. Users report that enabling of manual updates helps. You can safely remove old tracker, it will not be used anymore

**Comment by PaeP3nguin** [comment]
Seems that turning off auto-update and restarting my computer helped. Thanks!
