### ISSUE TITLE
Suggestion: Sort collection by date

### ISSUE THREAD

**Issue by Lila-Blume** [Razviar/mtgap#67]
It's already possible to filter your collection by specific dates (as in "the date when the tracker first discovered a card in your collection", as I understand it; because Arena itself doesn't save the date you received a card).
Could we get the ability to sort our collection by this date? Or is it not possible because of how cards and their copies are displayed?

**Comment by Razviar** [comment]
It's possible, we are working on it

**Comment by Razviar** [comment]
Implemented.
