### ISSUE TITLE
Tracker puts a shortcut on the desktop on every boot

### ISSUE THREAD

**Issue by Charlielx** [Razviar/mtgap#68]
**Describe the bug**
Every time I boot up I have a new tracker shortcut on my desktop I have to delete since I dislike having any icons on the desktop. Quite annoying as there's no way I can tell to disable this, and I've never seen a program do it before so I'm assuming it's not something you're doing intentionally

**To Reproduce**
1. Boot PC
2. View desktop

**Desktop:**
 - OS: Windows 10 Pro 1909 (64 bit)
 - Version: 2.0.29

**Comment by Razviar** [comment]
Working on it

**Comment by Razviar** [comment]
New versions starting from v.2.0.30 are not creating desktop shortcut.
