### ISSUE TITLE
[Suggestion] Collection Format Filter (Standard/Historic)

### ISSUE THREAD

**Issue by shirbr510** [Razviar/mtgap#69]
I'm trying to get my progress on 100% (completionist 🤷‍♂ )

the issue is: my Uncommon "All Craftable" Progress bar states I have 1565/1572 yet I cannot determine which cards am I missing.

I would like to be able to filter based on format (standard/ historic) in collection filters so I can figure out which cards do I miss (this will allow me to chain filters with the "no 4 set" filter in order to get the info I need)

**Comment by F43nd1r** [comment]
The "All Craftable" Progress bar is just wrong. I can see ingame that I have at least one copy of every craftable uncommon, and yet the progress bar states 90% (733 of 815 unique).
I've also counted all uncommons in my collection and arrived at 733 as well. I don't know which additional cards are counted here. Maybe Momir cards? Those should not be considered craftable.

**Comment by Razviar** [comment]
Numerous updates implemented in this regard
