### ISSUE TITLE
Virus alerts

### ISSUE THREAD

**Issue by enilson4** [Razviar/mtgap#70]
I am receiving numerous virus alerts trying to install the v.2 version of MTGA Tracker.  I'm seriously concerned about continuing with the install.  Is this expected?  Please advise.  Thanks.

First I was warned on the install - but I ignored it.  Now I'm getting another one for Update.exe and the threat name is "IDP.Generic"

**Comment by Razviar** [comment]
This is false positive. As you can see, 'Generic' means basically 'we don't know what virus this is, but we will consider it virus anyway'. As long as trust builds up, these alerts will call down.

App is open source, and if there were any malicious code, community would have found out already. So you can safely ignore antivirus alerts.

**Comment by enilson4** [comment]
Thank you - as you can imagine - it was surprising and concerning.  I've created an exception on the virus software for it.  Thank you for confirming.
