### ISSUE TITLE
The application shows Error - Enable Detailed Logs and Restart MTG

### ISSUE THREAD

**Issue by DiamondDTR** [Razviar/mtgap#71]
The application shows Error - Enable Detailed Logs and Restart MTG

**Expected behavior**
sync with local logs

**Screenshots**
![image](https://user-images.githubusercontent.com/59883641/72358086-ed018f80-36e3-11ea-9dbd-b1850d07a4e0.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Edge

**Comment by Razviar** [comment]
Well, have you enabled detailed logs in MTGA and restarted MTGA as app suggested?

**Comment by DiamondDTR** [comment]
Yes, also uninstalled/ reinstalled 3 times. Rebooted my machine on every occasion 

David McCrone

**Comment by Razviar** [comment]
Is your mtga log file has standard location? AppData\LocalLow\Wizards Of The Coast\MTGA

**Comment by willcotter** [comment]
Same issue here.

**Comment by DiamondDTR** [comment]
I had to uninstall 
Reboot
Reinstall 
Do a full reset of the app
Reboot 
Then it worked 

David McCrone
