### ISSUE TITLE
Awaiting Account Sync...

### ISSUE THREAD

**Issue by Coachwooten** [Razviar/mtgap#72]
For some reason my mtg arena profile is showing as null, and the mtgarena.pro software is showing a 'Awaiting Account Sync...' message.

Any ideas?

**Comment by Razviar** [comment]
Do you have nickname and other fields filled out here https://mtgarena.pro/edit-profile/ ?

**Comment by tristanfey** [comment]
I have the same issue. Have tried my nick with and without the #12345 as part of it and I still have the "Awaiting account sync..." message. I've closed and reopened both the tracker and MTGA as well as uninstalled/reinstalled the tracker with no success. This despite the website saying it completed successfully and also receiving a Windows notification about parsing the logs.

 
![2020-01-17](https://user-images.githubusercontent.com/60023763/72657380-702b1b80-3958-11ea-93e8-a1bcd203bf32.png)

![2020-01-17 (1)](https://user-images.githubusercontent.com/60023763/72657427-fba4ac80-3958-11ea-897f-9f5b744ffce5.png)

**Comment by Razviar** [comment]
@tristanfey I can see that MTGA account tristanfey#35945 is succesfully linked to MTGA.pro account tristanfey#35945. Are you sure you have only one account used? If you have several, you need to skip them during sync request or sync with different MTGAPro accounts.

**Comment by aolmenki** [comment]
I have having the same issues

**Comment by tristanfey** [comment]
> @tristanfey I can see that MTGA account tristanfey#35945 is succesfully linked to MTGA.pro account tristanfey#35945. Are you sure you have only one account used? If you have several, you need to skip them during sync request or sync with different MTGAPro accounts.
> 
> Also, I can see your matches and all other data tracked correctly in the system.

I only have the one account and it is not appearing in the tracker.
![Screenshot 2020-01-19 at 1 53 53 AM](https://user-images.githubusercontent.com/60023763/72679130-09ddf000-3a61-11ea-9cbc-4468cb5db6e1.png)

I play almost daily with rare exception and yet I have no updated information loaded into the account past Nov. 28th. No feed updates, no match data and no progress.

![Screenshot 2020-01-19 at 1 57 03 AM](https://user-images.githubusercontent.com/60023763/72679156-5295a900-3a61-11ea-835d-271a5fb6a29b.png)
![Screenshot 2020-01-19 at 2 06 01 AM](https://user-images.githubusercontent.com/60023763/72679158-59242080-3a61-11ea-8a52-959fbb125f82.png)

**Comment by Razviar** [comment]
@aolmenki please set your nick here: https://mtgarena.pro/edit-profile/ make settings wipe and try to sync again.

**Comment by Razviar** [comment]
@tristanfey try to wipe settings in tracker and sync again.

**Comment by aolmenki** [comment]
![chrome_2020-01-19_06-09-00](https://user-images.githubusercontent.com/12127142/72679926-479f4080-3a82-11ea-8a32-aec08db9d379.png)
I see, this is the confusing field than because it says "MTGAPro Site" which has me assuming it is custom for this website, and not my ID on MTGA

**Comment by Razviar** [comment]
@aolmenki it is for site, you can write there anything, but it needs to be filled. In your case it was empty

**Comment by tristanfey** [comment]
> 
> 
> @tristanfey try to wipe settings in tracker and sync again.

That appears to have done the trick. Thank you for taking the time.
