### ISSUE TITLE
My deck is off-screen

### ISSUE THREAD

**Issue by amirebrahimi** [Razviar/mtgap#73]
**Describe the bug**
Somehow the widget to move my deck is now off-screen. I was messing around with scaling up and down the UI because I couldn't see anything initially. Then finally when my deck showed up the button had already moved off the screen.

**To Reproduce**
Not sure how to repro

**Expected behavior**
The deck and opponent deck move icons should always stay on screen.

**Desktop (please complete the following information):**
 - OS: Windows

Do I have to wipe all my settings to get it back?

**Comment by Razviar** [comment]
Go to settings and click wipe button
