### ISSUE TITLE
Set progress appears as 100% when missing one card

### ISSUE THREAD

**Issue by GipsonLens** [Razviar/mtgap#74]
Very minor but at the progress page, I was looking at Guilds of Ravnica completion and for rare cards, it displays "100% / 100%" but when hovering over it, it states that "You have 211 of 212 cards / 53 of 53 unique cards" so it shouldn't be at 100% yet.

![image](https://user-images.githubusercontent.com/59993563/72592101-ab750e00-38b6-11ea-961d-a8a9f5887ae9.png)

**Comment by Razviar** [comment]
Hi! 
211/212 = 0,99528301886792452830188679245283
By math rules of rounding numbers 0,99528301886792452830188679245283 = 100. As long as we don't show decimals, we round to 100.
