### ISSUE TITLE
Tracker not tracking wildcards properly

### ISSUE THREAD

**Issue by TheDarkPreacher** [Razviar/mtgap#75]
**Describe the bug**
I go to the website, browse decks, and click the craftable button to see which decks can be crafted using the wildcards I have on hand after parsing my logs with the tracker app. Incorrect amounts for my owned wildcards show up. Example: I click the button, it shows me decks that would require 1 rare or 1 mythic rare, when I used those wildcards a full day ago, and do not have them.

**To Reproduce**
1. open tracker on desktop, click "Sync old logs", or "Pick Log to parse"
2. wait until logs are parsed
3. go to website, click "Browse decks"
4. click the "craftable" filter button
5. See decks filtered that need wildcards I don't have.

**Expected behavior**
It should show decks I can build using my actual wildcards, not wildcards I no longer have.

**Screenshots**
![image](https://user-images.githubusercontent.com/15058826/72888830-fbe3d580-3cd3-11ea-97bc-175b5f74db1f.png)
![image](https://user-images.githubusercontent.com/15058826/72888886-1918a400-3cd4-11ea-854b-92354204bd0b.png)
![image](https://user-images.githubusercontent.com/15058826/72888917-2897ed00-3cd4-11ea-9172-87e87759d1fa.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser: Chrome
 - Version: Chrome version: Version 79.0.3945.117 (Official Build) (64-bit), Tracker Version: V. 2.0.31, Windows 10 Pro version: V. 1909

**Additional context**
When trying to locate default log path in settings on tracker app, it is looking for a "output_* (*.txt)" file, but the prefix for the logs is UTC on my system. 
![image](https://user-images.githubusercontent.com/15058826/72889435-4d409480-3cd5-11ea-83f2-5fa3684b4a94.png)

**Comment by Razviar** [comment]
This is how information on wild cards is getting updated in log, nothing we can do about it. WS will get synced as soon as you will get new WC of respective rarity.

As for logs, we track file in AppData\LocalLow\Wizards Of The Coast\MTGA and if you are getting any data parsed, than you should touch log path.
