### ISSUE TITLE
Access is denied

### ISSUE THREAD

**Issue by pjmattingly** [Razviar/mtgap#76]
**Describe the bug**
The application seems to be running, but is unresponsive. Attempting to manually terminate the application results in an error with "Access is Denied".

**To Reproduce**
Unsure, this is the first time it's happened.

**Expected behavior**
I expected to be able to use and close the application normally.

**Screenshots**
NA

**Desktop (please complete the following information):**
Windows 10

**Additional context**
I also attempted to uninstall and reinstall the program. The installation failed with a similar error. See attached for the installation log.
[SquirrelSetup.log](https://github.com/Razviar/mtgap/files/4100467/SquirrelSetup.log)

**Comment by Razviar** [comment]
Try to reboot PC and re-attempt installation

**Comment by pjmattingly** [comment]
Yes, that worked.

**Comment by pjmattingly** [comment]
Hi it happened again.

It looks there's more than one process when it happens:

![mtgpro 1](https://user-images.githubusercontent.com/6288999/73127760-95381380-3f82-11ea-9635-8f47c399cc16.png)

Then when I try to end the processes the one that gives me an Access Denied error does not terminate. Then when I try to end process on the one remaining process it gives me the error:

![mtgpro 2](https://user-images.githubusercontent.com/6288999/73127765-b0a31e80-3f82-11ea-99b9-778b50eae39a.png)

Restarting like last time isn't feasible, I'm working on something at the moment.
