### ISSUE TITLE
Bad dates cause poor progress graph display

### ISSUE THREAD

**Issue by iluvatar777** [Razviar/mtgap#77]
**Describe the bug**
Some data gets recorded with a default date back in 1970, causing progress graphs to display poorly

**To Reproduce**
go to: https://mtgarena.pro/progress/#matt%20giesmann
view graph, and any other progress gaphs.  

**Expected behavior**
There should be a client feature to automatically clean data, or graphs should not show 1970 dates by default.

**Comment by Razviar** [comment]
Working on reliable fix, should be ready today

**Comment by Razviar** [comment]
Patch applied.

**Comment by iluvatar777** [comment]
Thank you for the quick fix!
