### ISSUE TITLE
Re-bind hotkeys

### ISSUE THREAD

**Issue by Elogain** [Razviar/mtgap#78]
Hello!

Great app and website. Unfortunately alt+~ is not possible to type properly on a swedish keyboard, is it is a delayed key, ie, press altgr, press the button to generate ~ and then another key for the ~ to actually show up. Even pressing alt during a ~~~~~~~~~~~ (holding altgr and repeating the "tilde" button will emit keystrokes) sequence will halt the sequence. Ie; I have to switch between keyboard locale to activate overlay.

**Comment by Elogain** [comment]
Also, to press ~ on an US keyboard setting requires you to press shift. You also require alt to be pressed. In windows that is by default the switch locale command (shift + alt, if you have several locales set up it will rotate between them). Basically, I have no clue how to get the overlay up over my mtgArena window.

**Comment by Razviar** [comment]
Thanks for reporting, we will look into possibility of hotkeys rebinding

**Comment by momala454** [comment]
even when i change layout to qwerty (originaly azerty) doing every possible manipulation to show up overlay doesn't work

**Comment by Razviar** [comment]
Updated v2.0.36 gives opportunity to re-bind hotkeys. You can click on key indicated on hotkeys map to assign new key. Currently only ALT + ... combinations are supported.
