### ISSUE TITLE
old log files not being uploaded after parsing

### ISSUE THREAD

**Issue by Spongman** [Razviar/mtgap#79]
I have a few old log files from before i installed the latest version. i used 'pick log to parse' and selected the files, and it says it was successful in parsing them, but those matches don't appear on the site.

the log filenames are:
````
01/23/2020  10:06 PM            19,513 UTC_Log - 01-24-2020 06.05.03.log
01/23/2020  10:28 PM            93,356 UTC_Log - 01-24-2020 06.06.52.log
01/24/2020  12:04 AM           451,761 UTC_Log - 01-24-2020 06.29.04.log
````

**Desktop (please complete the following information):**
 - OS: windows
 - Browser chrome
 - Version 2.0.32

**Comment by MAC-GH** [comment]
I've observed this issue with the last 2.0.37 and 2.0.38 versions too.

**Comment by Razviar** [comment]
Closing this in favor of #86 since it's the same nature issue
