### ISSUE TITLE
"Game is not running"

### ISSUE THREAD

**Issue by Yooops** [Razviar/mtgap#8]
Hello there !

Here is my problem : the game is not detected. 
![image](https://user-images.githubusercontent.com/58131537/69491640-05012380-0e98-11ea-8268-dfd9315e28f0.png)

I tried to re-launch Tracker after the launch of MTGA, same issue.
I tried to manually locate the log, same issue.
The Re-sync Log button doesn't seem to do anything.
My MTGApro account is ok in the Accounts tab.

(Win7 64, last MTGA update)
Thanks,

**Comment by Razviar** [comment]
Can you please make a screenshot of tasks manager with mtga running?

**Comment by Yooops** [comment]
![image](https://user-images.githubusercontent.com/58131537/69492792-14d43400-0ea7-11ea-8915-773054b5c68c.png)
Here it is.

I've just got a strange thing : i launch the game > the tracker detect it.
I re-launch the game, the tracker doesn't detect it. BUT i've seen a small white window that disappeared as fast as it appeared (too fast to make a screen shot). I think it's the answer if we know what it is... (i don't see it the first time when the tracker detect the game).
I do my best to get it on screen and make a screenshot (or see the process in the taskmanager... )

**Comment by Yooops** [comment]
Just got it : 
![image](https://user-images.githubusercontent.com/58131537/69492936-bad46e00-0ea8-11ea-9ea8-9ead9574110a.png)

**Comment by Yooops** [comment]
Here is the MTGALauncher Log :
[MTGAInstall.log](https://github.com/Razviar/mtgap/files/3883430/MTGAInstall.log)

"doormat error". Don't know if it is linked... (the game works perfectly well)

**Comment by patmey** [comment]
Same problem here as well.

I also run 64-bit windows 7.

Interestingly the tracker works when I let the Arena client start first and start the tracker when I'm in the main menu.

**Comment by VicNumber21** [comment]
The same for me.
The workaround is go to Settings, click Locate Log and select the latest log there.
After that it works fine until MGTA restart.

**Comment by VicNumber21** [comment]
Just verified: looks like it was fixed for me in https://github.com/Razviar/mtgap/releases/tag/v2.0.14
I reset path to Default Log Path in settings and now it detects that game is running without manipulations with Log Path.
Did not work like that on previous release (I tried).
