### ISSUE TITLE
White screen

### ISSUE THREAD

**Issue by ionelFR** [Razviar/mtgap#80]
I downloaded and installed mtga pro tracker 2.0.33, When launched, i only observe a white screen.

I also tried with 2.0.30
![Capture](https://user-images.githubusercontent.com/60568080/73606247-b2836800-45a8-11ea-83bc-d13266cf2d46.JPG)

**Comment by Razviar** [comment]
This might be electron bug. We can't reproduce it and do anything about it

**Comment by Razviar** [comment]
Try 2.0.35 version, it has updated Electron v8, may be working
