### ISSUE TITLE
The notation of the result is not uniform.

### ISSUE THREAD

**Issue by stormcat664** [Razviar/mtgap#82]
![01](https://user-images.githubusercontent.com/52299273/74098942-446b1200-4b61-11ea-9d95-14f01ec3c45f.jpg)
There are the following four patterns in BO1.
1:0 win, 0:1 win, 1:0 loss, 0:1 loss

**Comment by Razviar** [comment]
This is expected behavior. Score is shown in format [team1]:[team2] , and it's always random which team you are in. That is why we are "win" or "loss" mark on the top
