### ISSUE TITLE
Collection export results in a CSV with no contents (only the header row)

### ISSUE THREAD

**Issue by jspillers** [Razviar/mtgap#84]
**Your Desktop (please complete the following information):**
- Chrome Version 80.0.3987.106 (Official Build) (64-bit) on Mac 10.14.5

**Describe the bug**
I try to export my collection to CSV and the resulting file does not contain any of my card data - only the header row

**To Reproduce**
1. Go to https://mtgarena.pro/collection/
2. Have cards in your collection
3. Press Export
4. No card data in the export file

**Screenshots**
![mtgarena_export_bug](https://user-images.githubusercontent.com/2891/75310593-6089d700-5822-11ea-8383-4b25fd750cee.gif)

**Comment by Razviar** [comment]
Thanks for reporting, now it's fixed.

**Comment by jspillers** [comment]
amazing - you are awesome!
