### ISSUE TITLE
Partial SQL query being exported on line two of collection CSV's

### ISSUE THREAD

**Issue by jspillers** [Razviar/mtgap#85]
**Your Desktop (please complete the following information):**
- all

**Describe the bug**
when exporting a CSV dump of a collection, there is a SQL query fragment on line 2

**To Reproduce**
1. Go to https://mtgarena.pro/collection
2. Export your collection
3. Open downloaded CSV
4. Line 2 contains ```select `cardid`,`cardnum` from `mtg_collections_struct` where `uid`=xxxxx"```

**Screenshots**
<img width="944" alt="Screen Shot 2020-02-26 at 11 18 10 AM" src="https://user-images.githubusercontent.com/2891/75364428-b8a7f400-5889-11ea-85cf-50252d5f97a5.png">

**Comment by jspillers** [comment]
And since this query was partially exposed in the download I thought I might share some observations as a fellow developer...

I am not sure what flavor of SQL you guys are using, but it looks to me like you are doing one `SELECT` per card and maybe even one `SELECT` per card column? 

The export is not slow in prod from my experience as a user, but you could drastically reduce the number of queries you are executing by using the "IN" operator and then iterating over the results. If you mapped all the UID's into an array and then built up your query something like so:

```
-- not sure card name exists on your table, but if it did you could select it as well

SELECT 
  `cardid`, `cardname`, `other_column`, `whatever` 
FROM 
  `mtg_collections_struct` 
WHERE
  uid IN ('uid1234', 'uid2345', ...);
```
and then iterate over the resulting collection to build up the CSV

I am most familiar with Postgresql, but almost all flavors of SQL are going to be very similar

examples in postgresql https://www.techonthenet.com/postgresql/in.php

**Comment by Razviar** [comment]
That was just forgotten line of code after debugging, now it's removed. 

We are getting the whole cards array with one query like you wrote. The query you've seen is getting basically collection and with next one we are getting cards details. If we were running several queries per card, server would be down all the time :D But thanks for your suggestion :)
