### ISSUE TITLE
Mythic Point Challenge's logs are not shown in Match history

### ISSUE THREAD

**Issue by stormcat664** [Razviar/mtgap#87]
**Your Desktop (please complete the following information):**
 - OS: [Windows 10]
 - App Version [2.0.37]

**Describe the bug**
Mythic Point Challenge's logs are shown on profile but not in Match history.(except for first match log)

**Screenshots**
![capture_001_01032020_162354](https://user-images.githubusercontent.com/52299273/75621630-1a45c680-5bda-11ea-8e50-7884cd7647b3.jpg)
![capture_002_01032020_162416](https://user-images.githubusercontent.com/52299273/75621631-1b76f380-5bda-11ea-8e22-f866cf302594.jpg)

**Comment by Razviar** [comment]
Please provide your mtgapro account link so we could check

**Comment by stormcat664** [comment]
sai#59664
mtga.cc/u/sai

**Comment by Razviar** [comment]
Thanks, we will investigate

**Comment by florianlauer** [comment]
Hi, i think I'm facing the same issue but for Draft games.
![image](https://user-images.githubusercontent.com/11716644/78260983-ed4d4200-74fe-11ea-8fe6-7c78cd75f152.png)
![image](https://user-images.githubusercontent.com/11716644/78261050-01913f00-74ff-11ea-8465-e5497fcd55e4.png)
I played 8 Draft matches on April 1st but only 2 are displayed in match history.
I'm on Win10. My profile is https://mtgarena.pro/u/Dyum
Let me know if you need more infos.

**Comment by Razviar** [comment]
Closing this in favor of #86 since it's the same nature issue
