### ISSUE TITLE
Selecting "New Player Experience" from sets removes almost every element of the collection progress interface

### ISSUE THREAD

**Issue by bqback** [Razviar/mtgap#89]
Including the set dropdown menu, so you can't even change it back, requiring a page refresh.
![image](https://user-images.githubusercontent.com/28458777/75820963-69dceb80-5dae-11ea-83b3-1b9afca44b0e.png)

**Comment by Razviar** [comment]
Currently we are completely rewriting progress page, since it's old and needs to be transferred to React. Hold on for a week it so, new version will be much better

**Comment by Razviar** [comment]
Fixed in updated page version
