### ISSUE TITLE
Causes MTGA Unity error and stops "untapped" add in 

### ISSUE THREAD

**Issue by Jelly-Flinger** [Razviar/mtgap#9]
Hi,

The new version of the app causes an error symbol on MTGA unity to appear and stops the untapped ad in from working. Untappeds overlay stops working and it stops untapped from recording data.

**Comment by Razviar** [comment]
Which new version are you referring to? v.2.0.12 ?

**Comment by Jelly-Flinger** [comment]
Sorry I meant any of the v2 I have tried so far. I just updated to v2.0.14.

The untapped overlay works now but its still not uploading data. When I stop mtgapro it works fine and I do not see the unity error.

**Comment by Razviar** [comment]
For now I wasn't able to reproduce this issue.

**Comment by Jelly-Flinger** [comment]
Thanks for checking! 

Uninstalled/reinstalled everything and maybe its OK now? Just played one game and both ad in are working. Will play a few more and if all good I will close the issue.

Great work on the app btw. I use it so much. Would have been incredibly sad if I had to pick between pro and untapped. Have a huge amount of data in both that's really improved my play.

**Comment by Razviar** [comment]
We are committed on making our app able to coexist with other trackers, so we'll keep monitoring this

**Comment by Jelly-Flinger** [comment]
The original issue looks to resolved. Many thanks for all your hard work!

 I do have another issue,  multiple identical rewards (repeated maybe 10 times). Its possibly just because I was messing about trying to read old logs and reinstalling? 

What are your thoughts? If its a one time issue I am not too upset.

**Comment by Razviar** [comment]
@Jelly-Flinger , Investigating this doubling rewards issue.

**Comment by Jelly-Flinger** [comment]
The tracker (2.014) had stopped at some point today so it missed some data. When I restarted it, the tracker  picked up all the missed rewards and did not seem to to duplicate. 

When I look back in my reward history there is a period where rewards are duplicated approx 20 times. I have not clicked "read old log" though.

I also checked and of the 4 cards I can see 20 times in the rewards log I have less than 4 copies of two of them. I guess this means my collection is not messed up.

Do you want me to click "read old log"?

**Comment by Jelly-Flinger** [comment]
The add in had shut down again. When I restarted (i did not shutdown MTGA first) it found all the log file but introduced multiple identical rewards.

**Comment by Razviar** [comment]
We are still investigating repeating rewards, no fix was applied yet.

**Comment by Razviar** [comment]
v16 with this issue fix is rolled out
