### ISSUE TITLE
If multiple "Show all cards..." elements are located in one day in the feed, all of them only expand the first one 

### ISSUE THREAD

**Issue by bqback** [Razviar/mtgap#90]
Clicking on either of them here
![image](https://user-images.githubusercontent.com/28458777/75821396-3c447200-5daf-11ea-8032-0bd773de1fa5.png)
will lead to this
![image](https://user-images.githubusercontent.com/28458777/75821422-49616100-5daf-11ea-9190-10a1e11d5156.png)
You can get my profile link from [this](https://github.com/Razviar/mtgap/issues/88) issue to test.
Tested on Chrome, Firefox and mobile Safari.

**Comment by Razviar** [comment]
Fixed
