### ISSUE TITLE
Collection progress web page no longer showes actual numbers on mouse hover

### ISSUE THREAD

**Issue by rat128** [Razviar/mtgap#92]
The collection page no longer shows the actual number of cards collected for a category when you hover in the progress section.  The percentages are nice but the number of cards is helpful for tracking set completion.  

Sorry this isn't a tracker issue but a website issue.  I wasn't sure where else to post it.

![image](https://user-images.githubusercontent.com/44983104/76176158-ff4cf680-6185-11ea-808f-52e9a1899530.png)

**Comment by Razviar** [comment]
Fix delivered

**Comment by rat128** [comment]
I've been checking every day.  This doesn't appear to be fixed. The hover still just displays the type(common, rare, etc.)

**Comment by Razviar** [comment]
@rat128 now you need to set mode selector to raw numbers, see details here: https://twitter.com/mtgapro/status/1236919001420357633

**Comment by rat128** [comment]
Cool.  I don't use twitter much but I'll start following you.  Thanks for all the sweet updates!
