### ISSUE TITLE
Where is the install directory? Where to start the Tracker?

### ISSUE THREAD

**Issue by diskdusk** [Razviar/mtgap#94]
- OS: Windows 10
 - App Version 2.0.37 (but also had this problem in previous versions)

I know this probably doesn't fit here, but I don't know where else to ask. If it's not appropriate here I will ask the Magic Arena reddit.

My Problem is: I can't choose where to install the tracker and while it starts after installing, if I quit it I don't know where the executable to start it again might be. I have to start the setup file and install the program again. I am sure I miss something very obvious here, but I just can't find out what it is. Thanks!

**Comment by Razviar** [comment]
Install directory is C:\Users\{USERNAME}\AppData\Local\mtgaprotracker

You also should get Start menu element able to launch tracker.
