### ISSUE TITLE
Mirage Lands

### ISSUE THREAD

**Issue by Lord-Priapus** [Razviar/mtgap#95]
**Your Desktop (please complete the following information):**
Windows 10]

**Describe the bug**
Imported two different decks from Arena, came back 56-57 cards. Went line by line and discovered the Mirage Lands are not appearing in MTGA

![Screenshot (47)](https://user-images.githubusercontent.com/45022793/77031336-ad6f5200-6977-11ea-9b92-7e265581c2ad.png)

**Screenshots**

**Comment by Razviar** [comment]
Cards are present in DB now.

**Comment by mmxxiii** [comment]
Mirage lands are not showing correct collector numbers. They all show up as "(MI) 0".
Here are the correct numbers as exported from MTGA:
Plains (MIR) 331
Island (MIR) 336
Swamp (MIR) 340
Mountain (MIR) 346
Forest (MIR) 347
