### ISSUE TITLE
Overlay shows all cards being played as opponents cards

### ISSUE THREAD

**Issue by ducksarefun** [Razviar/mtgap#96]
Hi there, 

The overlay shows all the cards that are played on the opponent side of the screen, no matter if I am the one who played them or not.
What is the issue here?

**Comment by Razviar** [comment]
We are currently investigating this issue, it's happening to very small portion of users and we don't know why yet. Can you please provide your raw log files? Note that log we need is in AppData\LocalLow\Wizards Of The Coast\MTGA folder, NOT in program files

Also, you can try to reinstall tracker and wipe settings and see if it helps

**Comment by winterbelow** [comment]
I have the same issue! Just installed it today. Is it possible that the program is reading the wrong log file? I have the game installed on a separate hard drive, so maybe that's the issue? A friend of mine also installed it today and had the same issue but fixed it by using the "wipe all settings" option and restarting everything. That solution didn't work for me, so maybe its something there?

I also can't change the log location since it says the log path is fine but is there a way for me to override that and make sure?

I've reinstalled and wiped multiple times.

**Comment by Razviar** [comment]
@winterbelow if it says log is fine, then you definitely shouldn't tinker with it.

Can you please get a lot from AppData\LocalLow\Wizards Of The Coast\MTGA folder so I can check it?

**Comment by winterbelow** [comment]
@Razviar I'm not sure where the folder is, my stuff is split between multiple hard drives and I'm pretty sure I've found multiple AppData folders, any suggestions where it might be?

Also, I played a game of Brawl after i posted my previous comment and it worked, but still doesn't work in bots or direct challenges against friends, haven't tested in other online game modes yet.

**Comment by Razviar** [comment]
Ah, bots and direct challenges are special modes we don't support yet.

**Comment by Av8orgamer** [comment]
I'm experiencing this problem in Brawl only. Every other mode (except special events) shows the decks/played cards correctly. However, in brawl, all the cards populate on the opponent's side. I checked my log file, and I'm not really sure what I'm looking at on it. Do you want me give it to you?

**Comment by jonculver** [comment]
I have this problem in draft - specifically premier draft (and also in bot matches, though the above suggests this might be expected). It works OK in normal play mode. Screenshot and log from AppData/LocalLow attached as requested above. Let me know if I can provide anything else of use.
![Screenshot 2020-05-06 13 33 57](https://user-images.githubusercontent.com/16334712/81178403-0cc50800-8fa0-11ea-8d78-d23b52363af5.png)
[output_log.txt](https://github.com/Razviar/mtgap/files/4586780/output_log.txt)

**Comment by nick1984-png** [comment]
I'm having the same issue. Razviar, what email address can I send the logs to? admin@mtgarena.pro did not work.

**Comment by Razviar** [comment]
@nick1984-png is issue persists all the time or happens in some matches only?

**Comment by nick1984-png** [comment]
It happens every time. It didn't at first, during the first couple days. I've only been using your tracker for about 4 days, and the last 2 days it's had this issue.

I've reinstalled multiple times, deleted the program files stale directory after uninstalling, wiped the settings through the UI, toggled every combination of settings, verified during a standard match (not against a bot). Nothing has worked.

**Comment by Razviar** [comment]
@nick1984-png can you please upload zipped logs with samples of such bugged matches to any could service and drop me a link?

**Comment by nick1984-png** [comment]
I don't want to upload the logs to this public discussion thread. admin@mtgarena.pro did not work and Github doesn't have a messaging feature it looks like. Can you reply back with your email address or an upload link?

**Comment by Razviar** [comment]
@nick1984-png admin@mtgarena.pro works, just not for attached files. Please mail a link to uploaded into the cloud file. Like here https://dropmefiles.com/

**Comment by Razviar** [comment]
Please try 2.0.47 and check if it helped

**Comment by nick1984-png** [comment]
How do you reset the opponent card list for games 2 and 3 in a Bo3 match?

**Comment by Razviar** [comment]
@nick1984-png should be from empty deck every time. How it looks like? We don't test much with bo3

**Comment by nick1984-png** [comment]
![2020-05-30 12_48_59-MTGA Pro Tracker](https://user-images.githubusercontent.com/65867217/83335902-87b6d100-a275-11ea-892d-448a25b75479.png)
This is what it looks like during game 2 or 3. It has cards from the previous game.

**Comment by Razviar** [comment]
This issue is resolved in 2.0.49
