### ISSUE TITLE
No Feed Tracking

### ISSUE THREAD

**Issue by Dingodan4711** [Razviar/mtgap#97]
Hello,

since the 28.03.2020 the Social Feed didn't update. The Matches and Booster etc. works well.
I've tried to wipe all settings and also installed the tracker new both with no success.
Tracker Version 2.0.38
Last successfully Feed was on the 28.03.2020 AM 1:31 (GMT+1)

**Comment by Razviar** [comment]
Hello! Have you tried to use "regenerate feed" button under your avatar?
In order to check anything I need a link to your profile.

**Comment by Dingodan4711** [comment]
Already tried.
After the Day change from the 28th to the 29th it has shown the Feed for the played time on the 29th correctly. The whole 28th day time is missing.
I try it today maybe it was only an hickup in the system.

**Comment by Dingodan4711** [comment]
Works well at the moment.
