### ISSUE TITLE
Ixalan set not showing in progress

### ISSUE THREAD

**Issue by stroki33** [Razviar/mtgap#98]
The website doesn't show Ixalan as a choice to filter during Progress or during Collection Manager.

**Comment by Razviar** [comment]
Thanks for noticing, fix delivered.

**Comment by stroki33** [comment]
You guys are awesome!!  Thanks for the quick resolution.  Noticed it a while ago but figured someone would see it and say something ... guess next time I should just be that person earlier.  I love your site to track my cards and help with drafting.
