### ISSUE TITLE
Opponent deck incompletely tracked

### ISSUE THREAD

**Issue by MAC-GH** [Razviar/mtgap#99]
Hello,

In my last match (against Sematimba#35036, see the attached log file) the opponent has completely milled himself (his Underrealm Lich helped with that) so his whole deck was available but as I look at his deck in my matches history I see some cards are incorrectly counted. His 4 Murderous Riders are there but he also had 2 Assassin's Trophy, 2 Agent of Treachery, 2 Thought Erasure but only one of each are counted in his deck. Could you have a look at this, please.

[UTC_Log - 03-31-2020 20.22.37.zip](https://github.com/Razviar/mtgap/files/4423143/UTC_Log.-.03-31-2020.20.22.37.zip)

- Link to your MTGA Pro account: Allirog#15154

 - Windows 10 x64
 - App ver. 2.0.38

Thanks and regards

**Comment by Razviar** [comment]
Hello! Currently mill mechanics are not being tracked correctly, we don't have proper solution for that. Thanks for log, it will help to replicate this bug

**Comment by MAC-GH** [comment]
Hello, ty for your reply. I understand that it is not simple and milling sometimes goes with reanimation to complicate the things even further. I fear that a proper solution would imply to develop specific cases for milling/reanimating cards...

**Comment by MAC-GH** [comment]
Hello,

I would also add to this issue that only the cards that the opponent actually played are tracked and not the ones in his hand that were seen due to playing cards like Duress, Thought Erasure etc.

**Comment by Razviar** [comment]
@MAC-GH Hi! Thanks for sharing this special use cases, we will implement fix for them with next Tracker update.

**Comment by Razviar** [comment]
2.0.49 should address this issue

**Comment by MAC-GH** [comment]
Awesome, thanks for fixing this ! I love snooping at opponents decks after my matches to pick new ideas.
